### ISSUE TITLE
fix missing addon submodule

### ISSUE THREAD

**Issue by shahin** [greenplum-db/gpdb#1000]
Some build systems (like conda) break on missing submodules when checking out gpdb during automated builds. The [gpAux/addon submodule is missing](https://github.com/greenplum-db/gpdb/tree/058ac4f9ff7403b5834b9a3ab2631cb2083123fb/gpAux) on master, so updating submodules breaks, so automated builds on some systems (e.g. on conda) break.

It's not crazy to clone submodules when building a repo. The submodule here 404's, so this seems like an issue with gpdb's repo and not any particular build system.

Can we fix the gpaux/addon submodule, or remove it until it can be fixed?

**Comment by ascherbaum-pivotal** [comment]
@hlinnaka You know thet status of that submodule?

**Comment by hlinnaka** [comment]
On 08/18/2016 12:38 AM, Andreas Scherbaum wrote:
> @hlinnaka You know thet status of that submodule?

Hmm, I think it contained some proprietary code that Pivotal couldn't 
open source because of whatever reasons, when we released the rest of 
the code. I'm surprised it's still there, though, I thought we would get 
rid of it pretty quickly. I don't think there's anything interesting 
there; I don't have that submodule checked out on my laptop, and 
everything works fine without it.

@schubert, do you know the current status of the 'addon' submodule?
- Heikki

**Comment by adam8157** [comment]
Thanks @shahin  for the report! Closing this issue. Please reopen if the issue persists.
