### ISSUE TITLE
org.postgresql.util.PSQLException: FATAL: Unexpected internal error (postgres.c:886)

### ISSUE THREAD

**Issue by clmyyclm** [greenplum-db/gpdb#1001]
hello!
When I used JDBC to operate Greenplum, I get an error:

**org.postgresql.util.PSQLException: FATAL: Unexpected internal error (postgres.c:886)
  detail：FailedAssertion("!(ActiveSnapshot != ((void *)0))", File: "postgres.c", Line: 886)**
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1592)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1327)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:192)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:451)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:350)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:343)

**# and then, greenplum changed into recovery mode**

Driver is postgresql;
I had tried many version:8.3-603.jdbc3/8.1-404.jdbc3/8.3-603.jdbc4/9.4-1201-jdbc41/9.2-1003-jdbc4
my jdk is 1.7

table ：
  CREATE TABLE test (
  id character varying(128),
  name character varying(256)
)WITH (
  OIDS=FALSE ) DISTRIBUTED BY (id);
ALTER TABLE test
  OWNER TO gpadmin;

java code:
public class JdbcGreenplumTest {
	private Connection connection;
	private void initConnection(String url, String user, String pwd) throws ClassNotFoundException, SQLException {
		Class.forName("org.postgresql.Driver");
		connection = DriverManager.getConnection(url, user, pwd);
	}
	private void operate() throws SQLException {
		String sql1 = "INSERT INTO test(id, name) VALUES (?, ?)";
		PreparedStatement ps = connection.prepareStatement(sql1);
		ps.setString(1, "test2");
		ps.setString(2, "test_name");
		ps.execute();
		ps.close();
	}
	private void closeConnection() throws SQLException {
		connection.close();	
	}
	public static void main(String[] args) throws ClassNotFoundException, SQLException
	{
		JdbcGreenplumTest test = new JdbcGreenplumTest();
		String url = "jdbc:postgresql://192.168.0.253:5432/DGI-APPLICATION";
		String user = "gpadmin";
		String pwd = "123456";
		test.initConnection(url, user, pwd);
		test.operate();
		test.closeConnection();
	}
}

anybody having any idea is welcome ..

**Comment by clmyyclm** [comment]
I usedthe latest source code today, and Error is:
FailedAssertion("!(ActiveSnapshot != ((void *)0))", File: "postgres.c", Line: 888)

DB didn't changed into recovery mode

**Comment by hlinnaka** [comment]
It is supported. There was a bug, introduced by the merge of PostgreSQL 8.3. The code to handle with query parameters was mismerged, and the ActiveSnapshot was reset too early.

Fixed, thanks for the report!

**Comment by mayukhghoshme** [comment]
Hi,

Is this issue fixed in 5.3.0? I am seeing the exact same issue that is mentioned here. Problem is the recurrence of the issue isnt consistent and happens some times. Here is stack trace:

2017-12-29 04:30:00.110187 EST,,,p2863,th0,,,2017-12-29 04:24:53 EST,0,con15498,cmd3595,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process
received signal SIGSEGV",,,,,,,0,,,,"1    0x923483 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x163
2    0x7f9db1777370 libpthread.so.0 <symbol not found> + 0xb1777370
3    0x5a8057 postgres transformStmt + 0x17
4    0x5aa169 postgres parse_analyze + 0x39
5    0x807614 postgres pg_analyze_and_rewrite + 0x24
6    0x8fc023 postgres RevalidateCachedPlanWithParams + 0x103
7    0x8070ea postgres <symbol not found> + 0x8070ea
8    0x809073 postgres PostgresMain + 0x9a3
9    0x7acd86 postgres <symbol not found> + 0x7acd86
10   0x7ae762 postgres PostmasterMain + 0xc52
11   0x4c6783 postgres main + 0x393
12   0x7f9db0ba8b35 libc.so.6 __libc_start_main + 0xf5
13   0x4c6d0f postgres <symbol not found> + 0x4c6d0f


This is prepared statement coming via JDBC connection. I had shared more details in the group:

https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-users/w78SRaqTU9A

-Mayukh
