### ISSUE TITLE
Use more QEs for computing-only slice

### ISSUE THREAD

**Issue by hidva** [greenplum-db/gpdb#10070]
Currently, the maximum size of Gang for a Slice is the number of primary segments. But in fact, we can use more QE to increase concurrency for some slices of pure computing. 

For example, in a 3 primary segments cluster. The plan for `SELECT * FROM t1 INNER JOIN t2 WHERE t1.col1 = t2.col1` may like this:

![image](https://user-images.githubusercontent.com/17427025/81472863-1d3de280-922d-11ea-83f9-9b59d8ff2394.png)

But we can use more QE for slice1, such as 6:

![image](https://user-images.githubusercontent.com/17427025/81472909-7d348900-922d-11ea-9f75-cd86e7fe94c7.png)

I have written a [demo](https://github.com/hidva/gpdb/compare/use-more-qe-for-computing-slice%5E1...hidva:use-more-qe-for-computing-slice)  that implements the feature, Could you guys help me to review this?

**Comment by kainwen** [comment]
Thanks for the demo.

There is a similar thread in gpdb-dev mailing list: 
https://groups.google.com/a/greenplum.org/forum/#!searchin/gpdb-dev/parallel$20scan%7Csort:date/gpdb-dev/S2DGbqxX7sc/K1S-9b7NAAAJ

I think you could refer to that proposal and discussion there.

Many of your contribution and ideas are very interesting. Maybe gpdb-dev is a better place to
discuss instead of github issue?
