### ISSUE TITLE
CLUSTER command fails when it's run after previously aborted CLUSTER.

### ISSUE THREAD

**Issue by asimrp** [greenplum-db/gpdb#10150]
### Greenplum version or build
master (7x)
### Expected behavior
CLUSTER command finishes successfully when it runs after a previously aborted CLUSTER command on the same table.

### Actual behavior
The second CLUSTER command fails.

### Step to reproduce the behavior
```SQL
create table foo (a int, b varchar, c int) distributed by (a);
insert into foo select i, 'initial insert' || i, i from generate_series(1,10000)i;
create index ifoo on foo using btree (b);
-- execute cluster in a transaction but don't commit the transaction
begin;
cluster foo using ifoo; 
abort;

-- try cluster again, this time it fails
cluster foo using ifoo;
ERROR:  found xmin 622 from before relfrozenxid 623  (seg2 127.0.0.1:7004 pid=8696)
```

**Comment by asimrp** [comment]
@x4m FYI, since you expressed interest in this issue.

**Comment by x4m** [comment]
The problem seems to be caused by the fact that vac_update_relstats() violates transaction semantics. It updates pg_class in-place.
It is used to swap statistics. And it is used only in CLUSTER. And, basically, it should not.

I can create more transactional version of vac_update_relstats() but I do not see a reason for this, AFAICS numbers of tuples\pages are updated in a transaction way by nearby code.

Is it really that useful? As far as I can postgres does not do it.
```
/* swap size statistics too, since new rel has freshly-updated stats */
	if (swap_stats)
	{
		rel = relation_open(r1, AccessShareLock);
		vac_update_relstats(rel, relform1->relpages, relform1->reltuples,
							relform1->relallvisible,
							relform1->relhaspkey,
							relform1->relfrozenxid,
							relform1->relminmxid,
							false,
							true /* isvacuum */);
		relation_close(rel, AccessShareLock);
	}
```

**Comment by x4m** [comment]
The problem was intoroduced by #7040. If I simply remove vac_update_relstats() call - no relevant tests fail. Yet I'm leaning towards implementation of transactional vac_update_relstats().
