### ISSUE TITLE
Replicated table has inconsistent content after UPDATE

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#10226]
### Greenplum version or build
6X_STABLE, master

### Step to reproduce the behavior

If you update a replicated table with a volatile expression, the rows get different values on different segments. For example:
```
create table rpt (i int4) distributed replicated;
insert into rpt select g from generate_series(1, 10) g;
update rpt set i = random()*100;
```
Now connect in utility mode to each segment, and check the contents of the table. They are different on different segments:
```
$ PGOPTIONS=-cgp_session_role=utility psql postgres  -p 40000 -c "SELECT * FROM rpt ORDER BY i"
 i  
----
  9
 12
 14
 20
 27
 41
 48
 63
 78
 96
(10 rows)

$ PGOPTIONS=-cgp_session_role=utility psql postgres  -p 40001 -c "SELECT * FROM rpt ORDER BY i"
 i  
----
  5
 12
 26
 38
 54
 56
 72
 73
 85
 97
(10 rows)

$ PGOPTIONS=-cgp_session_role=utility psql postgres  -p 40002 -c "SELECT * FROM rpt ORDER BY i"
 i  
----
  1
 24
 34
 44
 66
 67
 80
 82
 98
 99
(10 rows)

```

**Comment by kainwen** [comment]
Another similar issue for volatile functions in replicated table query is:

```sql
gpadmin=# create table t(a int) distributed replicated;
CREATE TABLE
gpadmin=# explain update t set a = 0 where a < random();
                          QUERY PLAN
---------------------------------------------------------------
 Update on t  (cost=0.00..1785.25 rows=10700 width=14)
   ->  Seq Scan on t  (cost=0.00..1785.25 rows=10700 width=14)
         Filter: ((a)::double precision < random())
 Optimizer: Postgres query optimizer
(4 rows)

```

That is the qual contains volatile functions.

----------------------------------------------------------------------

The key of this bug is: for update-statement on replicated table, we have to dispatch the same plan to each segment to execute. And the assumption here (or the pre-condition we have to satisfy) is the plan gives the same result when invoking many times.

So I think we can simply reject replicated table with volatile function usage. Replicated table should be small and it can use simple work around if user has to use this kind of statement.

**Comment by kainwen** [comment]
This issue is a sub-case of a wider issue: https://github.com/greenplum-db/gpdb/issues/10419

So close this.
