### ISSUE TITLE
Concurrent updates cause data increase when use orca

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#10382]
### Greenplum version or build
6.5

### OS version and uname -a
centos 7.2

### Step to reproduce the behavior
Concurrent updates cause data copy when use orca.
The attach file is table schema and data.
If you run the follow sql concurrently, you will see the data Increasing.
```
UPDATE cps_user SET last_time=1592922006   WHERE  uid = 117
```
[cps_user_data.txt](https://github.com/greenplum-db/gpdb/files/4841811/cps_user_data.txt)
[cps_user_schema.txt](https://github.com/greenplum-db/gpdb/files/4841777/cps_user_schema.txt)

**Comment by kainwen** [comment]
The reason is that DBA does not set `gp_enable_global_deadlock_detector`  correctly. He only sets the GUC for master.

We have logic on QEs that needs the GUC's value.

After setting the GUC correct all over the whole cluster, the issue should not happen again.

------------------

There is an issue on the GUC inconsistent for GDD: https://github.com/greenplum-db/gpdb/issues/10030

It seems we should fix that ASAP.

**Comment by kainwen** [comment]
@lambgong 

Finally, we decide to make the GUC `gp_enable_global_deadlock_detector` as doc says, a master only GUC.

* On master branch, pr https://github.com/greenplum-db/gpdb/pull/10401 has fixed the issue
* On 6X, pr https://github.com/greenplum-db/gpdb/pull/10408 has fixed the issue
