### ISSUE TITLE
A problem with lock usage when querying waiting resqueue, causing cluster performance degradation

### ISSUE THREAD

**Issue by ppggff** [greenplum-db/gpdb#10564]
In stressed clusters, after enabling resqueue, many backends are waiting for lock table's partition lock.
And the one backend that hold the partition lock is busying on destroying idle gangs.

Why do we go to destroy idle gangs while holding the partition lock?
The partition lock should be release as soon as possible.

The related code is at src/backend/utils/resscheduler/resqueue.c: 449-460

**Comment by zhangh43** [comment]
Partition lock is used to protect the shared memory hash table, we still refer to `LockMethodLocalHash` inside `ResWaitOnLock `. One idea is to move the `cdbcomponent_cleanupIdleQEs` logic into `ResProcSleep`. Since we also need to release the partition lock before we really sleep.
```
ResProcSleep(LOCKMODE lockmode, LOCALLOCK *locallock, void *incrementSet)
{
...

/* Ok to wait.*/
LWLockRelease(partitionLock);
+if (ResourceCleanupIdleGangs)
+{
+	cdbcomponent_cleanupIdleQEs(false);
+}
}
```
Another idea to to tuning GUC `resource_cleanup_gangs_on_wait`.

Do you have some stats on the waiting time of partition lock?

**Comment by ppggff** [comment]
Yea, I think move it into `ResProcSleep` is OK. Thanks a lot.

About stats on waiting time, I don't have a specific value. What was happening was that most processes were waiting on the partition lock.

**Comment by zhangh43** [comment]
@ppggff  Do you want to open a PR based on the discussion to optimize this resource queue issue?

**Comment by ppggff** [comment]
OK, PR https://github.com/greenplum-db/gpdb/pull/10585
