### ISSUE TITLE
Error when combining SET DISTRIBUTED BY with ADD COLUMN

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#10604]
### Greenplum version or build
Tested on 6X_STABLE

### Step to reproduce the behavior

```
postgres=# create table foo (i int) distributed by (i);
CREATE TABLE
postgres=# insert into foo values (1);
INSERT 0 1
postgres=# alter table foo  add column t text, set distributed by (t);
psql: ERROR:  invalid attribute number 2 (heaptuple.c:1231)  (seg1 slice1 127.0.0.1:40001 pid=16551) (heaptuple.c:1231)
```

**Comment by kainwen** [comment]
This issue is the strange execution：

1. on QD, it first add a column, not dispatch
2. then it execute set distribute by, invoking the function `ATExecSetDistributedBy`, that function will dispatch the CTAS query to execute, but on segment, the newly added column Alter statement has not yet dispatched!

**Comment by dpandhi-git** [comment]
With @ashwinstar tried on 7X

`postgres=# alter table foo set distributed by (t), add column t text;
ERROR:  column "t" does not exist`

**Comment by ashwinstar** [comment]
No plans to fix and hence closing. If we receive reports of the issue from field we will reevaluate to fix.
