### ISSUE TITLE
greenplum install fail

### ISSUE THREAD

**Issue by luowencai** [greenplum-db/gpdb#10696]
### Actual behavior
```
error: Failed dependencies:
        greenplum-db >= 6.0.0 is obsoleted by greenplum-db-6-6.10.1-1.el7.x86_64
```

### Step to reproduce the behavior
rpm -qa|grep gree
greenplum-db-6.0.0_beta.3-1.el7.x86_64
greenplum-db-6.5.0-1.el7.x86_64
greenplum-db-6.7.1-1.el7.x86_64
greenplum-db-6.1.0-1.el7.x86_64

mkdir /usr/local/gpdb_new_version/
rpm -hiv greenplum-db-6.10.1-rhel7-x86_64.rpm --prefix=/usr/local/gpdb_new_version/
error: Failed dependencies:
        greenplum-db >= 6.0.0 is obsoleted by greenplum-db-6-6.10.1-1.el7.x86_64
Am i need to unistall old version before update to 6.10.1?

**Comment by bradfordb-vmware** [comment]
The RPM package name was recently (GP 6.9.0 & GP 5.28.0) changed from `greenplum-db` to `greenplum-db-6` to help with users who wanted to update their Greenplum clusters from Greenplum 5.x to 6.x. (Note: The Greenplum 5.x packages were also renamed from `greenplum-db` to `greenplum-db-5`). Because of the package name change, `yum` would not see that the old and new packages were related, so we added metadata to mark the old `greenplum-db` package as being obsoleted.

You will either need to:

1. Uninstall the old `greenplum-db` package with `rpm` before installing the new `greenplum-db-6` RPM package
2. Use `yum ./<path-to-rpm-file>` to install the new RPM package and `yum` will take care of removing the old installation for you.
