### ISSUE TITLE
planner crash when run group by cube and cte

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#10997]
### Greenplum version or build
6.5

### OS version and uname -a
centos 7

### Step to reproduce the behavior

create a  table as follow:
```
create table t1 (ADJUSTID varchar(128), channel varchar(128), country text, PLATFORM varchar(32));

create table t2 (adjustid varchar(128), PLATFORM varchar(32));
```

run sql as follow:
```
WITH TEMP_STEP_1 AS (
                     SELECT 
                            CHANNEL,
                            COUNTRY,
                            ADJUSTID
                     FROM t1
                     WHERE PLATFORM IN ('google')
                  ),
     TEMP_STEP_2 AS (
                     SELECT 
                            ADJUSTID
                     FROM t2
                     WHERE PLATFORM IN ('google')
                  )


     SELECT
           A.CHANNEL
     FROM TEMP_STEP_1 A
     LEFT JOIN TEMP_STEP_2 B ON A.ADJUSTID = B.ADJUSTID
     GROUP BY CUBE(A.COUNTRY, A.CHANNEL)
```

Planner will crash。

**Comment by guofengrichard** [comment]
Thanks for the report! With the repro, I can see error: `ERROR:  no relation entry for relid 2 (relnode.c:246)`

**Comment by lambgong** [comment]
Do we have any solution here?

**Comment by guofengrichard** [comment]
I believe the culprit is how we add subroot for SubqueryScan node in `add_subroot_for_subqueryscan()`. Here we hard-codes its `simple_rel_array_size` to constant 2, assuming it only has one rangetable entry. But in its corresponding subplan, there might be Scan node that has scanrelid larger than 1.

Another founding is that if we always choose sharing plan, rather than common subplan copies,  we can avoid this issue. In `generate_list_subplans()`, we consider both input sharing plan and a list of common subplan copies, and choose the one which has the cheaper cost.

**Comment by guofengrichard** [comment]
> Do we have any solution here?

Sadly not yet for now.

**Comment by dpandhi-git** [comment]
decided not to fix
