### ISSUE TITLE
Management utils: Instead of sending output/error to /dev/null redirect them to log files 

### ISSUE THREAD

**Issue by bhuvnesh2703** [greenplum-db/gpdb#11114]
### Greenplum version or build
Gpdb Master/6

### Step to reproduce the behavior

There are several instances where the errors are sent to /dev/null, we should instead redirect them to log files. Similar issues fixed in gpinitsystem via https://github.com/greenplum-db/gpdb/pull/10949/files

**Comment by shrakesh** [comment]
For below files we don't to do anything because they are not used in any of our CM tools

bin/pythonSrc/subprocess32/test_subprocess32.py
bin/gpload_test/gpload2/TEST_local_base.py
bin/gpload_test/gpload2/TEST.py
bin/gpload_test/gpload2/TEST_REMOTE.py
bin/gpload_test/gpload/TEST.py
bin/Makefile
test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
test/behave/mgmt_utils/steps/mgmt_utils.py
test/behave_utils/gpfdist_utils/gpfdist_mgmt.py
bin/generate-greenplum-path.sh

For below files we don't need to do anything because the output to dev/null is used as input further, the command itself then get logged

bin/lib/gp_bash_functions.sh
bin/gppylib/commands/unix.py
bin/gpcheckperf
bin/pythonSrc/subprocess32/subprocess32.py
bin/lib/pexpect/pxssh.py
bin/gppylib/util/ssh_utils.py
bin/gppylib/operations/package.py
bin/gpssh-exkeys
bin/gpinitsystem

example code snippet from unix.py:
```
cmdStr = "%s -an 2>/dev/null | %s %s | %s '{print $NF}'" % \
                 (findCmdInPath('netstat'), findCmdInPath('grep'), file, findCmdInPath('awk'))
```
