### ISSUE TITLE
gprecoverseg might want to use no-sync sometimes in pg_basebackup/pg_rewind.

### ISSUE THREAD

**Issue by paul-guo-** [greenplum-db/gpdb#11393]
We've seen in some scenarios that there are a lot of postgres nodes are down somehow. In such case we might want to run with no-sync option in pg_basebackup/pg_rewind for such cases and then run sync finally on those affected hosts.

The motivation is that

1. In gprecoverseg, pg_basebackup/pg_rewind will fsync all the files in the pg data which is time-consuming and sometimes not needed (for example in pg_rewind case probably most files are not needed for fsync since they were identical on both sides).

2. Usually multiple primaries/mirrors are configured on one host.

3. If there are multiple postgres nodes on one or more hosts are down, we could think about using the no-sync option to skip the final fsync steps but finally call sync on those affected hosts once. Sync-ing the kernel cache (page cache, inode, dentry) would be faster than open/fsync/close those files one by one sometimes.

One concern is that it seems that sync is not friendly for data integrity with disk cache, but nobarrier+xfs (we recommended) on old kernel, or battery-backed disk, or higher version kernel (no nobarrier but data integrity is ensured for such case) can ensure sync function call is ok for data integrity.

gprecoverseg might want to smartly decide what solution (previous one vs this one) depends on the failed postgres instances info.

**Comment by ashwinstar** [comment]
Integrity is more important compared to speed. Biggest doubt I have about the proposed approach is if host has 2 segment (content 1 and content2) pair to recover. Lets say content 0 completes incremental / full recovery but content 2 yet to complete. Content 0 will be marked in SYNC (content 1 yet will remain in non-sync state). gprecoverseg will not sync since yet to complete recovery for all the segments on this host. If power-outage happens in such situation, content 0's mirror will loose the data. That's too much risk to take. Hence, feel we should stick to syncing on per data directory basis only instead of per host basis.

**Comment by paul-guo-** [comment]
Closing this one since we use the solution in https://github.com/greenplum-db/gpdb/pull/11881
