### ISSUE TITLE
Failed to build postgres_fdw on macOS "ld: unknown option: --exclude-libs=libpq.a"

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#11523]
On macOS, postgres_fdw is failed to build, with an error "ld: unknown option: --exclude-libs=libpq.a"

It was introduced by https://github.com/greenplum-db/gpdb/pull/10617.

**Comment by lij55** [comment]
This is the known issue of https://github.com/greenplum-db/gpdb/pull/11524. Again, as mentioned in this comment: https://github.com/greenplum-db/gpdb/pull/10617#issuecomment-675348620, old behavior is worng because it linked to a wrong backend library and it has known security issue. 

This (https://github.com/greenplum-db/gpdb/pull/9462) should be the one that need reverting

**Comment by adam8157** [comment]
You were referring to the wrong link of "the known issue", I'm reopening this.

I'm OK with hacking to link to the frontend library, this issue is only about the macOS building issue.

**Comment by adam8157** [comment]
Why was this closed?

**Comment by lij55** [comment]
I believe there are duplicated issue (for example, https://github.com/greenplum-db/gpdb/issues/11400). please don't reopen this one any more.

**Comment by lij55** [comment]
these are are other known libpq related link on mac: https://github.com/greenplum-db/gpdb/issues/3215 https://github.com/greenplum-db/gpdb/issues/7101 as well. which is out of our current knowledge now.

**Comment by adam8157** [comment]
Fixed by #14464
