### ISSUE TITLE
Unable to use trigger for TRUNCATE statement

### ISSUE THREAD

**Issue by dbhao** [greenplum-db/gpdb#12045]
### Greenplum version or build
master

Hi @adam8157,
It seems master has disabled statement-level trigger by this [commit](https://github.com/greenplum-db/gpdb/commit/2325cffa86fa663567693cf54d5a98e7d5ed665f)

This change makes the following case no longer works. This is a use-case that simply checks and forbids TRUNCATE on a certain table, but now it says "ERROR:  Triggers for statements are not yet supported".
```SQL
postgres=# CREATE TRIGGER apm_policy_class_protect2 BEFORE TRUNCATE
postgres-# ON apm_policy_class
postgres-# EXECUTE FUNCTION _apm_metadata_protect();
ERROR:  Triggers for statements are not yet supported
```
Is there any workaround?
Hao

**Comment by adam8157** [comment]
Seems I disabled too much, I was planning to disable `referencing new table as ... for each statement` only.

Will fix it someday, PR is welcome too :)

**Comment by xianglli** [comment]
> ~Seems I disabled too much, I was planning to disable `referencing new table as ... for each statement` only.~
> 
> I disabled the trigger for statements while merging Postgres 12 into Greenplum, because Greenplum never supports it, and its behavior is kind of "undefined" in most cases.
> 
> Might fix it someday, PR is welcome too :)

I am curoius why it is hard to write statement triggle, what is the difference of the triggers in PG and GP? Or just unnecessary?
I am trying to work on the statement trigger though.

**Comment by adam8157** [comment]
It's hard because the statement trigger is cluster level but some triggers run on segments, we don't have clear rules when and where the statement triggers ought to work, yet.

It's a common issue for multi nodes clusters as I know.

**Comment by adam8157** [comment]
Note for people interested:

1, The REFERENCING option is almost certain to fail because it enables collection of transition relations, which are row sets that include all of the rows inserted, deleted, or modified by the current SQL statement. This feature lets the trigger see a global view of what the statement did, not just one row at a time. It is difficult for multi nodes clusters since triggers run on the nodes, they can't see the global view.

2, Other statement-level triggers also have issues, for example, what if the users want to `EXECUTE FUNCTION` for the whole cluster? The behavior is undefined in most cases.

We are reviewing this disabling decision and its reasons, ideas are welcome.
