### ISSUE TITLE
could not serialize unrecognized node type: 2139062143 (outfast.c:1817)

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#12448]
### Greenplum version or build
master branch

![image](https://user-images.githubusercontent.com/7367189/129470274-e607adc7-125f-4b22-a8e3-9725292ebf9c.png)

### Step to reproduce the behavior
```
CREATE OR REPLACE FUNCTION public.abc()
 RETURNS refcursor
 LANGUAGE plpgsql
AS $function$declare cname refcursor = 'result'; begin open cname for select 1; raise sqlstate '02000'; return cname; exception when sqlstate '02000' then  return cname; end;$function$;

```
Executing the following stmt will emit `ERROR: could not serialize unrecognized node type: 2139062143 (outfast.c:1817)`

`select abc() as a into temporary _aaaa;
`
The stack when error occurs, this is because List `oidAssignments` is something abnormal:
![image](https://user-images.githubusercontent.com/7367189/129470171-d406b2a9-ce3e-460c-9f42-77329332a31a.png)

After researching this problem, I locate the root cause:

Executing function abc() will begin a subtransaction, but since the function will raise error, this subtransaction will be rollback.
However, when rollback substransacion, `DispatchOids` will be released in `AtEOXact_DispatchOids`. So the parent transaction will got an invalid DispatchOid list.

To fix this problem, I think we should  remove `AtEOXact_DispatchOids` from `AbortSubTransaction()`. Correct me if I am wrong. 

Thanks.

**Comment by kainwen** [comment]
Hi @dreamedcheng 
Thanks for reporting this issue. I just spend several minutes debugging this problem.

It seems memory context issue, If I simply add this following copy, it works well:

```diff
diff --git a/src/backend/executor/execMain.c b/src/backend/executor/execMain.c
index a831464907..9d704666ac 100644
--- a/src/backend/executor/execMain.c
+++ b/src/backend/executor/execMain.c
@@ -585,7 +585,7 @@ standard_ExecutorStart(QueryDesc *queryDesc, int eflags)
                        if (queryDesc->ddesc != NULL)
                        {
                                queryDesc->ddesc->sliceTable = estate->es_sliceTable;
-                               toplevelOidCache = GetAssignedOidsForDispatch();
+                               toplevelOidCache = copyObject(GetAssignedOidsForDispatch());
                        }

                        /*
```

The reason is that your case SQL plan contains InitPlan (and that initPlan executes on master), and the InitPlan invokes the UDF which raises an exception.

The above diff only handles the specific pattern.  For example, if I force the UDF executes in segments, the issue does not happen:

```sql
CREATE 
OR REPLACE FUNCTION public.abcd() RETURNS refcursor LANGUAGE plpgsql AS $function$declare cname refcursor = 'result';
begin open cname for 
select 
  1;
raise sqlstate '02000';
return cname;
exception when sqlstate '02000' then return cname;
end;
$function$
execute on ALL SEGMENTS;
```

Then execute it will not impact the oid_dispatch:

```

gpadmin=#  select abcd() as a into temporary _aaaa;
psql: NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named '' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
psql: ERROR:  relation "_aaaa" already exists
```

----------------------------------------------------

So, some advice to push this work:

1. can we find another case that **QD process reset dispatch OIDs and then dispatch the plan** (your case is an example, the pattern is mentioned above, InitPlan + CTAS), but is there others? I try some cases, not manage to build one.
2. can we help verify if the previous versions of gpdb have this issue?
3. For initplan+ctas pattern, can we find which memcontext is removed? 
4. Finally, would you please open a pr for this?

Thanks @dreamedcheng again!

**Comment by dreamedcheng** [comment]
Thanks for the feedbacks:

  1. I can't find another case for now. To trigger this problem, QD should call `GetAssignedOidsForDispatch()` and a function 
before dispatch the plan. And searching the places where `GetAssignedOidsForDispatch()` is called, I think maybe no other case has the same problem.
  2. I tested it on 6X, 6X also has the same problem.
  3. I guess it's `Oid dispatch context`.
  4. I'll open one later.

**Comment by kainwen** [comment]
Previous version of gpdb does not have the issue because then gpdb allocate dispatch_oids in Topmemorycontext.

This is fixed by https://github.com/greenplum-db/gpdb/pull/12472 thanks @dreamedcheng
