### ISSUE TITLE
`MASTER ONLY` table support for HTAP-style use case

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpdb#12541]
Hi, Team,

Currently GPDB only supports storing user data in segment nodes with either `DISTRIBUTED` mode or `REPLICATED` mode.

But these are still dedicated for OLAP use and requires more complicated & restricted mechanism to handle concurrent activities.

We all know that a standalone PostgreSQL is a good OLTP database.

If GPDB can allow master node to store user data for OLTP style use, it might be better for GPDB to support HTAP use case; especially if GPDB 7.x is based on PostgreSQL v12, which is mature & robust for OLTP systems.

Best Regards.

**Comment by lij55** [comment]
Hi @CC-Hsu ,

thanks for the feature request. Single node postgres instance would always have better OLTP performance because it didn't need distributed transaction.
we would suggest another Postgres instance for the OLTP work and and Greenplum + postgres_fdw on master to access the Postgres as a work around for your use case. do you mind testing for its performance?

**Comment by CC-Hsu** [comment]
Hi, Jasper,

Thanks for your reply.

I tried `postgres_fdw` for bridging PGSQL and GPDB before.
But I find that sometimes `postgres_fdw` acts like a performance barrier due to pushdown implementation does not cover every situation.

So I think it's still better to utilize `mdw` node more.
