### ISSUE TITLE
Non-superuser should not be able to connect via utility mode

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#12566]
`PGOPTIONS='-c gp_role=utility' psql -U foo_user bar_database`

If the `foo_user` could touch `bar_database`, it could connect via utility mode too.

This seems not right to me, since utility mode could do things harmful to the cluster.

**Comment by adam8157** [comment]
Noticed this while reading https://github.com/greenplum-db/gpdb/issues/12217

**Comment by leskin-in** [comment]
The [documentation](https://docs.greenplum.org/6-16/admin_guide/managing/startstop.html) says:
```
Warning:

Incorrect use of maintenance mode connections can result in an inconsistent system state. Only Technical Support should perform this operation.
```

It does not actually forbid to use the utility mode, but serves as a precaution.

**Utility mode can be very useful** when applied correctly, as it enables a user to bypass limitations of the distributed transactions' system of GPDB: namely, that DML operations can only accept or output data through the coordinator. There is a mechanism that enables the user to export and import data in parallel (`FOREIGN` / `EXTERNAL` `TABLE`s and various tools based on this interface), and although it is powerful, it has limitations: firstly, its runs are user-driven (*GPDB* initiates all interactions, not some external system), and secondly, it enforces distributed transactions. Utility mode is much more flexible. Of course, it should be used with caution &mdash; but why put an **artificial** limitation on its use?

Role-based access control works well in utility mode as well, as users' privileges are replicated throughout the GPDB cluster.

Considering utility mode an another interface for Greenplum DB extensibility, its ban would make GPDB less extensible and would violate one of the core PostgreSQL principles &mdash; [extensibility](https://www.postgresql.org/docs/9.4/extend-how.html).

In order to limit the usage of utility mode, I suppose a GUC could be introduced to control its availability for ordinary users. This would preserve the currently available flexibility, but would also give extra safety to those who need it.

**Comment by adam8157** [comment]
That makes sense, closing this issue.
