### ISSUE TITLE
A share update exclusive lock occurs when execute insert tasks on a Non-Partitioned table via spark , and the Concurrency lost

### ISSUE THREAD

**Issue by hudingyi10** [greenplum-db/gpdb#12625]
## Bug Report
A share update exclusive lock occurs when execute insert tasks on a Non-Partitioned table via spark , and the Concurrency lost
### Greenplum version or build
6.16.0
### OS version and uname -a
centos 7
### Expected behavior
execute insert sql concurrently
### Actual behavior
A share update exclusive lock occurs when execute insert tasks on a Non-Partitioned table via spark , and the Concurrency lost

**Comment by kainwen** [comment]
I do not think this is a bug so I remove the bug label.

I believe this issue is because `insert` trigger `auto_stats` which might take a lock with the level of `share update exclusive`.

Would you please try set the GUC to none and then try again?  （Please refer to gpdb 6x's doc on the GUC: https://gpdb.docs.pivotal.io/6-17/ref_guide/config_params/guc-list.html)

```
gpconfig -c gp_autostats_mode -v none --masteronly
gpstop -u
```

**Comment by jimmyyih** [comment]
Yeah, it's most likely due to auto_stats and agree that it's not necessarily a bug.  One thing to note is that the `gp_autostats_mode` GUC can be set at session level as well with `SET gp_autostats_mode = none` which might be more manageable than configuring it for the entire GPDB cluster.

**Comment by kainwen** [comment]
Close this since I believe the above comments should work.

Feel free to re-open if needed.
