### ISSUE TITLE
Adding a GPDB-specific DB log GUC to specify log file directory

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpdb#13158]
## Feature Request

**Is your feature request related to a problem? Please describe:**
1. Currently all GPDB DB log directories are scattered across all `$PGDATA` of master/standby master/primary/mirror instances,
which is annoying for users when finding errors and housekeeping logs.
https://greenplum.docs.pivotal.io/6-19/best_practices/logfiles.html

2. When issuing `gpcheckseg` command, all affected `$PGDATA` are emptied, including their `pg_log/` subdirectories.
This makes tracking issues hard since logs are not kept after emergent `gprecoverseg` operations.

3. Currently the GUC parameters [`log_directory`](https://postgresqlco.nf/doc/en/param/log_filename/) and `log_filename` [in GPDB are locked](https://gpdb.docs.pivotal.io/6-19/ref_guide/config_params/guc-list.html) to prevent users from specifying custom location and filename.

4. It is annoying to perform log housekeeping inside all instances inside a GPDB cluster due to they all scattered across all instance directories.

**Describe the feature you'd like to request:**
1) Instead of unlocking `log_directory`, GPDB team may add another parameter `gp_log_directory`, 

2) Instead of unlocking `log_filename`, GPDB team may add another parameter `gp_log_filename`, 
and providing additional `%`-escapes to represent `<SEGID>` (just like what [`COPY ON SEGMENT`](https://gpdb.docs.pivotal.io/6-19/ref_guide/sql_commands/COPY.html) or [`gpbackup --backup-dir`](https://gpdb.docs.pivotal.io/backup-restore/1-24/utility_guide/ref/gpbackup.html) provides) and primary/mirror tag.
So that all instance logs on the same `sdw*` can be placed in the same directory.

In this case, one can point all GPDB instance logs to a dedicated log directory (e.g. `/var/log/gpdb/`).

Best Regards.

**Comment by ashwinstar** [comment]
Sure, I see the value in providing this option. It also helps to separate storage (like different filesystems and such) for actual data vs logging data.

Not currently convinced on the <SEGID> aspect in filenames, just because of the complexity it can bring in for single-host deployment kind of situations (with primary/mirroring roles can be flipped and such). We can explore alternative options in the longer term. Placing so many files in a single directory and performance impact to log rotation and such. Once we get to the implementation these aspects can be worked out.

If we have to expose this functionality seems fine to provide it via `log_directory` itself (unless some obvious blockers). Not sure why need to add gdb specific option.

(We in general have diffs in logging code compared to upstream and that needs to be removed as well, which is a separate effort from this.)

**Comment by ashwinstar** [comment]
I am closing this feature request given `log_directory` is implemented for 7X and helps to accomplish the required outcome.

For example I set `log_directory` to `/var/log/gpdb` and see all the logs populated to that directory (it creates sub-directories for dbid to avoid conflicts).
