### ISSUE TITLE
UDFs returning composite types potentially triggering unneeded executions

### ISSUE THREAD

**Issue by wjjung317** [greenplum-db/gpdb#1329]
From Robert in the DS team:

I noticed something odd.  When I have a PL/R function that returns a composite type and I call the function like this 

create table mdl as 
select (plr_func(…)).* 
from …

It calls the function once for each element of the composite type.  i.e. If the composite has 4 items, it runs four times.  If the composite type has 5 items, it runs five times!!!

On the other hand, if I make a nested select like this:

create table mdl as 
select (mdl).*
from (select (plr_func(…)) as mdl 
             from …
) t1

There is only one call.  

I checked this with pg.thrownotice() calls.  Is this a known issue?  
I cc'ed NYC Data since I thought this was an interesting feature of PL/R.

**Comment by hlinnaka** [comment]
Yeah, this is expected behavior. We've inherited that from the upstream. I couldn't find a reference right now, but I believe it's required by the SQL spec.

The "SELECT (compositetype).*" syntax is expanded in the parse analysis phase into:

SELECT compositetype.col1, compositetype.col2, ...

Hence, if "compositetype" is a function call, it gets expanded too, and called multiple times.
