### ISSUE TITLE
Getting no results when using a table valued function via join or IN condition

### ISSUE THREAD

**Issue by gaborremenyi** [greenplum-db/gpdb#13365]
## Bug Report

I have a table and a table valued function. They both work fine separately, but when trying to join the table valued function onto the table I'm getting no results. I have tried to use an IN condition instead of a join, but experienced the same behaviour.

### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.16.2 build commit:950f103fe23180ed0148552ef08cd62cbbf5a681) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Jun  3 2021 22:31:15

### OS version and uname -a
('Linux', '3.10.0-1160.59.1.el7.x86_64', '#1 SMP Wed Feb 23 16:47:03 UTC 2022', 'x86_64')

### Expected behavior
Using a table valued function via join or with an IN condition should return results.

### Actual behavior
Getting no results when using a table valued function via join or IN condition.

### Step to reproduce the behavior
```
create table testHeader (transactionId bigint, storeNo int);
insert into testHeader select i,3 from generate_series(1,10000) as t1(i);

create table testNumbers (testNumber int);
insert into testNumbers select i from generate_series(1,10) as t1(i);

-- create table valued function
create OR replace function secure_Test()
    returns TABLE(testNumberReturn integer)
    language plpgsql
as
$$
BEGIN
return query
    SELECT testNumber from testNumbers;
END
$$;

-- Running this query produces the below error message
SELECT T1.storeno
FROM testHeader AS T1
where t1.storeno in (select testNumberReturn from secure_Test());

-- [0A000] ERROR: function cannot execute on a QE slice because it accesses relation "bug_test.testnumbers" (entry db #.#.#.#:5432 pid=203178) Where: SQL statement "SELECT testNumber from testNumbers" PL/pgSQL function secure_test() line 3 at RETURN QUERY

-- To fix the error we've set the table distributed replicated;
alter table testNumbers set distributed replicated;

-- No results
SELECT T1.storeno
FROM testHeader AS T1
where t1.storeno in (select testNumberReturn from secure_Test());

-- No results
SELECT T1.storeno
FROM testHeader AS T1
INNER JOIN secure_Test() AS T2
ON (T2.testNumberReturn = T1.storeno);

**Comment by kainwen** [comment]
Actually, I do not think this is a bug, but at least Greenplum should throw an error when try to scan replicated table on master segment.

Greenplum is an MPP database, we do have some limitations from single instance Postgres.

UDF that invokes SQL is subtle in Greenplum because:

* only QD can dispatch, create gang and build interconnect
* Greenplum can only have one dispatch state at a time, means we cannot dispatch within a dispatch context.


Q1. why not replicated table, we hit the issue?  
A1: function cannot execute on a QE slice because it accesses relation: it is going to execute a distributed SQL on a QE, but QE cannot dispatch and create Gang

Q2: why replicated table no data?
A2: 
1. Replicated Table does not store data on Master
2. the function secure_Test is defaultly violation and execute anywhere (select provolatile, proexeclocation from pg_proc where proname = 'secure_Test'), thus this function in current gpdb planner’s code, will schedule on master to execute, (this seems can be changed, but that is a feature request)


--------

Work around:

To work around such case, DBA or users of Greenplum need to have a good knowledge .

Following is a workaround from me:

Method : execute on initplan

 When create a UDF, refer to the doc:  , read EXECUTE ON intplan related doc. In this method, distributed replicated, hash, or random all can work.

```sql
create OR replace function secure_Test() returns TABLE(testNumberReturn integer)
language plpgsql as
$$ BEGIN return query SELECT testNumber from testNumbers; END $$
execute on initplan;
```

**Comment by gaborremenyi** [comment]
Thanks [kainwen](https://github.com/kainwen) for the explanation and providing a work-around. It seems to have solve the issue.

**Comment by vishalrp** [comment]
Is this a work-around or a hack? 

Let me reframe the question then, since we have a ticket open with VMWare support as well.
We have a large table and we have a function that returns a small number of rows. We know the function will always return a small set of rows and the query is against a small table. 

By doing execute on initplan - we are able to run this query. What would be the caveat or issues with using that? Is there a better way to do this?

**Comment by kainwen** [comment]
> Is this a work-around or a hack?
> 
> Let me reframe the question then, since we have a ticket open with VMWare support as well. We have a large table and we have a function that returns a small number of rows. We know the function will always return a small set of rows and the query is against a small table.
> 
> By doing execute on initplan - we are able to run this query. What would be the caveat or issues with using that? Is there a better or more recommended way to do this?

It is a workaround for this case and if I remember correctly, `execute in initplan` is designed for such scenario.

And as you mention that 

> We know the function will always return a small set of rows and the query is against a small table.

This might be a solution.
