### ISSUE TITLE
Insert mass big bytea records issue

### ISSUE THREAD

**Issue by zeromax007** [greenplum-db/gpdb#1345]
When I insert mass big bytea records, maybe one record have 100 - 500MB. gpdb will report the follow error.

`ERROR:  Canceling query because of high VMEM usage. Used: 7378MB, available 792MB, red zone: 7372MB (runaway_cleaner.c:129)
CONTEXT:  SQL statement "select Ta.btyeacolumn from public.byteatable as Ta where random() < 0.13841724395751953125000000000000000000 limit 7500 "`

It looks like about this code https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/analyze.c  

When gpdb analyze table will select all columns, and then OOM.

**Comment by hlinnaka** [comment]
Hmm. ANALYZE grabs a sample of the table, and holds it in memory. If you have a lot of very large records, I can see that being a problem..

Looking at the corresponding upstream function, which we had to rewrite in GPDB to issue a SQL query, in order to have it work across the cluster, it doesn't detoast the columns. I guess that keeps the memory usage down in the upstream. Since we're fetching the results from the segment nodes, I don't think we can do the same in GPDB easily.

Perhaps we could modify acquire_sample_rows_by_query() to use a cursor and fetch only one row at a time, and check for exceedingly large datums and leave them out of the sample somehow. They're probably not very interesting from a statistics point of view anyway. I'm not sure how exactly to "leave them out of the sample", though. Pretend they're NULLs? Would skew the statistics for NULLs. Truncate them? Could do that for built-in datatypes like bytea or text, but not possible for the generic case (e.g. a huge PostGIS polygon).

Assigning to Venky, as the QP team is maintaining the ANALYZE code. (I believe, please re-assign if not)

**Comment by zeromax007** [comment]
How can I turn AUTO ANALYZE  off?

**Comment by bhuvnesh2703** [comment]
You can set the values of gp_autostats_mode to none. Refer to:
http://gpdb.docs.pivotal.io/4340/guc_config-gp_autostats_mode.html

Thanks,
Bhuvnesh Chaudhary
Email: bchau <bchaudhary@gopivotal.com>dhary@pivotal.io
Desk: +1-650-846-1696 | Mobile: +1-973-906-6976

**Comment by oarap** [comment]
The cursor idea is interesting but can you give us some more detail on how a cursor would handle the scenario where the SQL results of the sampling query already have large datum in it?

**Comment by hlinnaka** [comment]
On 03/03/2017 02:41 AM, Omer Arap wrote:
> The cursor idea is interesting but can you give us some more detail
> on how a cursor would handle the scenario where the SQL results of
> the sampling query already have large datum in it?

The point of using a cursor is that you would not hold the whole result 
set of the sampling query in memory at the same time, but only one row. 
There can be large datums on a row, but a single wide row shouldn't be 
enough to make you run out of memory. After fetching a row, if there are 
any really large datums, you would truncate or leave them out, before 
adding the row to the sample.

Now, it's still possible that you have a single row that contains 1000 
columns, and each column contains a 1 GB datum. Then you're still 
screwed. But at least it's a lot less likely, and I think you'll have 
trouble with e.g. pg_dump and restore with rows like that, anyway.

- Heikki

**Comment by oarap** [comment]
We have come up with two options: 
Let's say we have a table `foo(a int, b varchar, c varchar)`

1. First approach is to filter the huge rows in the sample. So, the select statement in `acquire_sample_rows_by_query` is going to look like 

```sql
SELECT * FROM foo WHERE random() < RANDOMTHRESHOLD AND pg_column_size(a)+pg_column_size(b)+pg_column_size(c) < TUPLESIZETHRESHOLD LIMIT SAMPLESIZE
``` 

This have a potential to cause skewed stats because of the tuples that we filtered.

2. The second option is to create samples with the large records replaced with `NULL` and have an auxiliary column that marks that tuple's that specific column is `NULL`ed. So, the sql statement would look like below:

```sql
SELECT a, 
(CASE WHEN pg_column_size(b) > COLUMNSIZETHRESHOLD THEN NULL ELSE b  END), 
(CASE WHEN pg_column_size(b) > COLUMNSIZETHRESHOLD THEN '1' ELSE '0'  END) AS case_b, 
(CASE WHEN pg_column_size(c) > COLUMNSIZETHRESHOLD THEN NULL ELSE c  END), 
(CASE WHEN pg_column_size(b) > COLUMNSIZETHRESHOLD THEN '1' ELSE '0'  END) AS case_c 
FROM foo LIMIT SAMPLESIZE;
```

We do not have to do the `CASE,WHEN` for the columns which are like integer types. 

Then, when we see a '1' in `case_b` column we can mark column `b` to be ignored for analyze for this particular sample. This aligns with the approach that we implemented in the pull request but avoids an extra `sql` statement and scanning the full table.  

Insights?

**Comment by oarap** [comment]
@hlinnaka What's your input for the options above?

**Comment by hlinnaka** [comment]
Yeah, those both seem workable. Option 2 is a bit more complicated, but will give better stats.

**Comment by vraghavan78** [comment]
I vote for Option 2.

**Comment by d** [comment]
Option 1 will lead to skewed samples: let's look at this scenario:
```
CREATE TABLE foo (a varchar(1024000000));
```
Our original random sampling
`SELECT a FROM foo WHERE random() < .38`

Returns a set of 8 samples: x1, x2, x3, x4, "y", "y", "z", "z". We use x1, x2, x3, and x4 to denote very large strings that will blow up our memory limit. Assuming the same random sequence, by moving the length check down to the filter, we have fundamentally changed the samples into: "y", "y", "z", "z". Now, the frequency of value "y" is estimated at 25% in the original sample, but now it will be mis-estimated as 50%.

**Comment by dhanashreek89** [comment]
Option#2 looks good.

**Comment by jpatel-pivotal** [comment]
#option2 looks good. 

However `pg_column_size(column)` gives you `toasted` value of the column's size  and we may want to figure out how to get the `detoasted` value as the difference could be 100x depending on the column type.   

Know of any built-in functions that get the detoasted length of a column?

**Comment by hlinnaka** [comment]
On 03/07/2017 08:53 PM, Jemish Patel wrote:
> #option2 looks good.
>
> However `pg_column_size(column)` gives you `toasted` value of the
> column's size  and we may want to figure out how to get the
> `detoasted` value as the difference could be 100x depending on the
> column type.

Good point. Yeah, we definitely need the detoasted size for this.

> Know of any built-in functions that get the detoasted length of a
> column?

Hmm, can't think of one off the top of my head. We could well write one 
for this purpose, though.

- Heikki

**Comment by dhanashreek89** [comment]
`octet_length()` gives the raw/detoasted length of the datum. `octet_length()` supports data types: bytea, text, character, bit

It is not polymorphic and hence it can not be used for User Defined Types. 

Approach to address this issue :
1. Numeric types or Fixed length user defined types:
    Always include the column in the sample.

2. Built in Variable length type :
    Use `octet_length()` to get the detoasted size and exclude the column if the size exceeds column_threshhold (uncompressed)

3. User defined variable length type :
    Check the toasted/compressed size and exclude the column if size exceeds column_threshhold (compressed)

```
  Create table foo 
  (
    a int,
    b bytea,
    c I_am_fixed_udt,
    d I_am_var_udt
  );
```
`I_am_fixed_udt` and `I_am_var_udt` are fixed length and variable length user defined types respectively.

The sampling query will look like :
```
SELECT a, 
(CASE WHEN octet_length(b) > COLUMNSIZETHRESHOLD_UNCOMPRESSED THEN NULL ELSE b  END), 
(CASE WHEN octet_length(b) > COLUMNSIZETHRESHOLD_UNCOMPRESSED THEN '1' ELSE '0'  END) AS case_b,
c,
(CASE WHEN pg_column_size(d) > COLUMNSIZETHRESHOLD_COMPRESSED THEN NULL ELSE d  END), 
(CASE WHEN pg_column_size(d) > COLUMNSIZETHRESHOLD_COMPRESSED THEN '1' ELSE '0'  END) AS case_d 
FROM foo LIMIT SAMPLESIZE;
```
This approach avoids creating a new system function/extending `octet_length()` to support UDTs.

Thoughts?

**Comment by hlinnaka** [comment]
Hmm. pg_column_size does actually return the detoasted size. However, got to be careful with the terminology here. If the column is compressed, pg_column_size returns the *compressed* size, whether or not it is also toasted. Are compressed datums transferred as compressed, from segments to the master? If they are, it's probably OK to fetch a datum that's huge when decompressed, but has been compressed to a small size. IOW, pg_column_size() will work fine for this purpose.

**Comment by bhuvnesh2703** [comment]
Yes, agreed, pg_column_size returns the compressed size (if compressed). 
When analyze gets the samples, i believe they are already uncompressed so in cases of columns like bytea if there is a huge string which is just a repetition of a single character, it might result in a very low compressed size but can cause the query to fail due to vmem issue, therefore using octet_length wherever applicable and pg_column_size for udt having variable length.

**Comment by vraghavan78** [comment]
https://github.com/greenplum-db/gpdb/pull/2156
