### ISSUE TITLE
Many Postgres processes are in the startup state for 2 hours

### ISSUE THREAD

**Issue by quentinliu** [greenplum-db/gpdb#13453]
## Bug Report
Many Postgres processes are in the startup state for 2 hours
### Greenplum version or build
6.19.1 build commit:0e314744a460630073b46cea7b7cf20a81e3da63
### OS version and uname -a
Linux bjcsi-dell-0-21 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
'--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/usr/local/gpdb'
### Installation information ( pg_config )
BINDIR = /usr/bin
DOCDIR = /usr/share/doc/pgsql
HTMLDIR = /usr/share/doc/pgsql
INCLUDEDIR = /usr/include
PKGINCLUDEDIR = /usr/include/pgsql
INCLUDEDIR-SERVER = /usr/include/pgsql/server
LIBDIR = /usr/lib64
PKGLIBDIR = /usr/lib64/pgsql
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/man
SHAREDIR = /usr/share/pgsql
SYSCONFDIR = /etc
PGXS = /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-rpath' '--with-perl' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-python' '--with-ldap' '--with-openssl' '--with-pam' '--with-krb5' '--with-gssapi' '--with-ossp-uuid' '--with-libxml' '--with-libxslt' '--enable-nls' '--enable-dtrace' '--with-selinux' '--with-system-tzdata=/usr/share/zoneinfo' '--datadir=/usr/share/pgsql' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0' 'LDFLAGS=-Wl,-z,relro '
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-z,relro -Wl,--as-needed
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgport -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lkrb5 -lcom_err -lgssapi_krb5 -lz -lreadline -lcrypt -ldl -lm 
VERSION = PostgreSQL 9.2.24
### Step to reproduce the behavior
The pg_attribute table is very large.
When executing vacuum pg_class or pg_attribute ，
This problem occurs when the pg_internal.init file does not exist.

**Comment by lij55** [comment]
Hi @quentinliu ,

do you mean that you manually deleted the pg_internal.init  file while running 'vacuum pg_class'?

**Comment by quentinliu** [comment]
@lij55
This phenomenon is related to pg_internal.init file is lost. 
The reason for the file loss is uncertain.

**Comment by quentinliu** [comment]
<img width="1424" alt="WechatIMG327" src="https://user-images.githubusercontent.com/8469303/167237765-389242bd-3a9a-42a3-b292-c29933babe31.png">

**Comment by quentinliu** [comment]
> Hi @quentinliu ,
> 
> do you mean that you manually deleted the pg_internal.init file while running 'vacuum pg_class'?
@lij55 
This phenomenon is related to pg_internal.init file is lost.
The reason for the file loss is uncertain.

**Comment by ashwinstar** [comment]
`RelationCacheInitFilePreInvalidate()` can remove the `pg_internal.init` file seems. Interesting scenario, might need to repro to understand the things better. Guessing during vacuum of large pg_class or pg_attribute, `pg_internal.init` is getting deleted. Though still unsure how that connects to processes being in startup phase, as the stack trace posted above just points to waiting for some buffer lock to be acquired.

**Comment by huansong** [comment]
The `pg_internal.init` is OK to miss since it's a normal process of invalidating the content when the content is modified. It will be reconstructed at backend startup. 

The stack trace shows that the stuck backend was waiting to read a buffer page for `pg_attribute` (frame 11) when trying to open `pg_am` (frame 14) in the process of loading critical index (frame 20), which is a normal process when `pg_internal.init` is not there. What's uncommon is that it tries to read block 145233 of `pg_attribute` (frame 7). This is too high of a position where system catalog attribute would be in `pg_attribute`. In addition, we will do heap scan when we don't have the critical index built yet (`criticalRelcachesBuilt==false`). So when a lot of new backends are doing that, they cause such a high IO contention and eventually lock each other out for a long time.

This is due to vacuum moving pg_attribute tuples for system catalog to a high block number. This has been encountered in production recently. @ashwinstar  opened this upstream thread for a proposal of fix: https://www.postgresql.org/message-id/flat/CAKSySwf%2BYH_4%3DUDosdyNG2%2BEYOFaThsATB9AfNkUjM4uq%2B69vQ%40mail.gmail.com

So will close this issue.
