### ISSUE TITLE
Using bitmap index will throw error after greenplum database restart

### ISSUE THREAD

**Issue by SmartKeyerror** [greenplum-db/gpdb#13517]
### Greenplum version or build

Just happened in 7.0-alpha, 6X-STABLE not yet reproduced

### Step to reproduce the behavior

```
create table test_bitmap(
    id int, msg text, type int
) distributed by (id);

insert into test_bitmap (id, msg, type)
select g, md5(g::text), random() * 1000 from generate_series(1, 10000000) g;

create index on test_bitmap using bitmap(type);

explain analyze select * from test_bitmap where type = 520;
```

After that, and keep this session alive, use `gpstoop -rai` to restart the whole database, and run above query again, will get an error:

```
-- after restart, create a new session
postgres=# set optimizer = false;set enable_seqscan = off;set enable_bitmapscan = off;
postgres=# explain analyze select * from test_bitmap where type = 520;
ERROR:  could not open file "base/13378/32768.1" (target block 4194304): previous segment is only 7752 blocks (md.c:1344)  (seg0 slice1 127.0.1.1:7002 pid=84567) (md.c:1344)
```

`base/13378/32768.1` is the heap storage file, not bitmap index file:

```
postgres=# select relkind,relname,relfilenode from pg_class where oid = 'test_bitmap'::regclass::oid;
 relkind |   relname   | relfilenode 
---------+-------------+-------------
 r       | test_bitmap |       32768
(1 row)

postgres=# select relkind,relname,relfilenode from pg_class where oid = 'test_bitmap_type_idx'::regclass::oid;
 relkind |       relname        | relfilenode 
---------+----------------------+-------------
 i       | test_bitmap_type_idx |       32771
(1 row)
```

**Comment by Aegeaner** [comment]
Will this issue still happen after removing the immediately mode option from `gpstop` ?

**Comment by SmartKeyerror** [comment]
> Will this issue still happen after removing the immediately mode option from `gpstop` ?

This issue will not happen after we end all sessions normally, in other words, `gpstop -ar` will not trigger this issue.

**Comment by dpandhi-git** [comment]
@SmartKeyerror can you confirm if its fixed

**Comment by huansong** [comment]
This is still happening on main branch. Although for me I didn't have to do
```
set optimizer = false;set enable_seqscan = off;set enable_bitmapscan = off;
```
The issue repro'ed with all the above being true/on. After doing the above, I actually couldn't repro'ed it.

**Comment by huansong** [comment]
RCA
------------
Firstly, the ERROR is because the bitmap header portion is corrupted:
```sql
-- (assuming pageinspect is installed)
postgres=# SELECT (bm_bitmap_page_header('test_bitmap_type_idx', p)).* from generate_series(3,10) p;
 num_words | next_blkno |  last_tid
-----------+------------+------------
      3968 |          0 |  299499648
      3968 |          0 |  299434112
      3968 |          0 |  300286272
      3968 |          0 |  301400384
      3968 |          0 |  302383168
      3968 |          0 |  302842112
      3968 |          0 |  303104320
      3968 |          0 |  303497536
```
The `next_blkno` indicates the next bitmap block for the same bitmap vector. It should be larger than 1 because block 0 is metapage and block 1 is LOV page. 

When we read a bitmap page, we will remember its `next_blkno` (in `*nextBlockNoP` in the following code), which is in turn used when we read the next batch:

https://github.com/greenplum-db/gpdb/blob/1ce9669a2a6769567204fde837123f93d7d68c54/src/backend/access/bitmap/bitmapsearch.c#L325-L331

So basically we would read block 0 and think it is a bitmap data page. We would decode random data from it like `target block 4194304` which is unreasonably large. That results in the ERROR.

Why bitmap header is corrupted? An interesting thing is that if we do `checkpoint` to make sure all bitmap data is persistent, then it won't get corrupted after `gpstop -air` and the ERROR will be gone. So apparently, there's something wrong with WAL for bitmap header, so that after crash recovery we are not able to restore the header properly.

Another interesting thing is that the other two fields in the header (`num_words` and `last_tid`) look fine. Only `next_blkno` is bad. That brings me to suspect this redo logic:
https://github.com/greenplum-db/gpdb/blob/4971f7852696a680717145a57d722fe1751b6a00/src/backend/access/bitmap/bitmapxlog.c#L263-L273

We are not reading `next_blkno` directly from the WAL but just deducing it from "the next page" which is simply decoded from the current WAL read position `xlrecptr`. Is that correct? Note that we are not doing the same when are "officially" decoding the next page:
```
xlrecptr = XLogRecGetBlockData(record, bmpageno + 1, NULL);
```

In fact, I tried to just remove that logic as a whole:
```
--- a/src/backend/access/bitmap/bitmapxlog.c
+++ b/src/backend/access/bitmap/bitmapxlog.c
@@ -263,7 +263,7 @@ _bitmap_xlog_insert_bitmapwords(XLogRecPtr lsn, XLogReaderState *record)
                        /* Update next pointer. Peek into the next struct to get its block number */
                        bitmapPageOpaque =
                                (BMBitmapOpaque) PageGetSpecialPointer(bitmapPage);
-                       if (bmpageno + 1 < xlrec->bm_num_pages)
+                       if (false && bmpageno + 1 < xlrec->bm_num_pages)
                        {
                                xl_bm_bitmapwords_perpage *next_xlrec_perpage;
```
... and the ERROR is gone. Here are the the `next_blkno` field in that case:
```
 num_words | next_blkno | last_tid
-----------+------------+-----------
      3968 | 4294967295 | 301531264
      3968 | 4294967295 | 301793536
      3968 | 4294967295 | 302252224
```
It seems that if we don't do anything, `next_blkno` is going to be initialized to `InvalidBlockNumber` and we won't try to read `InvalidBlockNumber` in `read_words`. And seems that we can still get to that page later somehow.

But note that **this is not a fix**, just to show where the problem is. The proper fix is to restore `next_blkno` to what it is set before the restart.

**Comment by SmartKeyerror** [comment]
Under @huansong 's outstanding work, I seem to have identified some issues. 

The root cause lies in the invocation of `XLogRegisterBufData()` to save Buffer-related data. Due to the possibility of requiring Full Page Write, the written data may be replaced by Full Image. Additionally, if there are holes in the Buffer, the XLOG system will use 2 blocks to store the same page. This can lead to an error in the execution of the code `bitmapPageOpaque->bm_bitmap_next = next_xlrec_perpage->bmp_blkno;`, resulting in incorrect data playback.
