### ISSUE TITLE
use imdb dataset as test cases to check optimizer's cardinality estimate or cost estimate quality

### ISSUE THREAD

**Issue by iwanttobepowerful** [greenplum-db/gpdb#13784]

**Comment by iwanttobepowerful** [comment]
@dgkimura thx.

**Comment by lij55** [comment]
Hi @iwanttobepowerful ,

do you mean you want Greenplum to embed dataset of IMDB dataset? its license seems complex:
[Non-Commercial Licensing](https://help.imdb.com/article/imdb/general-information/can-i-use-imdb-data-in-my-software/G5JTRESSHJBBHTGX?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=3aefe545-f8d3-4562-976a-e5eb47d1bb18&pf_rd_r=XMYCDGEGJNZ6J6VXS20N&pf_rd_s=center-1&pf_rd_t=60601&pf_rd_i=interfaces&ref_=fea_mn_lk1) and [copyright/license](http://www.imdb.com/Copyright?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=3aefe545-f8d3-4562-976a-e5eb47d1bb18&pf_rd_r=XMYCDGEGJNZ6J6VXS20N&pf_rd_s=center-1&pf_rd_t=60601&pf_rd_i=interfaces&ref_=fea_mn_lk2)

it is a legal issue instead of code or tech one so closing this issue.

**Comment by iwanttobepowerful** [comment]
@lij55 this issue is inspired by [Plan cost regression tests](https://github.com/duckdb/duckdb/pull/4033)

**Comment by lij55** [comment]
the test is wonderful and my only concern is about the dataset. it would be good if we could generate sample data by script, just as the duckdb does.
