### ISSUE TITLE
How to change the ssh default port of segment host?

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#14500]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Because the network scheme of the GP container cluster has changed, I want to change some ports of the existing cluster.

Do I just need to modify /etc/sshd_config for SSH Port?

For Segment Port, can I still change it? 

**Describe the feature you'd like to request:**

**Comment by cobolbaby** [comment]
Is it possible to modify the configuration in /etc/ssh/ssh_config?

**Comment by nimish350** [comment]
In order to change the segment port [specified in the table **gp_segment_configuration** under column "port"], you can take the following steps: 

1. Stop the specific segment using "pg_ctl stop". Confirm that the segment has been marked down in gp_segment_configuration table. 
2. Run gprecoverseg -o <file_name> to generate a output file. 
3. Modify the file generated in Step 2 and change the value of port. Example: 

```
sdw1|35033|/data/mirror/gp_6.25.3_202401151233391 sdw1|38000|/data/mirror/gp_6.25.3_202401151233391
```
**Notice that we only changed the port above from 35033 to 38000. 

4. Run gprecoverseg -i <file_name>. [Note that this will perform a full recovery of the segment] 

Once done, validate the change of port in the **gp_segment_configuration** table.

**Comment by nimish350** [comment]
@cobolbaby If ok I will close this issue.

**Comment by nimish350** [comment]
In order to change the ssh port, you can edit the following file: 

```
vi /etc/ssh/sshd_config
```

Change the default port for ssh from 22 to something else, save the file and restart sshd: 
```
service ssh restart
``` 

or 
```
systemctl restart sshd
```

**Comment by cobolbaby** [comment]
@nimish350 

Do I need to modify the /etc/ssh/ssh_config configuration?
