### ISSUE TITLE
Orca should support backward index scan to generate optimal plan

### ISSUE THREAD

**Issue by mingminghao** [greenplum-db/gpdb#14730]
## Enhancement
![image](https://user-images.githubusercontent.com/39397546/211178095-5bb2b64b-32fd-4683-be18-b83a24905528.png)

**Comment by kainwen** [comment]
Several points from the plan:

* Index scan on `<` and `>`
* index scan then sort (seems strange)

Can you please upload `mini repro` here?  (For minirepro usage please refer to https://community.pivotal.io/s/article/How-to-Collect-DDL-and-Statistics-Information-Using-the-Minirepro-Utility?language=en_US)

------

Optimization direction:

1. I'd suggest to use partition on `scheduled_time` so that using partition pruning to avoid much data scanning
2. or can you try to use planner to see if we can void the sort node in your case? Share the below result here.

```
set optimizer = 0;
set enable_seqscan = 0;
explain analyze + you SQL
```

**Comment by mingminghao** [comment]
![image](https://user-images.githubusercontent.com/39397546/211185230-03dc2df4-f1a2-468e-826e-f9cd39cc78b6.png)
set optimizer = 0 is effective;why?

**Comment by mingminghao** [comment]
set optimizer =0 is effective; why?
![image](https://user-images.githubusercontent.com/39397546/211185361-49626fa4-3bc5-4f6b-9bf8-0fbeb122fcbe.png)

**Comment by kainwen** [comment]
Index scan (btree) will output tuples in order so there is no need to add a sort node.

@gpopt would you please help see if it is an ORCA problem? Seems easy to reproduce.

@mingminghao Please upload minirepro here, thanks.

**Comment by gpopt** [comment]
Orca doesn't support backward index scan yet.
