### ISSUE TITLE
Kitchen Sink Binary Build - PXF, PLPython, PostGIS inclusion

### ISSUE THREAD

**Issue by inviscid** [greenplum-db/gpdb#14825]
## Feature Request

**Is your feature request related to a problem? Please describe:**
While you can certainly optimize the build process for Greenplum to minimize installed packages and size, there is a significant use case to have a binary that "just works" in all cases without having to build additional extensions or installing packages.

**Describe the feature you'd like to request:**
The latest binary build for Ubuntu is fantastic.  It makes the process of running basic Greenplum very straightforward.  However, the binary does not have PXF, PLPython, or PostGIS installed which we consider common tools for general Greenplum usage.

I would advocate that you maintain the current clean Greenplum builds but also add a kitchen sink build that includes many of the useful extensions and packages such as PXF, PLPython, and PostGIS so they work right out of the box.

I think this well help in adoption and overall happiness with Greenplum since there is a substantial difference between setting up a build machine and simply installing a binary.

In addition, with a binary, it is much easier to build Docker images and automate processes using deployment tools.

**Comment by kmacoskey** [comment]
Howdy @inviscid . I completely relate with the difficulties installing all of the many other optional components that work with Greenplum Database. This is something we are working on in the commercial releases of VMware Greenplum. We are choosing to keep each of the open source projects more focused - as an example in releases here, https://github.com/greenplum-db/gpdb/releases , you will only find Greenplum Database in the pre-built packages. The purpose is to only have the one OSS project in each respective release. 

What I suggest in place is to contribute to / work with each of the other respective components you are interested in if you have ideas on them being easier to install. As an example, PXF could benefit from an RPM/DEB package in the Github release / Launchpad PPA. This would make installing PXF and Greenplum both together much easier.

PostGIS will need to remain a separate project due to the requirements of it's open source license. It is not as compatible to combine into a single package for distribution.

PL/Python is already included within https://github.com/greenplum-db/gpdb , it's part of the code base here: https://github.com/greenplum-db/gpdb/tree/main/src/pl/plpython . I believe it's enabled by default in the build system so it should already be found in the pre-built packages created for the Github release / Launchpad.

**Comment by inviscid** [comment]
Thanks for the explanation.  My first few attempts at getting things to build using a Dockerfile have not been successful so I was looking for an easier path.  If I can get this working I will likely contribute it, if for nothing else but a reference.
