### ISSUE TITLE
unrecognized parameter "compresstype"

### ISSUE THREAD

**Issue by july-gyq** [greenplum-db/gpdb#14913]
unrecognized parameter "compresstype" is reported when the child table is not specified as an ao table.An error occurs when the operation is performed in mode 1. No error is reported when operating in mode 2

Mode One：
create table test1(c1 char(20),c2 varchar(20))
WITH (appendonly=true, compresstype=zlib, compresslevel=5,orientation=column) 
distributed by (c2) 
partition by list(c1)
(
partition p1 values(
'1ABC123abc,./')WITH (appendonly=false),
partition p2 values(
'31ABC123abc,./')WITH (appendonly=false),
default partition default_p WITH (appendonly=false)
);

Mode Two：
create table test2(c1 char(20),c2 varchar(20))
WITH (appendonly=true, compresstype=zlib, compresslevel=5,orientation=column) 
distributed by (c2) 
partition by list(c1)
(
partition p1 values(
'1ABC123abc,./')WITH (appendonly=true),
partition p2 values(
'31ABC123abc,./')WITH (appendonly=true),
default partition default_p WITH (appendonly=true)
);

**Comment by ashwinstar** [comment]
Would be helpful if can state reporting the issue for which GPDB version.

**Comment by huansong** [comment]
This is happening in 7X. But it is hard to argue that it's actually a bug:

It is expected that a child table get the reloptions specified for the parent, as long as it is not also specified for the child itself. For example in the "Mode Two" example you would expect that the child tables inherit `compresstype=zlib, compresslevel=5` which they indeed get. And if you specified e.g. `compresslevel=1" for the children, then they would get `compresstype=zlib,compresslevel=1`.

Think of it in another way: both these cases are equivalent to creating a partitioned table with desired AM, and then SET the reloptions from the parent. E.g. "Mode One" is equivalent to:

```
create table test1(c1 char(20),c2 varchar(20))
WITH (appendonly=true, orientation=column)
distributed by (c2)
partition by list(c1)
(
partition p1 values(
'1ABC123abc,./')WITH (appendonly=false),
partition p2 values(
'31ABC123abc,./')WITH (appendonly=false),
default partition default_p WITH (appendonly=false)
);
alter table test1 set (compresstype=zlib, compresslevel=5);
```

This will error out in GPDB7 as well. And that was a decision we made earlier: https://github.com/greenplum-db/gpdb/pull/13995#issuecomment-1233079541

However, the difference is that in the above case we would print a somewhat nicer message:
```
postgres=# alter table test1 set (compresstype=zlib, compresslevel=5);
ERROR:  cannot alter reloptions for "test1" because one of the child tables "test1_1_prt_default_p" has different access method
HINT:  Alter tables individually or change the child's AM to be same as parent.
```

But it is hard to do the same for CREATE TABLE because when setting reloptions for child table, we don't know whether it's inherited from the parent or specified for the child itself.

**Comment by july-gyq** [comment]
Why can orientation=column be identified by child tables in the mode you enumerated??? Is it because it is removed in the process of inheritance??? Instead, the following errors will not occur:

ERROR: invalid option "orientation" for base relation

HINT: Table orientation only valid for Append Optimized relations, create an AO relation to use table orientation.

**Comment by huansong** [comment]
@july-gyq The `orientation` is kinda special: it only works _**together**_ with `appendonly`|`appendoptimized` to indicate the access method (AM). It is not inherited by itself too. So in the example:

```
create table test1(c1 char(20),c2 varchar(20))
WITH (appendonly=true, orientation=column)
distributed by (c2)
partition by list(c1)
(
partition p1 values(
'1ABC123abc,./')WITH (appendonly=false),
partition p2 values(
'31ABC123abc,./')WITH (appendonly=false),
default partition default_p WITH (appendonly=false)
);
```

The `appendonly=true, orientation=column` together indicate "append-optimized column-oriented" (`ao_column`) AM. The `appendonly` and `orientation` are not inherited individually like other parameters (compresstype etc.), they are inherited together to indicate the AM. So if the child table doesn't have `appendonly`|`orientation` itself, it will have `ao_column`. However in this case the child table has `appendonly=false` which indicates "heap" AM, it will ignore the AM of the parent, which means that it ignores **both** `appendonly` and `orientation` from the parent.

For another example:

```
create table test1(c1 char(20),c2 varchar(20))
WITH (appendonly=true, orientation=column)
distributed by (c2)
partition by list(c1)
(
partition p1 values(
'1ABC123abc,./')WITH (appendonly=true),
partition p2 values(
'31ABC123abc,./')WITH (appendonly=true),
default partition default_p WITH (appendonly=true)
);
```

The child table in this case will have `ao_row`. It is not because it inherits `appendonly=true` and ignores `orientataion=column` from the parent, but it is ignoring **both** `appendonly` and `orientation` from the parent because itself has  `appendonly=true` which already indicates `ao_row` AM. 

I understand mixing AM in the storage parameters might make things complicated. But unfortunately we have to support that in 7X for backward compatibility. We [strongly recommend](https://docs.vmware.com/en/VMware-Tanzu-Greenplum/7/greenplum-database/GUID-ref_guide-sql_commands-CREATE_TABLE.html#:~:text=Note%3A%20Although%20you%20can%20specify%20the%20table%E2%80%99s%20access%20method%20using%20WITH) using the `USING <access_method>` syntax in `CREATE TABLE` command. But in Greenplum legacy syntax like creating child partitions with parent (i.e. `(partition p1 ..., partition p2 ...,)`), we still have to use the `WITH` clause. We might consider adding `USING <access_method>` in the legacy syntax too which I'll discuss with the team.

Thanks for your questions! I hope I have answered them. Lmk if you still have questions/concerns.

**Comment by huansong** [comment]
Re:
> We might consider adding USING <access_method> in the legacy syntax too which I'll discuss with the team.

After discussion we think that it's better that we don't mix new clauses with legacy syntaxes. So if one would like to use the `USING <access_method>` clause for child table, they should use the new syntaxes to create the child table too, e.g.:

```
create table test1(c1 char(20),c2 varchar(20))
using ao_column
distributed by (c2)
partition by list(c1);

create table p1 partition of test1
for values in ('1ABC123abc,./') 
using heap;
```
