### ISSUE TITLE
DDL `alter table ... add column ...` without default value will rewrite the whole table

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#14929]
### Greenplum version or build

- 6.23.0

### Expected behavior

In theory, if the default value is not set, the database background does not need to rewrite the whole table.

### Actual behavior

```sql
CREATE TABLE inframinio.archive_zip_info
(
    s3site_id smallint NOT NULL,
    path text NOT NULL,
    archiveds3site_id smallint,
    archivedpath character varying(256),
    path_hash character varying(10) NOT NULL,
    cdt bigint NOT NULL
)
WITH (
    OIDS = FALSE,
    APPENDONLY = TRUE,
    COMPRESSLEVEL = 5,
    COMPRESSTYPE = ZLIB
)
TABLESPACE tbs_ssd01
DISTRIBUTED BY (path)
PARTITION BY LIST(s3site_id) 
        (
        PARTITION pics VALUES(11), 
        PARTITION testlog VALUES(17), 
        DEFAULT PARTITION other
        );

insert into inframinio.archive_zip_info ...;

alter table inframinio.archive_zip_info add column deleted boolean;

-- ALTER TABLE
-- Query returned successfully in 8 min 22 secs.
```

**Comment by kainwen** [comment]
It seems your table append only and row oriented? If it is the case, then there has to be a rewrite of whole table.

**Comment by cobolbaby** [comment]
> It seems your table append only and row oriented

Yes. Doesn't this problem exist with the heap table?

**Comment by kainwen** [comment]
> > It seems your table append only and row oriented
> 
> Yes. Doesn't this problem exist with the heap table?

Yes. Postgres also has the problem. You can try.

Greenplum's AOCS table have some optimization.

**Comment by cobolbaby** [comment]
> Yes. Postgres also has the problem.

I didn't experience the wait when dealing with PG or GP heap tables.

**Comment by kainwen** [comment]
> ```sql
> alter table inframinio.archive_zip_info add column deleted boolean;
> ```

Ah you are right, I look into the code, and see there is a gpdb specific code (`tablecmds.c:ATExecAddColumn`) to resolve an old issue https://github.com/greenplum-db/gpdb/issues/3756

```c
         *
         * Currently memtuples cannot deal with the scenario where the number of
         * attributes in the tuple data don't match the attnum. We will generate an
         * explicit NULL default value and force a rewrite of the table below.
         *
         * At one point there were plans to restructure memtuples so that this
         * rewrite did not have to occur. An optimization was added to
         * column-oriented tables to avoid the rewrite, but it does not apply to
         * row-oriented tables. Eventually it would be nice to remove this
         * workaround; see GitHub issue
         *     https://github.com/greenplum-db/gpdb/issues/3756
         */

        if (!defval && RelationIsAppendOptimized(rel))
        {
            defval = (Expr *) makeNullConst(typeOid, -1, collOid);
        }

        if (defval)
        {
            NewColumnValue *newval;

            newval = (NewColumnValue *) palloc0(sizeof(NewColumnValue));
            newval->attnum = attribute.attnum;
            newval->expr = expression_planner(defval);

            /*
             * tab is null if this is called by "create or replace view" which
             * can't have any default value.
             */
            Assert(tab);
            tab->newvals = lappend(tab->newvals, newval);
            tab->rewrite = true;
        }
```

@ashwinstar not sure if the issue still there for gp7 or gp6. Reopen this.

**Comment by ashwinstar** [comment]
Yes still to be improve for AO/CO tables. https://github.com/greenplum-db/gpdb/issues/3756 captures the context for the same.

**Comment by huansong** [comment]
I looked at a related problem in https://github.com/greenplum-db/gpdb/pull/15071. Some thoughts about this issue:

Basically, I think the whole table rewrite issue for `ADD COLUMN` for AO/CO tables can be divided-and-conconquered in these sub-tasks:
(note that this is for 7X, not sure about 6X as it misses some important upstream feature)
1. Avoid table rewrite when adding a column w/ non-NULL default to `ao_column` table. Instead, we just do a column rewrite. This is a low-hanging fruit since we already have the capability to do that `ATAocsWriteNewColumns`. The above PR addresses it.
2. Avoid table rewrite when adding a column w/ NULL default to `ao_column` table and only do a column rewrite. From a logical standpoint we can do exactly the same as step i: writing a column w/ a non-NULL or NUL value shouldn't make a difference. We can try it in another PR.
3. Avoid table rewrite when adding a column w/ non-NULL default to `ao_row` table. This will leverage the [upstream's feature](https://github.com/huansong/gpdb/commit/16828d5c0273b4fe5f10f42588005f16b415b2d8) that default value is stored in catalog and doesn't need to be written to the table immediately. [This FIXME](https://github.com/greenplum-db/gpdb/blob/main/src/backend/commands/tablecmds.c#L7700-L7711) talks about the difficulty of it for `ao_row` tables: basically memtuple doesn't have the number of attributes stored with it, while heap tuple has (see `HeapTupleHeaderGetNatts`). However, some initial exploration seems to indicate that w/ what's available we should already have the knowledge about from which attribute we need to look up the default value (i.e. the "missing attributes"). The key observations are:
    1. The missing attributes are always at the end of the tuple, because whenever the tuple is rewritten with a non-default value, it is rewritten as a whole and the missing attributes will be filled with real data. After that, only new columns would be missing again. 
    2. In memtuple, the attribute descriptor indicates how the attribute will be stored in the tuple, and that is fixed (see `create_col_bind`, which doesn't need a real tuple). And, the memtuple's own length indicates how much data it really has. Using those two sources of information we should be able to construct the knowledge about how many attributes are missing.
4. Avoid table rewrite when adding a column w/ NULL default to `ao_row` table. I think this will be doable after step iii - it is just a matter of different missing values. But we might need to be aware of the memtuple's own null bitmask - by the time when we need to fill a missing value, the bitmask might give us wrong information about whether the attribute is being NULL or not which might impact our decision.
5. Avoid column rewrite when adding a NULL/non-NULL default to `ao_column` table. This will be a further improvement to i/ii. Haven't looked into the details. The benefit will be less though considering we would be just optimizing a column rewrite away.

Thoughts?

**Comment by huansong** [comment]
Regarding table rewrite in ADD COLUMN for ao_row (point 3 and 4 above):

I looked a bit more into the issue, and now agreed that it's better to add a "number of attributes" field to the memtuple:

* Prior idea was: we read the attribute in the memtuple one-by-one. Each time we try to read an attribute, we first compute the size considering only up to that attribute (could modify `compute_memtuple_size` to do that). If the computed length is larger than the actual length of the tuple, we know for sure that this attribute isn't there, and all the following attributes are missing as well.
* However, it turns out that there's a key problem: the attribute values/references in memtuple are **not placed according to attnum**. They are placed first according to the size of the attribute type, then the attnum (see `create_col_bind`). So adding a new column is totally possible to change the entire value/reference placement (e.g. imagine if its new attribute's type is shorter than any other existing attributes), and require a table rewrite.
* Therefore, for my previous idea to work, we have to make the attributes ordered only by attnum. But that requires change of memtuple format which is the exact thing I wanted to avoid when I was thinking about this alternative solution...
* So, if we nonetheless have to change the memtuple format, why not just follow the FIXME suggestion and add the knowledge about the number of attributes? That would be much easier to implement and probably easier to support backward compatibility too.

Thoughts?

**Comment by ashwinstar** [comment]
Some thoughts to add:
- Lucky we starting GPDB7, memtuple is ONLY used within AO table (other usage of it like hashjoin spilling, interconnect broadcasts motions and such are all replaced by minimal tuple). Hence, the impact of format change is localized to ao_row tables for memtuples
- Due to that there is possibility we just use pg_appendonly's newly added version field for this purpose and not attach anything to memtuple itself. Means detect the type of memtuple at table level itself instead of per tuple
- Documentation states `bit 30 is unused` might need to look into it if real is or not and that can be other avenue which can be explored
- Other aspect I do wish to explore as FIXME comment states do we really need to store the number of attributes at tuple level or varblock level will work out. Any for sure varblock can never has mixed number of attributes. The only complication might be on-disk then memtuple format might differ compared to in-memory format where we will have to carry the length populated from varblock

**Comment by huansong** [comment]
Another great idea from @ashwinstar in offline discussion:
* During `ADD COLUMN`, we record  “the current largest row number of the table” in the catalog (e.g. `pg_attribute_encoding`) and associate that with the new column. Any row inserted after a certain column is added, should have that column's value physically in file.
* So, during reading an AO row, based on the `row_number` and the `last_row_number_for_column_i` we find out the "largest column `i` which has `last_row_number_for_column_i` that is smaller/equal than the `row_number`". That constructs our knowledge about "the number of on-disk attributes" for that row. Correspondingly, we will know "the number of missing attribute". And the rest is simple as stated in https://github.com/greenplum-db/gpdb/issues/14929#issuecomment-1508671986.

[Some initial implementation](https://github.com/huansong/gpdb/commit/f3394a8b0333593fbbf181c7d484743d6c7098a8) already shows me that this approach works well for AO row tables. Will test more and also try to cover AO column using the same approach.
