### ISSUE TITLE
Inconsistent code style?

### ISSUE THREAD

**Issue by amosbird** [greenplum-db/gpdb#1500]
I saw a lot inconsistency in gpdb's code base. Is there a formal code style that should be followed?

![](https://ptpb.pw/Qwt_.jpg)

**Comment by hlinnaka** [comment]
The basic rule is to follow the PostgreSQL's coding style. That said, there is tons of existing code with varying styles in the codebase (like above :-) ), accumulated over the years, and there hasn't been any concerted effort to clean it all up. People have been cleaning it up as they go, fixing indentation etc. in the files whenever they've had to make other changes to them.

PostgreSQL has a tool, pgindent, that auto-formats source files. We could run it on the GPDB sources. But we've refrained from doing that, because there is also a lot of code or comments that pgindent would make even more ugly, because the code hasn't been written with the PostgreSQL coding style in mind in the first place. That's the tool to use, if you're hacking on a source file and want to clean it up beforehand. But the result needs to be manually checked and often fixed up. For example:
```
@@ -833,28 +852,25 @@ cdbdisp_checkCancel(DispatchCommandParms * pParms)
                        waitMode = DISPATCH_WAIT_FINISH;
 
                /*
-                * However, escalate it to cancel if:
-                *       - user interrupt has occurred,
-                *       - or I'm told to send cancel,
-                *       - or an error has been reported by another QE,
-                *       - in case the caller wants cancelOnError and it was not canceled
+                * However, escalate it to cancel if: - user interrupt has occurred, -
+                * or I'm told to send cancel, - or an error has been reported by
+                * another QE, - in case the caller wants cancelOnError and it was not
+                * canceled
                 */
                if ((InterruptPending || pParms->waitMode == DISPATCH_WAIT_CANCEL || meleeResults->errcode) &&
                        (meleeResults->cancelOnError && !dispatchResult->wasCanceled))
                        waitMode = DISPATCH_WAIT_CANCEL;
```
Pre-formatted lists like that need special marker comments (/*----) to tell pgindent to not mangle them. 

There have been changes to pgindent over the years too. When I've run it manually on some GPDB source files, I've used the version from PostgreSQL's master branch, rather than the version that's in the GPDB source tree.

Also, in the long term, we're trying to merge with more recent version of PostgreSQL. And it's often very useful to compare GPDB sources with the corresponding PostgreSQL code, to see what's changed and how. To make that easier, it's very important to keep upstream code unchanged, as far as possible. No reformatting of PostgreSQL sources, no fixing of typos, no moving functions from one file to another, etc. That doesn't apply to files that are completely GPDB-specific, of course.

Hope this helps!

**Comment by hlinnaka** [comment]
Closing the issue, I don't think there's anything to actually do here. But feel free to continue discussing.
