### ISSUE TITLE
gpsegrecoverd 

### ISSUE THREAD

**Issue by bloodwolf2020** [greenplum-db/gpdb#15068]
![image](https://user-images.githubusercontent.com/46953147/221540996-df64056d-cca0-491b-8925-37393c974752.png)

**Comment by piyushc01** [comment]
@bloodwolf2020 Can you please help us with the way you are trying to run the recovery?
It would be great if you can share the command, config file used if any, logs (if possible).

**Comment by bloodwolf2020** [comment]
I have three servers. The server is configured with [CPU 64 threads, memory 128G]. The data of each server is about 1T, 16 segments, all of which are geospatial data. The cluster is run using the docker container.

This error occurs when I execute the command [gprecoverseg - F]. At the same time, I also found two other problems:

1. In the process of executing the command, the error of [ssh_exchange_identification: read: Connection reset by peer] will occasionally occur. After several times of execution, you can enter the database backup process;

2. During the execution of the command, the ssh port encountered an error [connection reused]

In addition, when the cluster is running, there are too many concurrent queries. When the query data is too large, primary and mirror will automatically switch, and mirror will be activated. Occasionally, the port IPV6 that the process of mirror listens to is normal, but the port of IPV4 cannot be interrogated. Use the netstat command to query the port without IPV4 in the listen, and use the gpstate - m command to query the status. The service status shows that the cluster can be used normally, but the active mirror node cannot be interrogated when any sql is executed.



I want to know whether the above problems are caused by incorrect configuration parameters of my server.

kernel.shmmax=16000000000

kernel.shmmni=4096

kernel.shmall=4000000000

kernel.msgmnb=65536

kernel.msgmax=65536

kernel.msgmni=2048

kernel.sem=52100 51200000 51200 2560

I hope to get your help, thank you！

**Comment by Annu149** [comment]
@bloodwolf2020  I think there is an issue with ssh connection between hosts gp_master and gp_segment. gprecoverseg does ssh to segment hosts to run recovery script(gpsegrecovery.py) to recover them. Looks like while the recovery script is running on segment host , ssh session expires that's why the failure. Reasons to think the same are:

- As you have mentioned that you faced connection reset error many times - "In the process of executing the command, the error of [ssh_exchange_identification: read: Connection reset by peer] will occasionally occur. After several times of execution, you can enter the database backup process;"
- Also In the second image , we can see that there are "connection refused errors "  for dbid 18,19,20 at first and then "Unexpected EOF while looking ..." error.
- Also in the first image we can see that pg_basebackup was successfully completed for dbids 4,5,6,7,8,9 on **gp_master** host. That means there are no issues with the gprecoverseg code. And only segment recoveries(dbids 18-27) on **gp_segment** host have failed (probably because ssh session expired)

Few things I would suggest to check before executing gprecoverseg:

- Check the cluster state with gpstate -a
- Check whether you are able to do ssh to all segments host from master host
- If your ssh connection is being reset after it has already been established, there is a good chance that you are reaching the inactivity timer. To check the timeout setting or adjust it, find ClientAliveInterval line inside of your sshd_config file.
- Check to make sure that the SSH configuration file allows for an appropriate number of simultaneous connections- MaxStartUps inside sshd_config file
- Or maybe just restart ssh service on hosts
- Better to run gprecoverseg in verbose mode to see more debug logs "gprecoverseg -F -v"

**Comment by bloodwolf2020** [comment]
@Annu149 Thank you very much.
First of all, I'm sorry. After many checks, I found that the problem was due to the network card settings. The auto-negotiation attribute of the network card of one server was set to no, but the other two were set to yes. This caused a large number of network packets to collide and the network was close to collapse

**Comment by Annu149** [comment]
Thanks @bloodwolf2020, Closing this issue as there is no problem with gprecoverseg utility.
