### ISSUE TITLE
Only the master can modify the system table, and then restart the database to execute ddl or dml, and the page will get stuck

### ISSUE THREAD

**Issue by victory12346** [greenplum-db/gpdb#15097]
This happens when you perform the following operations in 7x. The operation steps are as follows
1. Only start master
`gpstart -m`
2. Log in to master
`psql（Master can be linked even without utility mode.This problem was discussed in 12580）`
3. Delete mirror or modify system table
`select gp_remove_segment_mirror('0');`
4. stop database
`gpstop -m`
5. start database
`gpstart`
6. Connect to the database and execute dml or ddl statements
```
psql
create table stu(id int);
```
The following phenomena will occur according to the above operation.The page will get stuck。
![image](https://user-images.githubusercontent.com/65478644/222163219-6f0a8f93-5034-4494-8fea-409bc24dd7c5.png)

**Comment by SmartKeyerror** [comment]
@victory12346 Hi, thanks for you to report this BUG, but I can't reproduce this issue in my local environment. 

Since if I use `select gp_remove_segment_mirror('0');` to delete a tuple from table gp_segment_configuration, I can't restart the cluster cause it leaves an invalid HA cluster configuration.

Could you give more details about this issue? Thanks a lot.

**Comment by victory12346** [comment]
> to delete a tuple from table gp_segment_configuration, I can't restart the cluster cause it leaves an invalid HA cluster configuration.

ok, I'll give you some more details on this issue.These are some of the steps and configurations I used to reproduce the problem.
1.This is my initialization file configuration
![image](https://user-images.githubusercontent.com/65478644/223144532-d20bfe6d-6ffd-4f01-a6bf-558bee94ea0f.png)
2.Here is my version number and the details of gp_segment_configuration
![image](https://user-images.githubusercontent.com/65478644/223145422-8fe9093f-2866-4fc1-8fbe-acc47383ef44.png)
3.After the initialization, the database is then stopped
`gpstop`
4.Start the database as master
`gpstart -m`
5.Delete mirror
`select gp_remove_segment_mirror('0');`
![image](https://user-images.githubusercontent.com/65478644/223147356-6fd36e75-549b-4f2e-87ff-9a99f89ee056.png)
6.Restart the database
```
gpstop -m
gpstart
```
7.Perform the ddl operation
`create table stu(id int);`
Perform the preceding steps step by step. After the database is restarted, the client hangs. No operation can be performed on the client. I think it was in master mode that the database was damaged by restarting the database after changing the data of the system table.
![image](https://user-images.githubusercontent.com/65478644/223148563-f5d0d017-4848-4aa4-8123-ba73887eb11a.png)

**Comment by jimmyyih** [comment]
I believe this is expected behavior.  The `gp_remove_segment_mirror()` catalog function is mainly meant to be used by supported external tools (e.g. gpexpand) and so there are extra steps surrounding its usage.  For this "hang", the backend that the client is connected to is most likely stuck in synchronous replication wait because your `gp_segment_configuration` shows the primary segment (content 0) in mode `synchronized (s)`.  If you're removing all mirrors from the cluster, you'll most likely need to manually update the primary modes to be `not synchronized (n)` and maybe reset the `synchronous_standby_names` GUC to blank in the `postgresql.conf` or `postgresql.auto.conf` file of that primary segment (make sure to reload with `gpstop -au`).

**Comment by victory12346** [comment]
> 3\. select gp_remove_segment_mirror('0');

**Comment by victory12346** [comment]
> I believe this is expected behavior. The `gp_remove_segment_mirror()` catalog function is mainly meant to be used by supported external tools (e.g. gpexpand) and so there are extra steps surrounding its usage. For this "hang", the backend that the client is connected to is most likely stuck in synchronous replication wait because your `gp_segment_configuration` shows the primary segment (content 0) in mode `synchronized (s)`. If you're removing all mirrors from the cluster, you'll most likely need to manually update the primary modes to be `not synchronized (n)` and maybe reset the `synchronous_standby_names` GUC to blank in the `postgresql.conf` or `postgresql.auto.conf` file of that primary segment (make sure to reload with `gpstop -au`).

I've also tried setting the primary mode to synchronized (n) and then reloading. But when I stop the database and then restart it and ddl it, it still hangs.
![0880c4c80710fcdcdd0c](https://user-images.githubusercontent.com/65478644/223347348-6bca4a4f-66c3-4c3b-88ef-269d57cbea4e.png)

**Comment by ashwinstar** [comment]
Did you took action about synchronous_standby_names GUC (as Jimmy mentioned)?

**Comment by victory12346** [comment]
> Did you took action about synchronous_standby_names GUC (as Jimmy mentioned)?

yes, I have tried to reset `synchronous_standby_names` to blank(`gpconfig -c synchronous_standby_names -v ''`) and then restart. However, the value of synchronous_standby_names remains *. The configuration value in the primary is blank, but the value obtained by gpconfig is still * (`gpconfig -s synchronous_standby_names`).
![image](https://user-images.githubusercontent.com/65478644/223378306-9d8730f6-4615-4f4c-a77b-7b56dc53a736.png)
![image](https://user-images.githubusercontent.com/65478644/223378604-045d50c6-b59b-4f0c-9b61-8cd2239c07c8.png)

**Comment by jimmyyih** [comment]
As shown from your gpconfig output, `synchronous_standby_names` is not blank for the primary segment(s).  Running `gpconfig -c synchronous_standby_names -v ''` won't help here because it only edits user GUCs in `postgresql.conf`.  You'll have to manually open the internal file `/data/greenplum/gpdata/primary/gpseg0/postgresql.auto.conf` and remove the `*` from there (make sure to reload after with `gpstop -au`).
