### ISSUE TITLE
Role names starting with "gp_" are reserved.

### ISSUE THREAD

**Issue by ycauld** [greenplum-db/gpdb#15259]
creating a role with a gp_<name> results in a error.  DETAIL:  Role names starting with "pg_" are reserved. I know that with PostgreSQL 9.6 role names starting with pg_ were reserved.  should this the same for roles starting with gp_?

**Comment by soumyadeep2007** [comment]
# RCA

Since 2010 (historical), gp_* names have been "reserved". See IsReservedName.

So you can never create certain objects such as tablespaces, schemas etc with that name for 4x, 5x, 6x and 7x

However, PG9.6 (Frost) [commit: 293007898d3fa5a815c1c5814df53627553f114d] extended this check to cover roles as well.

```
Reserve the "pg_" namespace for roles

This will prevent users from creating roles which begin with "pg_" and
will check for those roles before allowing an upgrade using pg_upgrade.

This will allow for default roles to be provided at initdb time
We absorbed it in the merge for 7x.
```

So, you could create roles with gp_/pg_ in 6.x but no longer in 7.x.

Now we have 2 things we can do:
* Lift the restriction entirely for gp_ roles in 7X.
* Deal with it during major version upgrades/backup-restore by automatically renaming such roles.

**Comment by ashwinstar** [comment]
Do we know the details on why the restriction was added in upstream to understand the impact of choice 1 "Lift the restriction entirely for gp_ roles in 7X."?
