### ISSUE TITLE
Reorganize the table with distributed randomly not work

### ISSUE THREAD

**Issue by roseduan** [greenplum-db/gpdb#15733]
### Greenplum version or build

main branch

### Step to reproduce the behavior

```
postgres=# create table tbl(v int) with(appendonly=true, orientation=column) distributed by(v);
CREATE TABLE
postgres=# insert into tbl select generate_series(1,1000);
INSERT 0 1000
postgres=# select gp_segment_id, count(*) from tbl group by gp_segment_id;
 gp_segment_id | count
---------------+-------
             0 |   508
             1 |   492
(2 rows)

postgres=# alter table tbl set with (reorganize=true) distributed randomly;
ALTER TABLE
postgres=# select gp_segment_id, count(*) from tbl group by gp_segment_id;
 gp_segment_id | count
---------------+-------
             0 |   508
             1 |   492
(2 rows)
```

**Comment by huansong** [comment]
Thanks for reporting @roseduan !

I can reproduce the same issue on main. It doesn't exist in 6X. So it is a regression.

**Comment by huansong** [comment]
**Partial RCA:**

Some background: during `REORGANIZE=true`, a temp table is created to hold the re-organized data. There are two ways to create the temp table, one is to build a `CREATE TABLE ... AS ...` command to directly create the table with data, another is to create an empty table first, and then build a `INSERT INTO ... SELECT FROM ...` command to fill the data. More details about why we have to do the second approach can be found in `prebuild_temp_table()`, but basically, we need to do the second approach when any of these conditions is true:
1. The table is a CO table;
2. The table is an AO table with index;
3. The table has dropped column.
So for the query like in the issue description which is a CO table, we have to do the second approach. 

Another thing is that, internally we are forcing the postgres planner (`optimizer=false`) for `REORGANIZE=true` due to problem with ORCA: https://github.com/greenplum-db/gpdb/blob/main/src/backend/commands/tablecmds.c#L17237-L17243 .

So when we are doing
```sql
alter table tbl set with(reorganize=true) distributed randomly;
```
we are essentially doing
```sql
create temp table temp_tbl (v int) using ao_column distributed randomly;
set optimizer = false;
insert into temp_tbl select * from tbl;
-- Finally, swap relfilenodes between tbl and temp_tbl
```

And the problem is that, with postgres planner it seems that we are not doing the right thing for `INSERT`:
```sql
postgres=# explain insert into temp_tbl select * from tbl;
                        QUERY PLAN
-----------------------------------------------------------
 Insert on temp_tbl  (cost=0.00..4.33 rows=333 width=4)
   ->  Seq Scan on tbl  (cost=0.00..4.33 rows=333 width=4)
 Optimizer: Postgres query optimizer
(3 rows)
```
No motion is generated. Whereas in 6X there is:
```sql
postgres=# explain insert into temp_tbl select * from tbl;
                                        QUERY PLAN
-------------------------------------------------------------------------------------------
 Insert on temp_tbl  (cost=0.00..11.00 rows=334 width=4)
   ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..11.00 rows=334 width=4)
         ->  Seq Scan on tbl  (cost=0.00..11.00 rows=334 width=4)
 Optimizer: Postgres query optimizer
(4 rows)
```

So in 7X we ended up doing `insert into temp_tbl select * from tbl` on each segment individually, resulting in no effect of redistributing randomly. We should find out why the plan changed between 6X and 7X.

**Comment by roseduan** [comment]
Seems like it is related to this function:
```
/*
 * Get a locus that represents the desired distribution of the query result.
 *
 * This is a stripped down version of the logic in cdbllize_adjut_top_path(),
 * used to hint the planner on where the result is needed. Sometimes, the
 * final distribution is not representable as a locus, a Null locus
 * returned in that case.
 *
 * TODO: This only handles a few cases. For example, INSERT INTO SELECT ...
 * is not handled, because the parser injects a subquery for ti which makes
 * it tricky.
 */
CdbPathLocus
cdbllize_get_final_locus(PlannerInfo *root, PathTarget *target)
```

**Comment by huansong** [comment]
Interesting, but I think when the target table in `INSERT INTO SELECT ...` is randomly-distributed,  `cdbllize_get_final_locus` will simply always give `CdbLocusType_Strewn` which should be the right locus type.

I think the real issue is this (not far away from that function): in `create_motion_path_for_insert` we have intentionally skipped motion for an `INSERT` into a randomly-distributed table if there's no difference in the number of segments between the target and source tables : https://github.com/greenplum-db/gpdb/commit/1dc3e975b8a . The reason is that if the table is randomly-distributed, the inserted data can be anywhere, so why not just insert on segment-local only.

I think the aforementioned [ORCA issue](https://github.com/greenplum-db/gpdb/blob/main/src/backend/commands/tablecmds.c#L17237-L17243) is probably of similar nature: we skipped redistribution of `INSERT` for a randomly-distributed table.

I tend to agree that the above behavior makes sense and we don't need to revert that. So for the fix, the idea currently on my mind is to introduce an internal GUC e.g. `gp_insert_force_redistribution` to force the motion creation in `create_motion_path_for_insert`, and use that GUC in `REORGANIZE=true`.

**Comment by roseduan** [comment]
> 

Sounds like a reasonable solution, would you follow this to slove it?

**Comment by huansong** [comment]
Yes PR to follow soon.

**Comment by ashwinstar** [comment]
Having GUC to control redistribute behavior for randomly distributed table sounds reasonable choice as, in reality there is no perfect answer for it - its really a personal use-case based choice. 

To avoid regression compared to 6X maybe default should be to redistribute. Thoughts?

**Comment by huansong** [comment]
@ashwinstar Just to clarify - yes it is a regression for `REORGANIZE=true` for sure and I was going to fix that by `set gp_insert_force_redistribution = true` just for `REORGANIZE=true` and reset it back after done.

But the default of `gp_insert_force_redistribution` should be false right? It is not a regression for non-REORGANIZE cases. In fact it is supposed to be an optimization according to [the comment](https://github.com/greenplum-db/gpdb/blob/main/src/backend/cdb/cdbpath.c#L2304-L2306) and I kinda agreed with that. Eg, imagine we do `INSERT INTO t1 SELECT * FROM t2` where both `t1` and `t2` are randomly distributed, it seems fine to skip redistribute.

**Comment by huansong** [comment]
@ashwinstar @roseduan I've raised a PR for this: https://github.com/greenplum-db/gpdb/pull/15795 The GUC `gp_force_random_redistribution` is tentatively default to `false`. Feel free to take a look and comment! Thanks.

**Comment by roseduan** [comment]
> 

Great! Thanks.
