### ISSUE TITLE
INSERT fails on append optimized column oriented table with a foreign key

### ISSUE THREAD

**Issue by volkovandr** [greenplum-db/gpdb#16770]
### Greenplum version or build
`PostgreSQL 12.12 (Greenplum Database 7.0.0 build commit:0a7a3566873325aca1789ae6f818c80f17a9402d Open Source) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit compiled on Sep 20 2023 23:29:19 Bhuvnesh C.`

### OS version and uname -a
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Rocky
Description:	Rocky Linux release 8.8 (Green Obsidian)
Release:	8.8
Codename:	GreenObsidian

$ uname -a
Linux ######## 4.18.0-477.21.1.el8_8.x86_64 #1 SMP Tue Aug 8 21:30:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
### Cluster setup
A cluster with 24 primary segments, 24 mirrors and a standby coordinator. The cluster is healthy.

### Expected behavior
Insert into a table that has a foreign key, and was created using `WITH (appendonly=true, orientation=column)` should just work.

### Actual behavior
INSERT fails with a message
```
ERROR:  Trigger is not supported on AOCS yet (trigger.c:2714)  (seg4 #######:16004 pid=3948271) (trigger.c:2714)
```

The table does not have any triggers.

### Step to reproduce the behavior
```
test_insert_bug=# CREATE TABLE a(id int primary key);
CREATE TABLE

test_insert_bug=# CREATE TABLE b(id int references a) WITH (appendonly=true, orientation=column);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
WARNING:  referential integrity (FOREIGN KEY) constraints are not supported in Greenplum Database, will not be enforced
CREATE TABLE

test_insert_bug=# INSERT INTO b VALUES (1);
ERROR:  Trigger is not supported on AOCS yet (trigger.c:2714)  (seg4 #######:16004 pid=3948271) (trigger.c:2714)
```

but it works fine if there is no foreign key, and it also works if the table is not column oriented or append optimized
```
test_insert_bug=# CREATE TABLE c(id int) WITH (appendonly=true, orientation=column);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
test_insert_bug=# INSERT INTO c VALUES (1);
INSERT 0 1
```
and it does not seem dependent on any other storage parameters, partitioning or distribution policy.

**Comment by ashwinstar** [comment]
Thanka for reporting and repro, we will look into it.

**Comment by huansong** [comment]
In GPDB/Postgres, the foreign key constraint is implemented through a special constraint trigger (`createForeignKeyActionTriggers`). GPDB just silently ignore the trigger since we don't support it. We set `tgenabled` of the trigger to 'D', so the trigger event is not going to be set.

At the same time, GPDB also disables all kinds of row trigger for AO tables (including row and column). But we throw errors in difference places for AO-row and AO-column respectively:
* For AO-row tables, we throw error when we actually try to fire the trigger (`AfterTriggerExecute`). That would fail with error `feature not supported on appendoptimized relations` when we try to fetch the OLD tuple in a trigger action.
* For AO-column tables, we throw error `Trigger is not supported on AOCS yet` **before** we even set the trigger events. That's the `Trigger is not supported on AOCS yet` message, which was added since the very first commit of AO-column implementation: https://github.com/greenplum-db/gpdb/commit/11d14c930efff578344d1647203715fc4ecb9154

So the issue is that, the error for AO-column comes before we ignore the foreign key trigger. If we delete this error, we would ignore the foreign key trigger in the same way for both AO-column and AO-row tables. We would also error out other types of row triggers in the same way for AO-column and AO-row tables. 

BTW the error for AO-row tables might read too generic, that's because it's for some AM APIs that are being used by multiple features: https://github.com/greenplum-db/gpdb/blob/3400385b097f1d89ce3d35ac27f1c514a7f6b3a8/src/backend/access/aocs/aocsam_handler.c#L1168-L1185 . If we want to support row trigger for AO/CO tables we need to implement these AM APIs.

6X has the same issue.
