### ISSUE TITLE
DELETE from appendonly tables produces strange results

### ISSUE THREAD

**Issue by volkovandr** [greenplum-db/gpdb#174]
Hello
I understand that appendonly tables are optimized for inserting. But since DELETE and UPDATE commands are supported in 4.3, I assume they are supposed to work properly. But they don't, at least DELETE doesn't. Here is an example:

```
dwh=# CREATE TABLE bar (a int, b text) WITH (appendonly=true) DISTRIBUTED BY (a);
CREATE TABLE
dwh=# INSERT INTO bar SELECT a, a::text FROM generate_series(1,1000000) a;
INSERT 0 1000000
dwh=# SELECT count(*) FROM bar;
count
---------
 1000000
(1 row)

dwh=# DELETE FROM bar;
DELETE 1000000
dwh=# SELECT count(*) FROM bar;
count
--------
 868928
(1 row)

dwh=# DELETE FROM bar;
DELETE 868928
dwh=# SELECT count(*) FROM bar;
count
--------
 868928
(1 row)
```

And now the completely crazy thing:

```
dwh=# DELETE FROM bar WHERE a = 500;
DELETE 1
dwh=# DELETE FROM bar WHERE a = 501;
DELETE 1
dwh=# DELETE FROM bar WHERE a = 502;
DELETE 1
dwh=# SELECT count(*) FROM bar;
count
--------
 967229
(1 row)
```
I've tried this on two different installations of GP: same result with only difference in the number of rows that are deleted and then "restored". Am I doing anything wrong?

**Comment by asimrp** [comment]
@volkovandr thank you for reporting the issue and apologies for the inconvenient experience with Greenplum.  DML should work just as heap tables with appendonly row/column oriented tables.  I am investigating this issue on priority, please stay tuned.

Please note that I did not see this issue on 4.3 code line.

**Comment by volkovandr** [comment]
Thank you for taking care.
FYI: I've done some more experiments and notices some regularities:
The number of records actually deleted from the table is a constant number multiplied by the number of segments. When the number of records initially inserted into the test table was relatively big, the DELETE command always deletes exactly 32768 records per segment. When it was relatively small, it deleted 32767 records per segment.
I've tried this on two different clusters of 4 segments and of 10 segments - results are the same.
It does not seem dependent on the size of a record in the test table, number of fields or orientation.

I'm running Greenplum compiled from source code downloaded from github about 2 weeks ago, so it does not include the most recent commits. My two clusters are running on CentOS 6 and CentOS 7, and the hardware configuration is different.
```
[gpadmin@centos-gp-master ~]$ gpstate -i
20151216:11:12:35:002603 gpstate:centos-gp-master:gpadmin-[INFO]:-Starting gpstate with args: -i
20151216:11:12:35:002603 gpstate:centos-gp-master:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 4.3.99.00 build dev'
```

**Comment by asimrp** [comment]
Thanks @volkovandr for further details.  Here is some info on what's causing the issue.

Appendonly tables use bitmaps for implementing visibility such that each bit in the bitmap represents unique row in appendonly table.  The bitmap for each appendonly table is stored in an auxiliary table called `visimap`.  Schema of the table is as follows:
```
postgres=# \d pg_aoseg.pg_aovisimap_17155*
?m? "pg_aoseg.pg_aovisimap_17155"
    Column    |    Type     
--------------+-------------
 segno        | integer
 first_row_no | bigint
 visimap      | bit varying

Index "pg_aoseg.pg_aovisimap_17155_index"
    Column    |  Type   |  Definition  
--------------+---------+--------------
 segno        | integer | segno
 first_row_no | bigint  | first_row_no
primary key, btree, for table "pg_aoseg.pg_aovisimap_17155"
```
Note that the index is defined with two keys (`segno`, `first_row_no`).  Each tuple scanned is queried against the tuple's visimap for visibility.  The visimap index is used to lookup the visimap tuple using the base tuple's tid (row number) and segment file (segno).

In this case, the btree comparison function returned for the `bigint` key is `hashint8`.  And this function never returns 0, to indicate equality.  That means when checking visibility, index lookups in visimap table fail.  If a visimap tuple is not found for a given tuple, the tuple is visible.  And hence the unexpected visible tuples.

In 4.3_STABLE branch, where this issue does not exist, the btree comparison function for `first_row_no` is `btint8()`.

Most likely this bug was introduced by operator families patch merged from upstream.  We are evaluating a fix.

Thanks to @asubramanya for pairing up on this one.

**Comment by hlinnaka** [comment]
I've pushed Asim's fix for this. Thanks for the report!
