### ISSUE TITLE
Change default installation directory from /usr/local/pgsql to /usr/local/gpsql

### ISSUE THREAD

**Issue by edespino** [greenplum-db/gpdb#22]
The default installation directory (configure prefix) is currently set to the that used by PostgreSQL (/usr/local/pgsql). Although related, PostgreSQL and Greenplum Database are different products, I suggest changing the Greenplum Database default installation directory to /usr/local/gpsql.

There is also a related issue with the default directory (/usr/local/pgsql) as this will change the default installation directory for gp_toolkit.sql. Consequently, it will not be loaded by "gpinitsystem" (function LOAD_GP_TOOLKIT). The src/Makefile.globals.in dictates an alternate installation directory "/share" instead of "/share/postgresql" if the installation directory is pgsql or postgresql is used.

This issue will be more prevalent in the OSS context as the default prefix will cause the loading of gp_toolkit.sql to fail.

WORKAROUND: Use an installation directory other then one containing the strings "pgsql" or "postgres" by specifying the configure "--prefix" option.

**Comment by ashwinstar** [comment]
+1 lets do it

- Ashwin

On Oct 29, 2015, at 8:33 AM, Ed Espino <notifications@github.com> wrote:

The default installation directory is currently set to the that used by
PostgreSQL (/usr/local/pgsql). Although related, PostgreSQL and Greenplum
Database are different products, I suggest changing the Greenplum Database
default installation directory to /usr/local/gpsql.

There is also a related issue with the default directory (/usr/local/pgsql)
as this will change the default installation directory for gp_toolkit.sql.
Consequently, it will not be loaded by "gpinitsystem" (function
LOAD_GP_TOOLKIT). The src/Makefile.globals.in dictates an alternate
installation directory "/share" instead of "/share/postgresql" if the
installation directory is pgsql or postgresql is used.

This issue can be more prevalent in the OSS context.

—
Reply to this email directly or view it on GitHub
<https://github.com/greenplum-db/gpdb/issues/22>.

**Comment by edespino** [comment]
Pushed to master.
