### ISSUE TITLE
Why so slow on gp postgres

### ISSUE THREAD

**Issue by mstaryi** [greenplum-db/gpdb#2463]
I did some simple performance tests and found that in this scenario, the performance of GP is far greater than that of pg9.5。
Test SQL：
create table testdis (id int, name varchar(20)) DISTRIBUTED BY (id);
CREATE OR REPLACE FUNCTION creatData()
  RETURNS boolean AS
$BODY$
DECLARE
i int;
begin     
i :=1; 
FOR i IN 1..10000 LOOP
 insert into testdis(id,name) VALUES(i,'CEIC');
END LOOP;
if i > 0 then 
     return true; 
   else 
     return false; 
   end if; 
end;    
$BODY$
LANGUAGE 'plpgsql' VOLATILE;

When I was running createData on pg9.5, it used only 500ms,
-bash-4.1$ time psql -c "select * from creatData();"
 creatdata 
-----------
 t
(1 row)
real	0m0.050s
user	0m0.002s
sys	0m0.002s

But it used about 5s on GP (GPORCA was enabled):
[gpadmin@sdw ~]$ time PGOPTIONS='-c gp_session_role=utility' psql -d postgres -p 40000 -c "select * from creatData();"
 creatdata 
-----------
 t
(1 row)
real	0m4.782s
user	0m0.003s
sys	0m0.002s

**Comment by asimrp** [comment]
@mstaryi there is flaw in your experiment.  You are creating a distributed table but inserting data into it in utility mode (`PGOPTIONS='-c gp_session_role=utility'`).  This is wrong because all the tuples will be inserted only in one segment, leading to wrong results.  Can you try running the same SQL from master segment?

Given the small data set in your experiment, I won't be surprised if Greenplum performs slower than PostgreSQL 9.5.  The performance gain due to Greenplum's shared-nothing, parallel architecture becomes more apparent with large data sets.  Also note that Greenplum was based on PostgreSQL 8.2 until 2015, we've caught up with PostgreSQL 8.3 now and efforts are underway for merging towards 9.x.

**Comment by hlinnaka** [comment]
I believe the point of connecting in utility mode is to get a more apples to apples comparison with a single-instance PostgreSQL. It's a reasonable test, I would expect the performance of a single GPDB node to be roughly on par with PostgreSQL.

I'm not actually seing such a big difference on my laptop. Make sure you compile GPDB without assertions (--disable-cassert), optimizations enabled (-O2 or higher), and without testutils (--disable-testutils).

**Comment by hlinnaka** [comment]
Ah, I only now noticed that you said "with ORCA enabled". That might explain it. ORCA has a very high startup overhead, so it adds several milliseconds to every query, no matter how simple. For a PL/pgSQL function, the plans should be cached, though, so that you would only incur the overhead on first invocation of a query. Perhaps that's not happening in this test case for some reason?

**Comment by mstaryi** [comment]
@hlinnaka I did this test case because of low insertion rate when I was using it, I tried to close the optimizer in the SQL statement，it still took so long.
time PGOPTIONS='-c gp_session_role=utility' psql -d postgres -p 40000 -c 'set optimizer=off;select * from creatData();'

When I recompile GP with ORCA disabled, it's really a lot faster, just a little slower than PostgreSQL.
When I tried the same test case on GP 4.3.10, which downloaded from the Pivotal website and with ORAC enabled, it just cost 0.621s, just a little slower than PostgreSQL.

**Comment by qzren1982** [comment]
@mstaryi 
`I tried the same test case executed on master on my laptop :
Open GP takes time 13.8s
PG 4.3.10 takes time 8.9s
When executed it in utility mode in one segment:
Open GP takes time 4.8s
PG 4.3.10 takes time 0.05s`

PG4.3.10 IS right or Wrong ？

**Comment by mstaryi** [comment]
@qzren1982
It was just a slip of pen, it should be GP 4.3.10

**Comment by hlinnaka** [comment]
I believe the conclusion here is that ORCA is generally slow to start up, and there's no action required here. Closing.
