### ISSUE TITLE
COPY FROM fails with ERROR:  target lists can have at most 1664 entries

### ISSUE THREAD

**Issue by soloneranger** [greenplum-db/gpdb#2511]
Environment: PostgreSQL 8.3.23 (Greenplum Database 5.0.0-alpha.5+dev.34.g27d0ae5 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

(configured --with-python --with-libxml  --disable-orca)

I'm trying to populate a table which has 957 columns(assume col1, col2...col957) from txt file. I'm using following statement:
`
dev=# COPY MY_TABLE FROM '/home/gpadmin/MY_TABLE.txt' WITH DELIMITER '|' NULL '' LOG ERRORS SEGMENT REJECT LIMIT 10 ROWS;`

and it fails with following error:

> ERROR:  target lists can have at most 1664 entries
CONTEXT:  SQL statement "select (case when pg_column_size(Ta.col1) > 1024 then NULL else Ta.col1 end) as col1, (case when Ta.col1 is NULL then false else true end), (case when pg_column_size(Ta.col2) > 1024 then NULL else Ta.col2 end) as col2, (case when Ta.col2 is NULL then false else true end),
...
(case when pg_column_size(Ta.col957) > 1024 then NULL else Ta.col957  end) as col957, (case when Ta.col957 is NULL then false else true end) from test.my_table as Ta  limit 7500 "

Never faced such problem on 4.3.x builds. Besides, why it's doing select for my COPY anyway?

**Comment by hsyuan** [comment]
When you run the command, it triggers auto stats collection.
I think the issue is caused by this: https://github.com/greenplum-db/gpdb/pull/2156

**Comment by bhuvnesh2703** [comment]
Hello @soloneranger, thanks for reporting the issue.
When you copy data to a table, and if the guc `gp_autostats_mode` is set to `ON_NO_STATS` the first time data is inserted it will trigger `analyze` on the table, the select queries which you see are executed during `analyze`.
`analyze` process creates queries to fetch data from the table and right now we are creating 2 `targetlist` entry for each of the varlena type (ex. `text`) columns due to which we are exceeding the max limit 1664. We will look into this issue.
However, to unblock you, you can set `gp_autostats_mode` to `NONE` before copying so that analyze is not triggered. And in case you need to `analyze` the table you can `analyze` a subset of columns, ex `analyze tablename (col1, col2,.... coln)`. `n` needs to be less than ~800 if all columns are text columns.

**Comment by vraghavan78** [comment]
No plan to fix it in the next 6 months.

**Comment by soloneranger** [comment]
Since there is a bug, wouldn't it be better to keep the issue open? "No plan to fix it in the next 6 months." - wondering what may potentially happen AFTER 6 months?
