### ISSUE TITLE
SELECT E'\x00'::bytea;

### ISSUE THREAD

**Issue by micklf** [greenplum-db/gpdb#2523]
```
db_lin=# SELECT E'\x00'::bytea;
ERROR:  invalid byte sequence for encoding "UTF8": 0x00
HINT:  This error can also happen if the byte sequence does not match the encoding expected by the server, which is controlled by "client_encoding".
db_lin=# SELECT E'\x01'::bytea;
 bytea 
-------
 \001
(1 row)
```

0x00 stands for nul
the type bytea should support the storage of this.

I checked in postgres, it support this.

I checkout the source at about November of 2016.

**Comment by micklf** [comment]
I tried
```
db_lin=# SELECT E'\\000'::bytea;
 bytea 
-------
 \000
(1 row)
```
ok <----Octal 
not <--- Hex??

**Comment by hlinnaka** [comment]
E'\x00' means a string literal with a single nul-byte. Null-bytes are not allowed in string literals. E'\\000' works, because that's a string literal containing four bytes: \, 0, 0, 0.  The bytea input function interprets it into the null byte.

What you meant to do is E'\\x00'. See also the docs at https://www.postgresql.org/docs/9.0/static/datatype-binary.html#AEN5110.

**Comment by hlinnaka** [comment]
Agh, I got that wrong myself.. So what you meant to do is:

```
postgres=# select E'\\x00'::bytea;
 bytea 
-------
 \x00
(1 row)

```

ie. two backslashes.
