### ISSUE TITLE
Remove Vagrant and Docker folder

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#2637]
Please remove the Vagrant folder, currently under `src/tools/vagrant`, in its entirety. The original pull request #224 was riddled with problems, and it has been a maintenance headache. In its current state, the vagrant files provide a sub-par, if not outright broken, experience, and it's difficult to support. Keeping them will only cause more confusion than not having them.

The Docker experience is pretty much a similar abomination and lacks the love and maintenance.

For the love of the community, please burn them down with fire.

**Comment by hsyuan** [comment]
I agree with @d, we should remove them.
@pivotal-mike @vraghavan78 Any thoughts?

**Comment by Eulerizeit** [comment]
I very much disagree. The pgAdmin 4 team used the vagrant image
instructions to create a local GPDB instance to work with and they plan to
use the Docker build instructions for creating a GPDB instance in CI as we
finish migrating from Circle to Concourse.

It we want to enable developers to build and test tools against GPDB then
instructions for Docker and vagrant need to be maintained not removed.

-- Rob

**Comment by brendanstephens** [comment]
Ideally, you would want to support as much rapid deployment as possible -- vmware, vagrant, docker... 

Vagrant and docker at least allow for some modification to the image, since you can build before.
I would think that some dedication towards these components would pay off with faster testing and adoption.

**Comment by cjcjameson** [comment]
Not to promise anything, but we might be getting the Dockerfile some love soon. Stay tuned...

To begin with, can anyone differentiate the usage of the two following Dockerfiles?
https://github.com/greenplum-db/gpdb/blob/master/Dockerfile
https://github.com/greenplum-db/gpdb/blob/master/src/tools/docker/base/Dockerfile

**Comment by hlinnaka** [comment]
Recent discussion on this: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/JfLYgYRnxV0/bI26KkjgFgAJ.

I think the consensus was that we're going to keep them, and try to keep them up-to-date. Not sure what the current state of the scripts is, or how successful we'll be in maintaining them, but since we're not going to remove them, I'll close this issue.
