### ISSUE TITLE
Incorrect calculation of window frame

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#3119]
These two queries should return the same result:

```
regression=# select i,j,sum(i) over(order by j range 1 preceding) from win_test_for_window_seq; 
 i | j | sum 
---+---+-----
 0 | 0 |   0
 1 |   |   6
 2 |   |   6
 3 |   |   6
(4 rows)

regression=# select i,j,sum(i) over(order by j range (1 + floor(random())) preceding) from win_test_for_window_seq; 
 i | j | sum 
---+---+-----
 0 | 0 |   0
 1 |   |    
 2 |   |   6
 3 |   |   6
(4 rows)
```

The only difference is that the latter uses `(1+ floor(random()))` in place of constant `1` as the frame bound. That expression is volatile because of the random(), but it always evaluatest to 1.

I'm not sure which result is correct, but surely they should be the same.

**Comment by d** [comment]
Hi @hlinnaka according to SQL 2003, the first query result is correct:
  - `RANGE 1 PRECEDING` means the frame starts from the first row in partition whose `j` value is greater than `current_row.j - 1`, if `current_row.j` is not `NULL`
  - If `j` is `NULL`, the frame starts from the first tuple whose `j` attribute is `NULL` in the partition.

We can further reduce this bug by materializing your window inputs to a table:
```
CREATE TEMP TABLE yolo(i, j, k) AS SELECT * FROM (VALUES (0,0,0), (1, NULL, 0), (2, NULL, 0), (3, NULL, 0)) AS t(i,j,k) DISTRIBUTED BY (i);

select i,j,sum(i) over(order by j range (1 + k) preceding) from yolo;
 i | j | sum
---+---+-----
 0 | 0 |   0
 1 |   |
 2 |   |   6
 3 |   |   6
(4 rows)
```

This looks like an executor bug to me, because the two plans look reasonably similar to me.

P.S. Playing with this exposed another parser bug, where I couldn't run the following DDL:
```
CREATE TEMP TABLE yolo(i, j, k) AS (VALUES (0,0,0), (1, NULL, 0), (2, NULL, 0), (3, NULL, 0)) DISTRIBUTED BY (i);
```
I opened issue #3285 to track it

**Comment by hlinnaka** [comment]
Works on master now. I think this got fixed in the big window functioning rewrite in 8.4 merge.
