### ISSUE TITLE
PXF needs newer curl dependency 

### ISSUE THREAD

**Issue by professor** [greenplum-db/gpdb#3214]
PXF needs a newer version of curl that what is shipped with macOS X. The current use of the Makefile for pulling in curl undesirable for reasons specified in https://github.com/greenplum-db/gpdb/issues/3168

Open questions are
1) what is the curl feature that PXF needs
2) how to leverage autoconf to specify that dependency
3) how to leverage connan for managing dependencies for extensions

**Comment by hlinnaka** [comment]
I downloaded libcurl 7.19.0, which is the oldest supported version by the rest of the system, and tried compiling PXF with it. There are two things that don't work:

1. The code in churl_init, to call `set_curl_option(CURLOPT_RESOLVE, ...)`. CURLOPT_RESOLVE was introduced in libcurl 7.21.3:

```
	/* needed to resolve localhost */
	if (strstr(url, LocalhostIpV4) != NULL)
	{
		struct curl_slist *resolve_hosts = NULL;
		char	   *pxf_host_entry = (char *) palloc0(strlen(PxfServiceAddress) + strlen(LocalhostIpV4Entry) + 1);

		strcat(pxf_host_entry, PxfServiceAddress);
		strcat(pxf_host_entry, LocalhostIpV4Entry);
		resolve_hosts = curl_slist_append(NULL, pxf_host_entry);
		set_curl_option(context, CURLOPT_RESOLVE, resolve_hosts);
		pfree(pxf_host_entry);
	}
```

That seems really suspicious. If localhost doesn't resolve correctly to 127.0.0.1, you've got bigger problems. Also, PxfServiceAddress hard-codes a port number, 51200. My first reaction is that we should dike out that code altogether. (If we can't remove it, could at least put it in an `#ifdef CURLOPT_RESOLVE` block).

2. The get_dest_address() function uses `CURLINFO_PRIMARY_PORT`, which was introduced in libcurl 7.21.0.
```
	/* add dest ip and port, if any, and curl was nice to tell us */
	if (CURLE_OK == curl_easy_getinfo(curl_handle, CURLINFO_PRIMARY_IP, &dest_ip) &&
		CURLE_OK == curl_easy_getinfo(curl_handle, CURLINFO_PRIMARY_PORT, &dest_port) &&
		dest_ip && dest_port)
	{
		appendStringInfo(&addr, "'%s:%ld'", dest_ip, dest_port);
	}
```
This function is used only for error messages and such, so we could well put an `#ifdef CURLINFO_PRIMARY_PORT ` there, and print just the IP address on older versions. Or taking a step back, is the IP address+port even the most informative thing in error messages? How about e.g. CURLINFO_EFFECTIVE_URL instead?


Or, maybe we don't care about libcurl versions < 7.21.3 anymore? If so, we could just bump the minimum requirement for GPDB as whole, and call it a day. But I guess older versions can still be found in the wild; presumably you wouldn't have put the code in the Makefile, to use a non-standard version, in the first place. 

I should mention that I'm guilty for the current minimum requirement of 7.19.0. This happened in 2015, some time before Greenplum was open sourced, when I replaced another library that was used for sending e-mail with libcurl's SMTP support. When I did that, I didn't realize that SMTP support was only added in version 7.19.0. And after it was found out, I didn't think that it would be a problem, since 7.19.0 was released back in 2008. But lo and behold, there were still systems out there with older versions. RHEL5 I think was the main culprit. Now, some time has passed, and I don't think we support RHEL5 anymore, but the moral of the story is that there can be *very* old versions of libcurl out there, and we'd like to at least be able to compile on such systems. Where exactly the threshold of "we no longer care" is, I don't know.

**Comment by danielgustafsson** [comment]
There are definitely systems with very old libcurl out there, but I have little sympathy for catering to a developer who wants to compile Greenplum with all it's dependencies but can't upgrade an ancient curl installation.

Also, since this issue refers to macOS: The system installed curl on my macOS 10.11 El Capitan box is 7.43.0 and the 10.12 Sierra machine it's 7.51.0. I don't have anything older available, but with the upgrade frequency on mac's it seems perfectly fine to not support more than 2 revisions back.

**Comment by hlinnaka** [comment]
On 8 September 2017 21:56:46 EEST, Daniel Gustafsson <notifications@github.com> wrote:
>There are definitely systems with very old libcurl out there, but I
>have little sympathy for catering to a developer who wants to compile
>Greenplum with all it's dependencies but can't upgrade an ancient curl
>installation.

Hmm. If I googled correctly, RHEL6 (ok, looked at Centos 6) also still ships libcurl 7.19.7. If we could stick to that, that would be really nice.

I'm sure a developer can manage to upgrade, and will probably be running something more recent to begin with, but it makes packaging simpler if you can rely on the OS version.

>Also, since this issue refers to macOS: The system installed curl on my
>macOS 10.11 El Capitan box is 7.43.0 and the 10.12 Sierra machine it's
>7.51.0. I don't have anything older available, but with the upgrade
>frequency on mac's it seems perfectly fine to not support more than 2
>revisions back.

Ok, good to know.

- Heikki

**Comment by denalex** [comment]
We also had another problem with PXF that in runtime on MacOS even 7.51.x installed by default would not work and we had to pull in the latest 7.54.x with "brew install curl" which was working. We haven't gotten to the root cause of this and @hlinnaka also indicated on the original PR we should review our use of curl, which we created a story for post-MVP.

**Comment by hlinnaka** [comment]
Is there anything left to do on this issue? I believe since commit f12d756c4e, PXF should build with libcurl 7.20 or newer, which is the same minimum requirement as with the rest of GPDB.

**Comment by danielgustafsson** [comment]
I think this can be closed.

**Comment by lavjain** [comment]
Correct! No longer an issue.
