### ISSUE TITLE
Assertion failure in cdbmutate.c

### ISSUE THREAD

**Issue by gcaragea** [greenplum-db/gpdb#332]
This is causing one of our regression tests to fail. 

Reproduction: 
```sql
create table r (a int, b int) distributed by (a);
create table p (a int, b int, c int)
        distributed by (a)
        partition by range (c) (start(1) end(5) every(1), default partition extra);

insert into r select generate_series(1, 10000), generate_series(1, 10000) * 3;
insert into p select generate_series(1, 1000), generate_series(1, 1000)*3, generate_series(1, 1000)%6;

explain delete from p where c = 3 and a in (select b from r);
```

Outcome: 
```
FATAL:  Unexpected internal error (cdbmutate.c:819)
DETAIL:  FailedAssertion("!(((((Node*)(appendPlan))->type) == T_Motion) && ((Motion *) appendPlan)->motionType == MOTIONTYPE_EXPLICIT)", File: "cdbmutate.c", Line: 819)
HINT:  Process 61448 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

**Comment by gcaragea** [comment]
@atris Any chance you could take a look at this please? Thanks.

**Comment by atris** [comment]
I will take a look tomorrow first thing.

**Comment by atris** [comment]
I looked into this and it seems to be coming from the equivalence class merge patch. The needed Motion nodes under which HashAggregate need to be present are not added and hence assertion is seeing bare HashAggregate nodes hence assertion trips.

**Comment by hlinnaka** [comment]
I did some digging, and it turns out that the underlying issue isn't actually new. The equivalence class patch changed the access plan you get for that query, and it started to trip the assertion, but I was able to construct this simpler test query, which trips the same assertion even before the equivalence class patch:

```
create table r (a int) distributed by (a);
create table p (a int, b int) distributed by (a);
create table p2 (a int, b int) inherits (p) distributed by (b);

explain delete from p using r where p.a =r.a ;
```

When run with assertions disabled, the plan looks like this:

```
postgres=# explain delete from p using r where p.a =r.a ;
                                               QUERY PLAN                                               
--------------------------------------------------------------------------------------------------------
 Delete (slice0; segments: 2)  (rows=4 width=10)
   ->  Append  (cost=0.01..0.13 rows=4 width=10)
         ->  Hash Join  (cost=0.01..0.05 rows=2 width=10)
               Hash Cond: public.p.a = r.a
               ->  Seq Scan on p  (cost=0.00..0.00 rows=1 width=14)
               ->  Hash  (cost=0.00..0.00 rows=1 width=4)
                     ->  Seq Scan on r  (cost=0.00..0.00 rows=1 width=4)
         ->  Explicit Redistribute Motion 2:2  (slice2; segments: 2)  (cost=0.01..0.08 rows=2 width=10)
               ->  Hash Join  (cost=0.01..0.08 rows=2 width=10)
                     Hash Cond: r.a = public.p.a
                     ->  Broadcast Motion 2:2  (slice1; segments: 2)  (cost=0.00..0.03 rows=1 width=4)
                           ->  Seq Scan on r  (cost=0.00..0.00 rows=1 width=4)
                     ->  Hash  (cost=0.00..0.00 rows=1 width=14)
                           ->  Seq Scan on p2 p  (cost=0.00..0.00 rows=1 width=14)
(14 rows)
```

Looking at the plan, it seems OK to me. It's performing the join and delete locally in each segment for table P, because both P and R are distributed on the same key, which is also the join key. But the join for the inherited P2 table requires a Motion node, because P2 is distributed on different key than R.

The assertion that tripped was asserting that if there are any motion nodes in the plan, then there must be an Explicit Redistribute Motion between the Append node and each of its children, to move the target tuples to the right segments. But the above plan seems OK to me - there's no need for a Motion node in  the first child of the Append. So I think the assertion is too tight.

The logic we use to decide when to insert the explicit Motion nodes (in apply_motion_mutator) seems a bit sloppy anyway. If I understand it correctly, it checks whether there are any Motion nodes in the subplan, and inserts an Explicit Redistribute Motion node if there are. The idea is that if there aren't any Motion nodes, then all the tuples came from this segment, and hence they don't need to be redistributed back. But that seems sub-optimal: there might be a Motion node in the plan, which doesn't move the target tuples, but some other tuples needed to decide which tuples to update. Or in a really complex plan, you might even have a Motion node that redistributes tuples to other nodes, and *another* Motion node that brings them back to this segment. Could we check that distribution key at the top of the plan matches the distribution key of the target table, instead of just checking whether there are any Motion nodes?

Thoughts?

I'm not sure what to do about the assertion. We could just remove it altogether, I guess, but presumably it was put there for a reason, so I'm a bit hesitant to just remove it. Anyone see a better way to formulate the assertion?

Another small mystery is why the plan changed with equivalence classes patch. The new plan looks correct to and even slightly better than the old one, so I don't plan to investigate that further, though.

**Comment by xinzweb** [comment]
@vraghavan78 and @gcaragea, any comments on the new behavior?

**Comment by atris** [comment]
I agree that the Assertion is too tight. IMO I think it is a bit out of place, and the planner should have done the right think by the time we get to the assertion.

Another problem here is that apply_motion_mutator is too dependent on Motion nodes for its checks, as you mentioned. While it would definitely make sense to add Motion nodes when the distribution keys and join keys are different, we should be safe enough if we add another check in apply_motion_mutator which allows the function to return if it sees that the two keys are same. This saves a whole lot of effort.

IMO the assertion should be removed completely, and we should make apply_motion_mutator more stringent, both in applying Motions and checks.

Thoughts?

**Comment by hlinnaka** [comment]
On 22/02/16 00:48, Atri Sharma wrote:
> I agree that the Assertion is too tight. IMO I think it is a bit out
> of place, and the planner should have done the right think by the
> time we get to the assertion.

Yeah, it seems a bit silly to have an assertion right after the code 
that created the Motion nodes, just to check that it really did.

> Another problem here is that apply_motion_mutator is too dependent on
> Motion nodes for its checks, as you mentioned. While it would
> definitely make sense to add Motion nodes when the distribution keys
> and join keys are different, we should be safe enough if we add
> another check in apply_motion_mutator which allows the function to
> return if it sees that the two keys are same. This saves a whole lot
> of effort.
>
> IMO the assertion should be removed completely, and we should make
> apply_motion_mutator more stringent, both in applying Motions and
> checks.

Ok, I created a pull to remove the assertion. I didn't change the logic 
to decide whether to add the Motion node or not for now, as that needs 
more work and testing, and isn't needed for correctness.

- Heikki

**Comment by xinzweb** [comment]
In general, assertion is to check the `assumption`, and make sure it's
right.

Before we completely remove this `assertion, how can we ensure `
apply_motion_mutator` is working correctly? Is there any other location we
should have `assumption` validated earlier?

Thanks,
Shin

**Comment by hlinnaka** [comment]
On 22/02/16 08:33, Xin Zhang wrote:
> In general, assertion is to check the `assumption`, and make sure it's
> right.
>
> Before we completely remove this `assertion, how can we ensure `
> apply_motion_mutator` is working correctly? Is there any other location we
> should have `assumption` validated earlier?

Well, in this case the code basically looks like this:

1. Do X
2. Assert that X has been done. (but the assertion doesn't quite match 
the code above, and we get the failure)

If you look at the code, the assertion block closely resembles the code 
just above it. It's not really checking a general assumption or an 
invariant, it's just repeating the thing it just did.

It might make sense to put in an assertion of some sort somewhere else, 
but I don't actually see where or how it should look it. I'm all ears if 
you have a suggestion.

- Heikki

**Comment by hlinnaka** [comment]
Fixed, closing. Thanks for the report!
