### ISSUE TITLE
Fix copy.c and add optimization

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3341]
Commit 95c238d, to make COPY of CSV files faster, was not merged. The function had been heavily modified in GPDB, and it was not immediately clear how to resolve the conflicts. That commit was just a performance enhancement, so we can revisit that later. Added a GPDB_84_MERGE_FIXME comment about that too.

This has been discussed offline by @danielgustafsson and @adam8157 if they could add context that would be appreciated.

**Comment by adam8157** [comment]
PostgreSQL 8.4 already had this optimization, split the loop into two parts, inside quotes, and outside quotes. We were planing to adopt this function's implement in PG8.4, will get back to this issue and confirm the details.

**Comment by yydzero** [comment]
@adam8157 could you please share on what is your discussion with @danielgustafsson about this? Any conclusion? Thanks!

**Comment by adam8157** [comment]
@yydzero we agreed that function has no feature difference between 8.3 and 8.4, so it's OK to leave it the same. And we decided to build it from 8.4 version, add the role check and some string api changes, but it turns out not easy enough to get it done on time.

So here we are, and it's in my to-do list.

**Comment by yydzero** [comment]
Thanks @adam8157

**Comment by adam8157** [comment]
Fixed a1648bcac48fc7b71094a96cb1a5e62fe014be80
