### ISSUE TITLE
Is there any data cache in gpdb?

### ISSUE THREAD

**Issue by demilich** [greenplum-db/gpdb#4035]
I just did a query test on gpdb and opened \timing option. I found the query time was almost same, though I tried several times. I though there should be some data cache mechanism and the time cost should be shorter after first query.

I just use: SELECT xxx FROM tablexxx WHERE condition.

**Comment by d** [comment]
Yes there are several quite common caching mechanisms in place. Can you describe the steps (queries) you used?

**Comment by demilich** [comment]
Will the tuples be cached, after gp access them? Especially on AOCS storage, I found gp will read the files, get the tuples from different column file according to the project. Am I right? After filter these tuples according to the where EXPR, will these tuples are cached? Thank you for help.

**Comment by asimrp** [comment]
No, the tuples obtained from AO or AOCS tables are not cached.  The underlying segment files are opened each time a table needs to be scanned.  This is different from HEAP tables, where tuples are cached in a shared buffer cache.  One of the main reasons for not reusing the shared buffer cache for AO/AOCS is the append-only nature of the underlying segment files.  In case of insert/update, each transaction is allocated a distinct AO/AOCS segment file, so that concurrent insert/update to the same table are isolated.  For more details on AO/AOCS storage, please refer to https://github.com/greenplum-db/gpdb/blob/master/src/backend/access/appendonly/README.md

**Comment by demilich** [comment]
Thank you for your prompt response.
-  "In case of insert/update, each transaction is allocated a distinct AO/AOCS segment file", do you mean if I insert/update one tuple each transaction. Lots of segment files will be created. Am I right?
- Talking about the shared buffer cache, what kind of cache it is? We all know a new process will be forked to handle the query in segment server. So, are the shared buffer cache used by multi-processes?
- Since gp is multi-process model, how to synchronize the access to the HEAP tables or AO/AOCS tables access? What kind of method are used?

**Comment by yydzero** [comment]
@asimrp with cache, will it speed up pure concurrent SELECT queries in TPC-H (with where conditions)?

**Comment by asimrp** [comment]
> "In case of insert/update, each transaction is allocated a distinct AO/AOCS segment file", do you mean if I insert/update one tuple each transaction. Lots of segment files will be created. Am I right?

Clarification: only in case of concurrent transactions inserting/updating the same AO table, each one gets a distinct segment file.  If two or more transactions insert into an AO table one after the other (not concurrently), the same segfile is reused.

> Talking about the shared buffer cache, what kind of cache it is? We all know a new process will be forked to handle the query in segment server. So, are the shared buffer cache used by multi-processes?

As the name suggests, shared buffer cache is a cache of buffers (data pages) shared between multiple processes.  Please refer to the [README](https://github.com/greenplum-db/gpdb/blob/master/src/backend/storage/buffer/README) for more details on how the cache is used.

> Since gp is multi-process model, how to synchronize the access to the HEAP tables or AO/AOCS tables access? What kind of method are used?

The readme cited above will provide answers regarding concurrently accessing tuples in a heap table.  For AO/AOCS, as noted above, concurrent insert/update transactions on the same AO table operate on separate files.

These are great questions, please feel free to ask more as I'm sure the answers are shot.  Also, please consider leveraging gpdb-dev mailing list instead of GitHub issues for such discussions.

**Comment by asimrp** [comment]
> with cache, will it speed up pure concurrent SELECT queries in TPC-H (with where conditions)?

Note that kernel buffer cache is still in use for AO/AOCS.  If we want to build another layer on top of that, similar to shared buffer cache for heap, the variable blocksize in AO poses a challenge.

**Comment by hlinnaka** [comment]
I don't think there's anything more to do here, closing.

**Comment by yjhjstz** [comment]
since the variable blocksize in AO poses is a challenge, if we use fixed blocksize which may speed up a lot .
