### ISSUE TITLE
getversion output 5.0.0 in 5.3.0 release tar?

### ISSUE THREAD

**Issue by hanjirui** [greenplum-db/gpdb#4234]
I download the 5.3.0 release version tar and run the getversion command, but the output is 5.0.0 build dev.  
Then I git clone the repository and checkout the 5.3.0 tag, the getversion result is 5.3.0 build dev.

**Comment by hsyuan** [comment]
thanks for reporting, there is already a same issue #4165.
@pivotal-mike Can toolsmith take a look?

**Comment by pivotal-mike** [comment]
@hsyuan Toolsmiths are an internal team to pivotal for providing infrastructure and really have no say in this kind of thing.

The problem is that it’s pulling the version from the configure script.  If we change it there then it breaks binary compatability for extentions (e.g. Madlib, PL/*) since the code uses 2 digits to verify major version, not one.  Fix there is to backport from 10 a change to dmgr.c.

@hanjirui I raised this on the developer list last month here: https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/7qjwvMoSRp8

**Comment by kapustor** [comment]
As i see, Pivotal Greenplum build (downloaded from official Pivotal site) has version 5.3.0:

```
adb2=# select * from version();
...
 PostgreSQL 8.3.23 (Greenplum Database 5.3.0 build commit:2155c5a8cf8bb7f13f49c6e248fd967a74fed591) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Dec  5 2017 1
9:10:20
```
MADlib (downloaded from madlib site, not from pivotal package) installs and works fine:
```
[gpadmin@mdw ~]$ /usr/local/madlib/bin/madpack -p greenplum -c gpadmin@localhost:5432/adb install
madpack.py: INFO : Detected Greenplum DB version 5.3.0.
madpack.py: INFO : *** Installing MADlib ***
madpack.py: INFO : MADlib tools version    = 1.13 
...
madpack.py: INFO : MADlib 1.13 installed successfully in MADLIB schema.
```
PL/Python and PL/Perl aslo work fine.

So are there any binary compatability issues now? Maybe we should change the version?

**Comment by ivannovick** [comment]
seems no issue here
