### ISSUE TITLE
Packages missing and not verified by ./configure

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#436]
Running "make" in the GPDB source tree fails, if the following packages are not installed (on Debian):
- libapr1-dev
- libevent-dev
- libssl-dev
- libyaml-dev

It always fails in "gpAux/extensions", after "make" in the top directory already compiled a great part of the code.

Because these packages are required in order to build GPDB, the existence should be checked in the top "./configure" script, before "make" is run.

**Comment by danielgustafsson** [comment]
I believe these will all be covered by #351 and #434 which both extend the autoconf script to gather all the requirement upon configuration.

**Comment by andreasscherbaum** [comment]
I only see yaml and apr in #351.

**Comment by Chibin** [comment]
#351 has been pushed into master, those packages should be checked in the configure now.

**Comment by andreasscherbaum** [comment]
Add Python "psi" to the list.

**Comment by hlinnaka** [comment]
On 29/02/16 00:07, Andreas Scherbaum wrote:
> Add Python "psi" to the list.

Shreedhar, you did some investigation on the "psi" dependency, didn't 
you? Can we get rid of it?

- Heikki

**Comment by hlinnaka** [comment]
I don't know,

"psi" is an old python utility package used to get process information on
the system. It looks hasn't been developed on since around 2009 (
https://bitbucket.org/chrismiles/psi/wiki/Home). There a number of pull
requests open since a number of years.

I was trying to asses if we can replace it with a more modern psutils
library (https://github.com/giampaolo/psutil) , or remove it all together.
By the way, both of these are available via pip.

I do not have sufficient background on what these scripts are used for, and
why they need to get information about child processes this way, but all
they use the "psi" for is listing out all the processes running (that they
have access to), and "grep"-ing the list to find those that they intend to
kill. This can be done without the dependency on this package, certainly by
using os.system("ps aux") and parsing the output of that and os.pkill(pid),
or by os.system(pkill string) or by just letting psi/psutils do the parsing
for us.

I am of the opinion that we should upgrade psi to psutils (also because
it's more portable). Unfortunately I don't know much more about these
scripts yet to know if we can just gut the dependency out.

For completeness, it's used in following python scripts:

$GPDB_HOME/gpAux/gpperfmon/src/gpperfmon.py:
- lightly_stop() to get PIDs of processes that have bin/lighttpd and or
lighttpd.conf in the process invocation.
- lightly_status() to get PIDs of processes that have lighttpd.conf or
gpmonws.py in the invocation
- kill_orphaned_cgi_scripts() having gpmonws.py in the invocation again.

$GPDB_HOME/gpMgmt/bin/gppylib/commands/unix.py:
getDescendentProcesses(pid): searchs the process of all (recursive)
dependants

$GPDB_HOME/./gpMgmt/bin/gppylib/programs/kill.py:
examine_process(pid): Again, to look at the arguments of the process.

 (and some test code)


-Shreedhar




On Sun, Feb 28, 2016 at 8:33 PM, Heikki Linnakangas <hlinnakangas@pivotal.io
> wrote:

> On 29/02/16 00:07, Andreas Scherbaum wrote:
>
>> Add Python "psi" to the list.
>>
>
> Shreedhar, you did some investigation on the "psi" dependency, didn't you?
> Can we get rid of it?
>
> - Heikki
>
>

**Comment by hlinnaka** [comment]
I agree with @hardikar, that we should replace 'psi' with 'psutils'. Not being a python hacker, and because I don't know what all those scripts do or how to test them, I'm not volunteering to do that work..
