### ISSUE TITLE
appendonlyam.c missing AppendOnlyBlockDirectory_InsertEntry?

### ISSUE THREAD

**Issue by vitesse-ftian** [greenplum-db/gpdb#4451]
### Greenplum version or build
master

### Step to reproduce the behavior

appendonlyam.c, there are two places that we may write a block, around line 1520 for normal path, and line 3010 for writing lob.   Only the normal path we add an InsertEntry -- this is really strange logic, why lob is treated differently?    Should InsertEntry be called for large row as well?

I am not exactly sure because the code path is more complex than I expected.

**Comment by yydzero** [comment]
@asimrp @ashwinstar would you please help to answer this?

@vitesse-ftian do you have any bad sql to produce issue? will be helpful to add a test to validate fix if provided.

**Comment by vitesse-ftian** [comment]
@yydzero No, I don't have a test -- just from inspection of the code.   Looks wrong.

**Comment by ashwinstar** [comment]
This commitfe1b76167a27b845774493bcfe4447787aefbd27 and ace8b8a5ba42baa7079c05abafb77ee0f5acf312 I believe fixed the problem reported here. @vitesse-ftian since issue only mentions line numbers which are changed, little fuzzy to know. Can you check latest code to confirm problem you were seeing from code inspection no more exists.

**Comment by vitesse-ftian** [comment]
Probably not related to the changes.   But, the master has quite some changes, I cannot be sure what does this issue mean by now.   Let me close it.
