### ISSUE TITLE
COPY FROM PROGRAM ON SEGMENT fails with large number of tables in single session on Mac

### ISSUE THREAD

**Issue by chrishajas** [greenplum-db/gpdb#4575]
### Greenplum version or build
Greenplum Database 6.0.0-alpha.0+dev.3783.g84c5b6988b build dev-oss

(This issue was not observed on other GPDB versions)

### OS version and uname -a
macOS Sierra and Yosemite

We do not see this issue on Linux. We've only seen it on Mac on the master branch.

When performing COPY FROM PROGRAM .. ON SEGMENT on over ~200 tables in a single session, the COPY statement fails with `psql:create_tables.sql:601: ERROR:  can not start command: cat /tmp/foo1-0.csv  (seg0 127.0.0.1:25432 pid=68375)`. If I instead run these copy statements in separate sessions, they succeed. It appears it's hitting an error case in `open_program_pipes()` in `src/backend/commands/copy.c`.

### Step to reproduce the behavior
When we have more than ~2-300 tables in a database and run a standard gpbackup then gprestore, gprestore will fail around the 200th table.

Repro script:

```
#!/bin/bash
rm -f create_tables.sql

for i in {1..300}; do
  echo "CREATE TABLE foo$i(i int) DISTRIBUTED BY (i);" >> create_tables.sql
  echo "COPY foo$i TO PROGRAM 'cat > /tmp/foo$i-<SEGID>.csv' ON SEGMENT CSV;" >> create_tables.sql 
done
for i in {1..300}; do
  echo "COPY foo$i FROM PROGRAM 'cat /tmp/foo$i-<SEGID>.csv' ON SEGMENT CSV;" >> create_tables.sql
done
```

**Comment by adam8157** [comment]
What's your `ulimit -a` outputs?

`COPY PROGRAM` forks processes, which has a limit, especially when you have multiple segments on a single system.

**Comment by liming01** [comment]
Although I cannot reproduce on my macos with ulimit -n 65535, however I guess that there still have some code branch forget to release pipe file description.

**Comment by liming01** [comment]
I can reproduce it with the default value of ulimit -n: file descriptors                7168.

**Comment by liming01** [comment]
After a long time investigation, I found there is no file descriptor leak in this case.
The reason is:
If I change ulimit setting to: "-n: file descriptors 7500", which is 332 more than the default value.
And also change the loop number from 300 to 900 in the reproduce steps, no error issues.
If any file descriptor leak, even 1 fd leak for one loop, then the error will issues.

But in other case when the program process exit before gpdb parent process ask, it still has some leak. I created PR https://github.com/greenplum-db/gpdb/pull/4585 to fix it.

**Comment by chrishajas** [comment]
Was there a change between master and 5X_STABLE? I haven't been able to repro the issue on 5X_STABLE. Specifically, I believe prior to the last postgres merge it didn't have this issue.

**Comment by liming01** [comment]
I tried the commit before last postgres merge, it still has this problem:
git bisect bad 4237a7a5313a9b1fbf253c33fe39a9fe58fe3d35 

But below commit works fine:
git bisect good 110b825f2319e2275faec6f34af42e48f778435f

However there are too many commits between them:
Bisecting: 300 revisions left to test after this (roughly 8 steps)

So it is better to change the setting, because from the pgdb init step, a warning issues: 
20180301:17:15:13:069343 gpinitsystem:Mrmbp:gpadmin-[WARN]:-Host Mrmbp.local open files limit is 7168 should be >= 65535

**Comment by chrishajas** [comment]
After updating to the recommended system configuration settings (ulimit=65536), I don't encounter this issue when running the script above with 70k tables. I'm not sure what could have caused this change on master and not 5X_STABLE, but as long as we're confident that this isn't a scale issue that would be encountered on databases with many tables, I'm ok with closing this issue. Thanks for your help!

**Comment by liming01** [comment]
Thanks @chrishajas.
