### ISSUE TITLE
postmaster_alive_fds is not initialized.

### ISSUE THREAD

**Issue by baobao0206** [greenplum-db/gpdb#5010]
### Greenplum version or build
5x master
### Expected behavior
The wal writer could get a pipe hung up status from postmaster_alive_fds if postmaster dead.
### Actual behavior
The wal writer could get nothing.

### Step to reproduce the behavior

This issues would be fixed after merging of pg9.2 on master. Just put a issue here and remind me to pick code from master to 5x after merging of pg9.2.

**Comment by hlinnaka** [comment]
PostgreSQL 9.2 merge is now complete.

**Comment by yydzero** [comment]
@baobao0206 would you please double check this? Thanks!

**Comment by baobao0206** [comment]
@yydzero Yeah，I will check it。

**Comment by asimrp** [comment]
@baobao0206 do you have a way to reproduce this problem?  Can we try it again on 6X and master to see if it is already fixed?

**Comment by ashwinstar** [comment]
The issue doesn't have many details to confirm what the problem was and if it's solved or not. GPDB6 is based on PG9.4 with rebased till the latest STABLE version of it. And the master branch is based on PG12. From the reading of the issue doesn't seem GPDB specific, hence believe with a refresh from upstream this won't be any issue anymore.
