### ISSUE TITLE
Unknown -- unable to load segment status

### ISSUE THREAD

**Issue by leciel0701** [greenplum-db/gpdb#5055]
Hi!
When I run 'gpstate -s'
I got WARNING about every segment like this:
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-   Segment Info
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      Hostname                          = segment12
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      Address                           = segment12
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      Datadir                           = /home/gpadmin/gpdata/gpdatam2/gpseg7
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      Port                              = 43001
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-   Mirroring Info
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      Current role                      = Mirror
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      Preferred role                    = Mirror
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      Mirror status                     = Synchronized
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-   Status
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      PID                               = 14740
20180529:10:08:12:018034 gpstate:master10:gpadmin-[INFO]:-      Configuration reports status as   = Up
20180529:10:08:12:018034 gpstate:master10:gpadmin-[WARNING]:-   Segment status                    = Unknown -- unable to load segment status   <<<<<<<<

SELINUX=disabled & firewalld is stopped & iptables added role like -s xxx.xxx.xxx.xxx -p all
Why I can't get the status

AND THEN I do select * from gp_segment_configration;
 dbid | content | role | preferred_role | mode | status | port  | hostname  |  address  |                datadir                
------+---------+------+----------------+------+--------+-------+-----------+-----------+---------------------------------------
    1 |      -1      | p    |       p              |      n   | u      |  5432 | master10  | master10  | /home/gpadmin/gpdata/gpmaster/gpseg-1
    9 |       7       | p    |      p              | s         | u      | 33001 | standby11 | standby11 | /home/gpadmin/gpdata/gpdatap2/gpseg7

HOW THE 'mode' CAN BE 'n' & What's 'n' mean?

Anybody could help?Thanks!

**Comment by jimmyyih** [comment]
Hi @leciel0701.  It seems like you are trying out the master branch (currently 6.0devel).  The `gpstate -s` command currently does not work because it relied on File Replication API calls.  On the master branch (6.0devel), we have replaced File Replication with WAL replication.  It's currently in active development so there may be missing parity until we cut the Greenplum 6.0 stable branch.  The `gpstate -s` command should be fixed by then.

The mode column in `gp_segment_configuration` has been changed during this transition as well.  In File Replication (Greenplum 4.3 and 5), mode can be s (synchronized), c (changetracking), or r (resynchronization).  For WAL Replication (Greenplum 6 and later), mode will now be either s (synchronized) or n (not synchronized).  In your example output, it shows that the master is not synchronized with the standby master.  However, this is just a known UX bug which we intend to fix before Greenplum 6.0 stable branch is created.  The master and standby master are most likely synchronized if you check `pg_stat_replication` or `gp_stat_replication` (if you see state STREAMING, they are synchronized).

It's much appreciated that you are trying out the master branch but please be aware that it is not yet ready for production environments.  For production, I would suggest using our latest Greenplum 5 (https://github.com/greenplum-db/gpdb/tree/5.8.0).

**Comment by leciel0701** [comment]
Thank you!@jimmyyih 
I'll try Greenplum 5
