### ISSUE TITLE
Ssh-exkeys makes all keys in authorized_keys file authorized, not just keys necessary for intra-node communication

### ISSUE THREAD

**Issue by dotyjim-work** [greenplum-db/gpdb#5069]
### Greenplum version or build
Observed on 4/5/master

### Actual behavior

(assume for simplicity that we are a user running  `gpssh-exkeys` from the master node)

When the user run `gpssh-exkeys` from a node (often time the master node), it takes the existing contents of the `authorized_keys`  file and appends the public half of the keys of each host in the cluster to that file, and then distributes that file to each node.  What this doesn't take into account is that the list of keys in the `authorized_keys` file may include more than just the keys identifying the OS users for each node in the cluster.  It is quite possible that this file includes authorized keys for users that are authorized to access the master node.  In this case the utility has now made those user's keys authorized to ssh to every node.  This behavior may not be desired, or obvious.

### Expected behavior

I would expect that the utility that we ship with the product to authorize intra-cluster ssh'ing, but not to take existing keys from the host that the command has been run from and place those authorized keys on every node.

**Comment by doty-pivotal** [comment]
@Tylarb - here is the issue we discussed.

**Comment by Tylarb** [comment]
As a demonstration of this behavior, observe this:

On the master, we add some key which is not on any node or desired to be on the node:

master:

~~~
[root@master75FIPS ~]# grep test .ssh/authorized_keys
ssh-rsa TESTkeyzaC1yc2EAAAADAQABAAABAQCTZ0DI0bmPbNDsCSInaHOjyrwAfwmzf3RQOGL4wBCUNIstfud2btVdyFJNTSybSeXTFZJ/dPp0I/05s+pVed09Ky4iYmXnLOzkGkuNNVzA8I7lQk2Umr4aiigv6JRCIFTmb2rWPxe9UaBJjKRDPHSmNUTGALDdrmB9NFwwvhYsDKYCipYOqN6M7Go1qW8D9u812ChXEhMNVLJG4p7lUzVVkO0x9yRhL14/DBkXjzfUB+mgTrkT8MEFDQXtnt+HfNp77oBrJLn9XuxCPVXWfRGopoGqXXD0NpcCmY0Lg1uWLUM0xoHJIDNfy8ix9ysvWz5SIjrDe0mseJMnTGtL7Tb1 testuser@example.com
~~~

Node:
~~~
[root@node75FIPS ~]# grep test .ssh/authorized_keys -c
0
~~~

Exchange keys using the tool, and observe that the test user's key is now present on the node:

~~~
[root@master75FIPS ~]# gpssh-exkeys -h node75FIPS

(on the node)
[root@node75FIPS ~]# grep test .ssh/authorized_keys -c
1

[root@node75FIPS ~]# grep test .ssh/authorized_keys
ssh-rsa TESTkeyzaC1yc2EAAAADAQABAAABAQCTZ0DI0bmPbNDsCSInaHOjyrwAfwmzf3RQOGL4wBCUNIstfud2btVdyFJNTSybSeXTFZJ/dPp0I/05s+pVed09Ky4iYmXnLOzkGkuNNVzA8I7lQk2Umr4aiigv6JRCIFTmb2rWPxe9UaBJjKRDPHSmNUTGALDdrmB9NFwwvhYsDKYCipYOqN6M7Go1qW8D9u812ChXEhMNVLJG4p7lUzVVkO0x9yRhL14/DBkXjzfUB+mgTrkT8MEFDQXtnt+HfNp77oBrJLn9XuxCPVXWfRGopoGqXXD0NpcCmY0Lg1uWLUM0xoHJIDNfy8ix9ysvWz5SIjrDe0mseJMnTGtL7Tb1 testuser@example.com
~~~

As a brief summary, the tool copies the `authorized_keys` file from whichever system the command is run to all destinations. This means that every key which has access to the master now has access to the nodes. 

A better behavior would be to create a temporary `authorized_keys` file which includes ONLY the current user's key, then disperse this temporary file, rather than the "master" `authorized_keys` file.

**Comment by ivannovick** [comment]
@Nirali13 can you check if this is still an issue that needs fixing

**Comment by ivannovick** [comment]
@sumitbasumallick is it a problem?

**Comment by sumitbasumallick** [comment]
@ivannovick This seems not an issue. 

The `gpssh-exkeys `utility performs key exchange using the following steps:

1. Adds the user's public key to the user's own `authorized_keys` file on the current host.
2. Updates the `known_hosts` file of the current user with the host key of each host 
3. Connects to each host using `ssh` and obtains the user's `authorized_keys`, `known_hosts`, and `id_rsa.pub` files.
4. Adds keys from the `id_rsa.pub` files obtained from each host to the `authorized_keys` file of the current user.
5. Updates the `authorized_keys`, `known_hosts`, and `id_rsa.pub` files on all hosts 

While invoking `gpssh-exkeys`, it removes and insert the current user key in `.ssh/authorized_keys` and exchange the `.ssh/authorized_keys` and other files across list of host provided in hostlist. 

If `.ssh/authorized_keys` already have few other user public keys (like testuser mentioned above), while coping `.ssh/authorized_keys` to other hosts these are getting propagated too but it will not do any harm in the segments where user (testuser) itself might not be there. 

If still this is undesirable behaviour , one could take backup of master `authorized_keys` before running `gpssh-exkeys` and remove master `authorized_keys`. Upon `authorized_keys` regeneration it will contains only all hosts exchange keys and no other undesirable keys, then just restore extra public keys belongs to master.

**Comment by sumitbasumallick** [comment]
Closing the issue, re-open if necessary.
