### ISSUE TITLE
qp_with_clause test fails if I temporarily change the random page cost from 100.0 to 4.0

### ISSUE THREAD

**Issue by paul-guo-** [greenplum-db/gpdb#5475]
Change cost for random page access in cost.h and build latest gpdb without ORCA on centos7.
```diff
- #define DEFAULT_RANDOM_PAGE_COST  100.0
+ #define DEFAULT_RANDOM_PAGE_COST  40.0
```

Run regression tests and found qp_with_clause test fails because it generates different result for the same query. Here is the diff output.

```diff
@@ -430,21 +430,10 @@
 select
 (select max(CNT) from diversecountries where  diversecountries.code = country.code) CNT,country.name COUNTRY,city.name CAPITAL
 from country,city where country.capital = city.id) FOO where FOO.CNT is not null;
- cnt |      country       |     capital
------+--------------------+------------------
-   7 | Denmark            | Kobenhavn
-   8 | Australia          | Canberra
-   8 | Austria            | Wien
-   8 | Italy              | Roma
-   8 | Myanmar            | Rangoon (Yangon)
-  10 | Iran               | Teheran
-  11 | South Africa       | Pretoria
-  12 | Canada             | Ottawa
-  12 | China              | Peking
-  12 | India              | New Delhi
-  12 | Russian Federation | Moscow
-  12 | United States      | Washington
-(12 rows)
+ cnt | country |  capital
+-----+---------+-----------
+   8 | India   | New Delhi
+(1 row)

======================================================================
```

I quickly compared the plan before and after the code change. There is slight difference of the plans which could be imagined. The plan is complex so I can not figure out why shortly so I'm creating the issue at first.

Since tablespace could define its own random page access cost so we should be able to hack the test case to reproduce this issue also instead of recompiling gpdb.

**Comment by hlinnaka** [comment]
You can also do simply `set random_page_cost=4` before running the query

**Comment by paul-guo-** [comment]
Yes, that's an easier way without recompiling gpdb. Thanks.

**Comment by hlinnaka** [comment]
This query, which is identical to the above, except that I turned the WITH query into a subquery, has the same problem:

```
postgres=# set random_page_cost=100;
SET
postgres=# select * from
(
select
(select max(CNT) from
(select country.code,country.name,country.capital,d.CNT
 from country, 
 (select countrylanguage.countrycode,count(*) as CNT from countrylanguage group by countrycode
  HAVING count(*) > 6) d
 where d.countrycode = country.code and country.gnp > 100000) as diversecountries
where  diversecountries.code = country.code) CNT,country.name COUNTRY,city.name CAPITAL
from country,city where country.capital = city.id) FOO where FOO.CNT is not null;
 cnt |      country       |     capital      
-----+--------------------+------------------
  12 | Russian Federation | Moscow
   7 | Denmark            | Kobenhavn
  12 | India              | New Delhi
   8 | Australia          | Canberra
  11 | South Africa       | Pretoria
   8 | Myanmar            | Rangoon (Yangon)
   8 | Italy              | Roma
  10 | Iran               | Teheran
   8 | Austria            | Wien
  12 | Canada             | Ottawa
  12 | China              | Peking
  12 | United States      | Washington
(12 rows)

postgres=# set random_page_cost=4;
SET
postgres=# select * from
(
select
(select max(CNT) from
(select country.code,country.name,country.capital,d.CNT
 from country, 
 (select countrylanguage.countrycode,count(*) as CNT from countrylanguage group by countrycode
  HAVING count(*) > 6) d
 where d.countrycode = country.code and country.gnp > 100000) as diversecountries
where  diversecountries.code = country.code) CNT,country.name COUNTRY,city.name CAPITAL
from country,city where country.capital = city.id) FOO where FOO.CNT is not null;
 cnt | country | capital 
-----+---------+---------
(0 rows)
```

I believe the bug is in the `QueryHasDistributedRelation(Query *q)` function. It scans the range table, and checks if it contains any distributed tables (i.e. not catalog tables, and not replicated tables). But it seems too simplistic: it doesn't recurse into RTE_CTE or RTE_SUBQUERY range table entries.

if the query is correctly recognized as containing a distributed table, then the planner will plan the subquery with (bitmap) index scans disabled, allowing only sequential scans. Changing `random_page_cost` also affects the decision on whether to use a bitmap scan. With the higher setting, the plan uses a Sequential Scan, which works, but with a lower setting, a bitmap index scan is chosen, which does not. You get the same effect if you use `set enable_seqscan=off` to persuade the planner to use a bitmap index scan.

**Comment by paul-guo-** [comment]
@hlinnaka Do you know why make_subplan() only allows seqscan in the code below? It seems that using other kind of scans lead to wrong results.

```
     if ((Gp_role == GP_ROLE_DISPATCH)
              && IsSubqueryCorrelated(subquery)
              && QueryHasDistributedRelation(subquery))
      {
<snipped> 
         /*
           * Only create subplans with sequential scans
           */
          config->enable_indexscan = false;
          config->enable_bitmapscan = false;
          config->enable_tidscan = false;
          config->enable_seqscan = true;
      }
```

**Comment by hlinnaka** [comment]
On 13/09/18 09:31, Paul Guo wrote:
> @hlinnaka Do you know why make_subplan() only allows seqscan in the code below? It seems that using other kind of scans lead to wrong results.
> 
> ```
>       if ((Gp_role == GP_ROLE_DISPATCH)
>                && IsSubqueryCorrelated(subquery)
>                && QueryHasDistributedRelation(subquery))
>        {
> <snipped>
>           /*
>             * Only create subplans with sequential scans
>             */
>            config->enable_indexscan = false;
>            config->enable_bitmapscan = false;
>            config->enable_tidscan = false;
>            config->enable_seqscan = true;
>        }
> ```
>

Yeah, see the comment above ParallelizeCorrelatedSubPlanMutator(). In a 
nutshell, the executor cannot pass parameters through a Motion node. For 
example, imagine a query like this, on PostgreSQL with no MPP:

postgres=# explain (costs off) select foo.id, (select count(*) from bar 
where foo.id = bar.id) from foo;
                       QUERY PLAN
-------------------------------------------------------
  Seq Scan on foo
    SubPlan 1
      ->  Aggregate
            ->  Index Only Scan using bar_id_idx on bar
                  Index Cond: (id = foo.id)
(5 rows)

In this plan, 'foo.id' is passed down as an "executor parameter", i.e. a 
Param node with type PARAM_EXEC, from the top Seq Scan on foo, down to 
the subplan and the Index Only Scan. If we parallelized this in the 
naive way, you would get something like this:

postgres=# explain (costs off) select foo.id, (select count(*) from bar 
where foo.id = bar.id) from foo;
                       QUERY PLAN
-------------------------------------------------------
  Seq Scan on foo
    SubPlan 1
      ->  Aggregate
            ->  Gather Motion
                 ->  Index Only Scan using bar_id_idx on bar
                       Index Cond: (id = foo.id)
(5 rows)

The GPDB executor cannot handle that, because there's no way to pass the 
the parameter from one segment to another (or from QD to QE, in this 
case), through the Motion node. So we force a plan like this, instead:

                                  QUERY PLAN 

-----------------------------------------------------------------------------
  Gather Motion 3:1  (slice2; segments: 3)
    ->  Seq Scan on foo
          SubPlan 1  (slice2; segments: 3)
            ->  Aggregate
                  ->  Result
                        Filter: foo.id = bar.id
                        ->  Materialize
                              ->  Broadcast Motion 3:3  (slice1; 
segments: 3)
                                    ->  Seq Scan on bar
  Optimizer: legacy query optimizer
(10 rows)

This plan works, because the query parameter (foo.id) is evaluated at 
the Result node, which runs on the same slice as the Seq Scan at the 
top. We cannot use an index scan, because we cannot use the query 
parameter at the Scan node, we can only evaluate it above the Broadcast 
Motion.

This is obviously super-inefficient. We're broadcasting the contents of 
every relation that's used in the subplan, to all segments. It would be 
nice to do something more clever here. This is also the reason there's 
more code to "pull up" subqueries in GDPB than in PostgreSQL. The 
penalty of not being able to pull up a subquery is much higher in GPDB.

It would be nice to be able to pass parameters through a Motion node...

- Heikki

**Comment by paul-guo-** [comment]
Great explanation, thanks!

**Comment by paul-guo-** [comment]
Verified. Closing.
