### ISSUE TITLE
[HTAP] Don't dispatch all values to every segment

### ISSUE THREAD

**Issue by adam8157** [greenplum-db/gpdb#5987]
This is a feature very nice to have for some corner TP cases I guess, comes from a local user, Mr. Xu, who has queries with hundreds even thousands of values to insert but not fit for COPY.

### Step to reproduce the behavior
1, attach to a segment
2,
```
gpadmin=# set gp_vmem_idle_resource_timeout=120000;
SET
gpadmin=# create table tbl (c1 int) distributed by (c1);
CREATE TABLE
gpadmin=# insert into tbl values (1),(2),(3),(4),(5);
```
3,
```
(gdb) b exec_mpp_query
```

### Expected behavior
Only the values which will be hashed to that segment are dispatched

### Actual behavior
```
Breakpoint 3, exec_mpp_query (query_string=0x2ce3220 "insert into tbl values (1),(2),(3),(4),(5);"
```

**Comment by adam8157** [comment]
@pivotal-ning-yu do you have an idea?

**Comment by xfg0218** [comment]
The same problem, thank you

**Comment by Eulerizeit** [comment]
Can you attach to a segment without being in utility mode? 

I'm very opposed to customers using utility mode, there are intentionally few/no protections for customers.

**Comment by Eulerizeit** [comment]
Could you describe a bit more about what you mean by
>has queries with hundreds even thousands of values to insert but not fit for COPY.

**Comment by adam8157** [comment]
It's just the QE not utility mode.

The user has an ETL tool which generates INSERT statements, with lots of values to insert in every single line.

**Comment by d** [comment]
This is how Value Scan works. Pretty sure we won't fix it. Write better
SQL, e.g. use COPY.

Jesse

**Comment by hlinnaka** [comment]
I agree with @d that we're not going to do anything about this in the short term. But I'd like to clarify what's happening here:

The SQL text that gets dispatched to all the segments is actually just for debugging purposes. It's not needed for executing the command, but it can be *very* handy when debugging. Commit 08f6b6dcf9 improved the situation, so that if the SQL command is very long, we only send a truncated version of it to the segments.

That's not all, though. The QD also send the Plan tree of the whole query to every segment, in the same message. In case of a VALUES query, the ValuesScan plan node includes all the values, whether or not they're needed on that segment. The plan tree is compressed, but it can still be very large. We could improve on that, by sending only the parts of the Plan tree to the segment process, that's actually needed in that process. I'm not sure if it would be worth the extra effort in the QD to strip the plan like that, in the general case, but it would certainly help this example.  The plan tree looks like this:
```
postgres=# explain insert into tbl values ('foo1'),('foo2'),('foo3'),('foo4'),('foo5');
                                       QUERY PLAN                                        
-----------------------------------------------------------------------------------------
 Insert on tbl  (cost=0.00..0.06 rows=2 width=32)
   ->  Redistribute Motion 1:3  (slice1; segments: 1)  (cost=0.00..0.06 rows=5 width=32)
         Hash Key: "*VALUES*".column1
         ->  Values Scan on "*VALUES*"  (cost=0.00..0.06 rows=2 width=32)
 Planning time: 1.021 ms
 Optimizer: legacy query optimizer
(6 rows)
```
So it only executes the Values Scan in one process, which sends the rows to the correct segments. You'd only really need the ValuesScan plan node in that one process.

This is clearly a feature request though. If you're interested in working on this, patches are welcome! I agree with @d, though, that in the short term it's probably easier to just change the application to not do that.

**Comment by kainwen** [comment]
I do not think we can do anything about this. This means we need to dispatch to different QE with different plans, this is not an easy job.
