### ISSUE TITLE
How can I trigger "log_invalid_page" during recovery

### ISSUE THREAD

**Issue by Dontpushme** [greenplum-db/gpdb#6612]
### Greenplum version or build
latest master

As far as I know "log_invalid_page" is called when I tend to read a page that not exist during recovery, and put it into a list, it will be forgeted if there is a xact_redo that actually perform a "drop table" or "truncate" action.

But now, the real "unlink file" action is been delayed to next "checkpoint", so, for now, "log_invalid_page" will never happend during recovery, is that correct? if not, how can I trigger it.

I hope someone could help me, and I realy truly appreciate you

**Comment by hlinnaka** [comment]
The real unlinking is delayed until next checkpoint, but the file is truncated to 0 bytes immediately.

Even without dropping a table, you can encounter that if you e.g. delete all rows on the last pages of a table, and then vacuum it, so that the vacuum truncates away the page and shrinks the file. If you then crash and restart, crash recovery will see the WAL records of the deletions first, but the physical file has already been shrunk, so the page doesn't exist, and `log_invalid_pages` gets called.

Except that there's one more thing that's masking that: full-page writes. In the above scenario, the first update on the page will actually include a full-page image of the record, and replaying will expand the file back to the original size, instead of calling `log_invalid_pages`. If you set `full_page_writes=off`, though, you should be able to make that happen.

Another case is Point-In-Time-Recovery, or restoring from an online-backup. Those can span multiple checkpoints, without performing a restartpoint in between.

**Comment by Dontpushme** [comment]
that's exactly what you said! thanks!!!
