### ISSUE TITLE
Append-only tables do not support unique indexes. Is it possible to do so?

### ISSUE THREAD

**Issue by KAdamsInCO** [greenplum-db/gpdb#6616]
### Greenplum version or build

GPDB 5.15

### OS version and uname -a

CentOS 7.x

### Step to reproduce the behavior

Is it technically feasible to enable unique indexes on AO tables / partitions at some point in the future?

testdb=# create unique index my_index on items(item_id);
ERROR:  append-only tables do not support unique indexes
testdb=#
testdb=# create index my_index on items(item_id);
CREATE INDEX

I work with customers who run into this, and don't understand why they can't create a unique index on the distribution column(s) of a table, when they can create a non-unique index without issue. Having the ability to create a unique index on an AO table / partition would be really useful.

Thanks.

**Comment by d** [comment]
This is currently not possible

**Comment by ashwinstar** [comment]
Let me post one of the hurdles I think for implementing unique/primary key indexes on AO / CO tables. AO / CO tables while insert session is in progress and entries are added to the table and index, do not provide any mechanism to trace down which transaction inserted it until block directory entry is created which has transaction ID for it. This is very unlike heap. In heap at every point in time one can reach from index to tuple and find which transaction inserted id.

Now why this causes hurdle, because to implement unique key index need to figure out if a conflicting row has been inserted by an as-yet-uncommitted transaction. The new transaction inserting must wait to see if the other in-flight transaction commits. If it rolls back, then there is no violation. If it commits there is a uniqueness violation.

As known Index by itself doesn't have transaction ids so physically it might store duplicate keys even in case of unique index. What's required is no MVCC snapshot include two rows with equal index keys.

Block Directory for AO/CO provides capability to check from MVCC stand-point what's visible and what's not. But entry into block-directory is created not at tuple level but once block is full and written to disk. So, during the time while the block is being created there is no way for con-current transaction to know if its in-flight / not there. For heap, the base table entry is made first and then index entry is made and hence in-flight transaction can be found and waited for to decide to commit/rollback to enforce uniqueness.

One of the possible solutions to overcome this issue, create block directory entry when the insert transaction starts with correct starting row number but infinite / last row number for that segment file. At end of insert update the block directory entry with correct last row number. Since anyways only one transaction can be inserting at a time to a segment file. That provides then way to find in-flight transaction Id for AO/CO tables. Downside though is block directory table bloat.

Also, I think updates and deletes pose challenges for implementing unique index but not given thought on what those are specifically.

**Comment by xiaozhongwang** [comment]
> This is currently not possible

Is the current design cannot be realized, or has not yet been realized?

**Comment by soumyadeep2007** [comment]
>> This is currently not possible

> Is the current design cannot be realized, or has not yet been realized?

Lets say it hasn't been realized yet. We are still discussing it.

> One of the possible solutions to overcome this issue, create block directory entry when the insert transaction starts with correct starting row number but infinite / last row number for that segment file. At end of insert update the block directory entry with correct last row number. Since anyways only one transaction can be inserting at a time to a segment file. That provides then way to find in-flight transaction Id for AO/CO tables. Downside though is block directory table bloat.

Some of the things we can do here is to (notes from offline discussion w/ @ashwinstar ):
* Use in-place heap update of the blkdir relation when blkdir entry gets written (at end of command or when blkdir entry is full) to sidestep the block directory bloat issue that Ashwin mentioned above. 
     * This should be safe as we are modifying a tuple that we are inserting (at the start of the insert) inside the context of the same command.
     * In-place updates are generally discouraged as they depart from the regular MVCC workflow, so we will have to be careful about pitfalls and also make any related code changes extremely visible.
* Completely do away with the ending row number, so we can always insert the blkdir tuple. This will lead to more code changes of course, as we will have to fetch 2 minipage entries instead of one in certain code paths. There are performance implications to this too.

Tomorrow problem:
Expanding on the solution that Ashwin proposed, we could also explore solutions to reduce the seemingly random lookups that will be made against the blkdir while doing conflict resolution for these unique indexes. (There is a high probability that the index for the blkdir as well as the blkdir rel itself will be in shared buffers but we could maybe improve/guarantee that somehow)

**Comment by soumyadeep2007** [comment]
Unique indexes are supported now on AO/CO tables!

Relevant PRs:
https://github.com/greenplum-db/gpdb/pull/14089
https://github.com/greenplum-db/gpdb/pull/14097
https://github.com/greenplum-db/gpdb/pull/14270
https://github.com/greenplum-db/gpdb/pull/14414
https://github.com/greenplum-db/gpdb/pull/14422
https://github.com/greenplum-db/gpdb/pull/14425
https://github.com/greenplum-db/gpdb/pull/14481

Blog post outlining syntax, internals, performance and best practices:
https://greenplum.org/gp7-unique-indices-aoco/
