### ISSUE TITLE
gpexpand fails, if a table is renamed or moved to different schema after expansion started.

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6886]
If a table is renamed or moved to a different schema after expansion has started, gpexpand will fail to expand it. gpexpand constructs the fully-qualified name of the table at the beginning, and uses it in the ALTER TABLE EXPAND command later. If the table or schema name has changed in between, the ALTER TABLE command will fail.

**Comment by hlinnaka** [comment]
Renaming the schema or database has the same problem.

**Comment by dujialun** [comment]
The table gpexpand.status_detail will not only record the pending tables but can allow the user to adjust the expand order by changing the rank value(which has been deleted in e2c8b17863eba0ba7ea2eb1b6babcefafca16e00, but we will get it back soon). So finding pending tables by numsegments in gp_distribution_policy is not a good solution.
If we record the table oid besides schema.tablename, and get the latest name from catalog by oid. The user may be puzzled by the out-dated table name. And we cannot create a view to translate the name from oid, because these tables are from different databases.
So I think we should keep the current behavior. The only disadvantage is that the user should do expand him-self according to failing list after expansion.

**Comment by gaos1** [comment]
Per Jialun's comments, it seems that we cannot do better than keeping current behaviors and let users expand those tables.  please reopen or comment if you have more idea.
