### ISSUE TITLE
Wrong warning during configure related to flex version

### ISSUE THREAD

**Issue by armenatzoglou** [greenplum-db/gpdb#691]
I am trying to build GPDB on Ubuntu 16.04, using flex 2.6.0 and I am getting the following wrong warning:

checking for flex... configure: WARNING:
*** The installed version of Flex, /usr/bin/flex, is too old to use with Greenplum DB.
*** Flex version 2.5.4 or later is required, but this is flex 2.6.0.
configure: WARNING:
*** The installed version of Flex, /usr/bin/lex, is too old to use with Greenplum DB.
*** Flex version 2.5.4 or later is required, but this is lex 2.6.0.
no
configure: WARNING:
*** Without Flex you will not be able to build PostgreSQL from Git nor
*** change any of the scanner definition files.  You can obtain Flex from
*** a GNU mirror site.  (If you are using the official distribution of
*** PostgreSQL then you do not need to worry about this because the Flex
*** output is pre-generated.)

**Comment by hlinnaka** [comment]
The autoconf code we use to detect flex version is inherited from upstream. Can you check if you get the same error with PostgreSQL, please? If you do, then please report this to pgsql-hackers and we'll pick the fix from there.

**Comment by danielgustafsson** [comment]
AFAICT it is a bug inherited from upstream where the assignment operator is used instead of the equality operator. Posted question and patch to pgsql-hackers and will backport once it has been cleared out there.

http://www.postgresql.org/message-id/CC00E097-CCF0-41F9-A289-D1F729B5D006@yesql.se

In the meantime you should be fine building, it's a warning rather than an error and GPDB should build properly anyways.

**Comment by danielgustafsson** [comment]
This was fixed in #695 as well as upstream, thanks for the report.
