### ISSUE TITLE
ERROR:  tids are not in order when building the bitmap index

### ISSUE THREAD

**Issue by zhangjackey** [greenplum-db/gpdb#7039]
### Greenplum version or build
Master

### Actual behavior
Raise an error:
```
[ERROR]:-Table regression.public.delta_blocks failed to expand: error 'ERROR:  tids are not in order when building the bitmap index: new tidnum 2199023321089, last tidnum 2199023353856 (bitmapinsert.c:1835)  (seg2 10.254.0.78:25436 pid=122709) (bitmapinsert.c:1835)
```

### Step to reproduce the behavior

```
Create table delta_blocks(a1 integer ) with(appendonly=true)  ;
Create index dl_bt_ix on delta_blocks using bitmap(a1);
Insert into delta_blocks select
    1   from generate_series(1, 32769)i; -- 32769 is the smallest value that will error out, change it to 32768, everything is OK!
reindex index dl_bt_ix;
DROP TABLE delta_blocks;
```

With debuging the code, I found that if it is an AO table, the range of offset(ItemPointer->ip_posid) is [0,32767] in ItemPointer, but we set a flag to avoid the offset to be 0. so if the offset is 0, then the actual value in the offset is 32768 = 0x8000, the 16th bit was set to 1(c249ac7a36d).

When create or rebuild bitmap index, we will compute the TupleID by BM_IPTR_TO_INT, we need to replace the 32768 to 0, otherwise, the TupleID can not be used correctly. 

We need to replace the 32768 to 0 in a reasonable place, it need more investigate.

**Comment by gaos1** [comment]
The issue is triggered by one  gpexpand case and Jackey already has some clue.

**Comment by hlinnaka** [comment]
Ah, ok, looking at the github issue explained that. So the problem isn't with 32768 as such, the problem is that the bitmap index build code expects to see the tuple IDs in order. It gets confused when it sees offset number 32768 before offset number 1.

I guess this patch is an ok way to fix that, but I'd like to see some more sanity checks in that macro. Can we add an assertion or elog there, to check that the offset number is always in the range 1..32768. Because if we ever had offset number >= 32769, then things would go wrong. Likewise, a genuine 0 would be bad, since we're now mapping 32768 to 0.
