### ISSUE TITLE
can't create gin index on ao table

### ISSUE THREAD

**Issue by tianshisiyi** [greenplum-db/gpdb#7222]
### Greenplum version or build
VERSION = 'PostgreSQL 9.4.20 (Greenplum Database 6.0.0-alpha.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3), 64-bit'

### OS version and uname -a
Linux gpsrc-centos7.4 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
can create gin index success and used normally

### Actual behavior
create index failed

### reproduce
1，create demo table
 CREATE TABLE users_ao (
    first_name text,
    last_name text
) with (appendonly=true,compresstype=zlib,compresslevel=5,blocksize=32768);

insert into users_ao SELECT md5(random()::text), md5(random()::text) FROM
          (SELECT * FROM generate_series(1,1000000) AS id) AS x;

2，install pg_trgm extension
cd /gpsrc/gpdb/contrib/pg_trgm
make && make install
psql -c "create extension pg_trgm;"

3，create index using gin index
psql -c "CREATE INDEX users_ao_search_idx ON users_ao USING gin (first_name gin_trgm_ops, last_name gin_trgm_ops);"

gpadmin=# CREATE INDEX users_ao_search_idx ON users_ao USING gin (first_name gin_trgm_ops, last_name gin_trgm_ops);
ERROR:  Unexpected internal error (ginpostinglist.c:82)  (seg0 172.17.0.110:20000 pid=329265) (ginpostinglist.c:82)
DETAIL:  FailedAssertion("!(iptr->ip_posid < (1 << 11))", File: "ginpostinglist.c", Line: 82)
HINT:  Process 329265 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.

ugly for test change
---------------
src/backend/access/gin/ginpostinglist.c
from:
#define MaxHeapTuplesPerPageBits                11
to:
#define MaxHeapTuplesPerPageBits                16

src/include/storage/off.h
from:
/*#define OffsetNumberIsValid(offsetNumber) \
        ((bool) ((offsetNumber != InvalidOffsetNumber) && \
                         (offsetNumber <= MaxOffsetNumber))) */
to:
#define OffsetNumberIsValid(offsetNumber) \
        ((bool) ((offsetNumber != InvalidOffsetNumber) \
                         ))

It can create success and work on AO table normally,hope we can support gin index on ao table too.

**Comment by hlinnaka** [comment]
Yeah, we need to something like that.

The story behind this is that in PostgreSQL, the number of tuples you can have on a heap page is limited, so we took a shortcut in that encoding in GIN: the encoding reserves only 11 bits for the offsetnumber.

There were two reasons for this:

1. It saves some space. You need fewer bytes to represent the posting list, which is nice.

2. The old, pre-9.4 posting tree page format was an array of ItemPointers, with 6 bytes for each item. When we reserved only 11 bits for the offsetnumber, we could guarantee that the new encoding also used at most 6 bytes for each item, even in the worst case. That made upgrading simpler: we could always re-encode an old-format page to the new format in-place.

Unfortunately, that doesn't work for AO tables, because the TIDs in an AO table use the whole 16-bit offsetnumber range.

The good news is that we didn't support GIN indexes on GPDB 5 at all, so we don't need to worry about upgrading. We can easily just expand that to use the full 16 bits for offsetnumber. It takes a little bit more space, but we can live with it.

**Comment by tianshisiyi** [comment]
I understand, thanks very much @hlinnaka
