### ISSUE TITLE
Recovery fail on large cluster(512 segments) when heap checksum enabled.

### ISSUE THREAD

**Issue by Tao-Ma** [greenplum-db/gpdb#7481]
### Greenplum version or build
5.17 5.18
6x branch
master branch

### OS version and uname -a
centos 7.3

### Expected behavior
Recovery successful

### Actual behavior
Recovery failed on a large cluster and got the following error messages:

```
ValueError: filedescriptor out of range in select()
```

### Step to reproduce the behavior
1. create a 512 segments cluster(256 primaries and 256 mirrors).
2. shutdown all of mirrors
3. run gprecoverseg # will fail

### Code Analysis
python function validate_heap_checksum_consistency  in file clsRecoverSegment.py initialize HeapChecksum module and passes len(live_segments) as worker number. This value may be too large for gpsubprocess module.

The gpsubprocess uses select() and has a 1024 file descriptor limitation. It is better to add a reasonable max value when gp worker pool module initialized or change gpsubprocess to poll().

All of modules who initialize worker pool should follow command line argument max_parallel.

**Comment by d** [comment]
I see that this is also an issue if one deployment has 2048 segments, but around 256 of the mirrors failed and we need to run `gprecoverseg`, yes?

**Comment by Tao-Ma** [comment]
> I see that this is also an issue if one deployment has 2048 segments, but around 256 of the mirrors failed and we need to run `gprecoverseg`, yes?

yes, gprecoverseg has a call path that do not honor the default max_parallel parameter. It will use segment number as worker pool size, when the cluster large enough this issue will occur.

**Comment by ashwinstar** [comment]
@pobbatihari would be best to add this to the list of issues to fix. For sure GPDB can have a large number of segments and failures like these are not good to have in a product.

We should verify if the issue continues to exist for GPDB6 and forward. Usage of poll() (instead of select()) is definitely desired change here. We are doing a similar change in the Server backend code as well which posed similar limitations/failures refer PR https://github.com/greenplum-db/gpdb/pull/13094

**Comment by pobbatihari** [comment]
Sure @Ashwin ***@***.***> . We already have story for replacing select() with poll() (https://www.pivotaltracker.com/n/projects/2501397/stories/179004098).  I will check and  prioritize the story.

Regards,
Hari

From: Ashwin Agrawal ***@***.***>
Date: Tuesday, 1 March 2022 at 5:50 AM
To: greenplum-db/gpdb ***@***.***>
Cc: Hari krishna Maddileti ***@***.***>, Mention ***@***.***>
Subject: Re: [greenplum-db/gpdb] Recovery fail on large cluster(512 segments) when heap checksum enabled. (#7481)

@pobbatihari<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpobbatihari&data=04%7C01%7Chmaddileti%40vmware.com%7Caed82c05fc0e4b4e58fe08d9fb193cea%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C637816908092729080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=P63y67Pj0nKcKdQE6Gw1RrL%2FC%2F8uCHXGLd7QIEsIPwk%3D&reserved=0> would be best to add this to the list of issues to fix. For sure GPDB can have a large number of segments and failures like these are not good to have in a product.

We should verify if the issue continues to exist for GPDB6 and forward. Usage of poll() (instead of select()) is definitely desired change here. We are doing a similar change in the Server backend code as well which posed similar limitations/failures refer PR #13094<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgreenplum-db%2Fgpdb%2Fpull%2F13094&data=04%7C01%7Chmaddileti%40vmware.com%7Caed82c05fc0e4b4e58fe08d9fb193cea%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C637816908092729080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=bBMEcyRtdNX0%2FdNdEhVbZ%2FKzm6geEaM1EJglGtpRbEI%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgreenplum-db%2Fgpdb%2Fissues%2F7481%23issuecomment-1054843622&data=04%7C01%7Chmaddileti%40vmware.com%7Caed82c05fc0e4b4e58fe08d9fb193cea%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C637816908092729080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=Ynn9eOf5lsPke2fNbQp68Rs2YvEEYhgfdu%2BJ7OS4ynw%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALXREAJGBXBL4REYQXGI6N3U5QGLLANCNFSM4HGRRJHQ&data=04%7C01%7Chmaddileti%40vmware.com%7Caed82c05fc0e4b4e58fe08d9fb193cea%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C637816908092729080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=1dRMNQz1%2FPl2OhFCIinjyHRodePUWtxX3s20IfozXvM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Chmaddileti%40vmware.com%7Caed82c05fc0e4b4e58fe08d9fb193cea%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C637816908092729080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=VWVYmhcUbnFXAqFXYIrqpQZtIk8U7tPBZzdCL9mGxco%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Chmaddileti%40vmware.com%7Caed82c05fc0e4b4e58fe08d9fb193cea%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C637816908092885306%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=PG6D5V3HMO2YN5Hi4%2FZ23zE69A1x2XXHF0Zs2OaZJ%2BU%3D&reserved=0>.

**Comment by dpandhi-git** [comment]
With CM team- Fixed in 7X and 6X by limiting worker pool size to parallelization degree. Issue can be closed.
