### ISSUE TITLE
can  greenplum-db-6.0.0-beta.3/ support Mysql_fdw? if can, how to configure?

### ISSUE THREAD

**Issue by minchen0716** [greenplum-db/gpdb#7916]

**Comment by adam8157** [comment]
Could you please paste the result of these two commands?
`which pg_config`
`pg_config`

**Comment by Eulerizeit** [comment]
@dyozie this might be something we communicate in the documentation. Which MySQL FDW? 

Ideally Greenplum 6 should support most/all Postgres FDW however they will only connect through the master. I'm not entirely sure what we are testing so trying stuff out would be appreciated.

**Comment by adam8157** [comment]
I saw @minchen0716 's report at another place, she/he is using https://github.com/EnterpriseDB/mysql_fdw, and makefile's version check fails with `PostgreSQL 9.3, 9.4, 9.5, 9.6 10 or 11 is required to compile this extension`

**Comment by hlinnaka** [comment]
mysql_fdw's Makefile is looking at variable called MAJORVERSION to determine the PostgreSQL source version it's being compiled against. GPDB's makefiles apparently differ from upstream's, GPDB defines PG_MAJORVERSION and GP_MAJORVERSION instead.

 @danielgustafsson, you changed the variable name from MAJORVERSION to PG_MAJORVERSION in commit 0de5fc631364045f59ecb7a4b40dd453995f6423. That was perhaps a bad idea, mysql_fdw probably isn't the only extension out there that looks at MAJORVERSION. It's nice to have PG_MAJORVERSION and GP_MAJORVERSION for clarity, but I think we should also add back plain MAJORVERSION as an alias for PG_MAJORVERSION, for compatibility.

If you work around the version check in the Makefile, next you'll hit compilation errors in the `mysqlIterateForeignScan` function:
```
mysql_fdw.c: In function ‘mysqlIterateForeignScan’:
mysql_fdw.c:635:21: error: ‘TupleTableSlot’ {aka ‘struct TupleTableSlot’} has no member named ‘tts_values’; did you mean ‘tts_buffer’?
  memset (tupleSlot->tts_values, 0, sizeof(Datum) * tupleDescriptor->natts);
                     ^~~~~~~~~~
                     tts_buffer
mysql_fdw.c:636:19: error: ‘TupleTableSlot’ {aka ‘struct TupleTableSlot’} has no member named ‘tts_isnull’
  memset (tupleSlot->tts_isnull, true, sizeof(bool) * tupleDescriptor->natts);
                   ^~
mysql_fdw.c:650:13: error: ‘TupleTableSlot’ {aka ‘struct TupleTableSlot’} has no member named ‘tts_isnull’
    tupleSlot->tts_isnull[attnum] = festate->table->column[attid].is_null;
             ^~
mysql_fdw.c:652:16: error: ‘TupleTableSlot’ {aka ‘struct TupleTableSlot’} has no member named ‘tts_values’; did you mean ‘tts_buffer’?
     tupleSlot->tts_values[attnum] = mysql_convert_to_pg(pgtype, pgtypmod,
                ^~~~~~~~~~
                tts_buffer
```

That's caused by a difference between GPDB and PostgreSQL's version of TupleTableSlot struct. Fortunately, it's mostly cosmetic and easy to work around.

With the attached patch, I was able to make mysql_fdw compile against GPDB master. I didn't try run it, though, so I don't know if it will actually work or if there are more little differences between GPDB and postgreSQL to work around.

[mysql_fdw-gpdb-workarounds.patch.txt](https://github.com/greenplum-db/gpdb/files/3285350/mysql_fdw-gpdb-workarounds.patch.txt)

**Comment by danielgustafsson** [comment]
> @danielgustafsson, you changed the variable name from MAJORVERSION to PG_MAJORVERSION in commit [0de5fc6](https://github.com/greenplum-db/gpdb/commit/0de5fc631364045f59ecb7a4b40dd453995f6423). That was perhaps a bad idea, mysql_fdw probably isn't the only extension out there that looks at MAJORVERSION. It's nice to have PG_MAJORVERSION and GP_MAJORVERSION for clarity, but I think we should also add back plain MAJORVERSION as an alias for PG_MAJORVERSION, for compatibility.

Maybe. I'm not convinced that this won't come back and bite us in the derriere given the confusion we had around versioning around the time of that commit. I have however opened a PR to bring back these versions in #7928 since not having them clearly cause other issues.

**Comment by minchen0716** [comment]
> 
> 
> Could you please paste the result of these two commands?
> `which pg_config`
> `pg_config`

![图片](https://user-images.githubusercontent.com/25602932/59483227-010bb700-8e9f-11e9-942f-785aed450b1f.png)

**Comment by adam8157** [comment]
Unofficial mysql_fdw for Greenplum: https://github.com/adam8157/mysql_fdw_greenplum
