### ISSUE TITLE
copy freeze inconsistent with relfrozenxid

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7939]
### Greenplum version or build
latest master c30cd3ba99b46802e267f761aa616a1ba0879815
After using copy freeze, I was expect relfronzenxid will be equal to xmin, but it did not.
### Expected behavior
```
postgres=# select relfrozenxid  from pg_class where relname='aa';
 relfrozenxid
--------------
          795
(1 row)
```

### Actual behavior

```
postgres=# select relfrozenxid  from pg_class where relname='aa';
 relfrozenxid
--------------
          794
(1 row)
```

### Step to reproduce the behavior
```
cat  /Users/sbai/work/gpdb/data.tx
1,2
3,4
5,6
7,8
```
```
begin;
CREATE TABLE aa (a int, b int);
COPY aa FROM '/Users/sbai/work/gpdb/data.txt' DELIMITER ',' freeze;
commit;

postgres=# SELECT xmin,xmax,a,b FROM aa WHERE a = 1;
 xmin | xmax | a | b
------+------+---+---
  795 |    0 | 1 | 2
(1 row)

```

**Comment by dgkimura** [comment]
I think this is actually expected behavior as of Postgres 9.4.  Following commit changed the way tuples are marked as frozen:

```
commit 37484ad2aacef5ec794f4dd3d5cf814475180a78
Author: Robert Haas <rhaas@postgresql.org>
Date:   Sun Dec 22 15:49:09 2013 -0500

    Change the way we mark tuples as frozen.
```

Following hacker thread may be of interest:  https://www.postgresql.org/message-id/CAJguA1SHpL%3D1wSTBwKn4CJCtVQH8s1Bw8YVCg%3DYxK7bW1AcDyQ%40mail.gmail.com

Besides reviewing commit above, I used the reproduction and validated with pageinspect that `t_infomask` mask has `HEAP_XMIN_FROZEN` flags set.

```
PGOPTIONS='-c gp_session_role=utility' psql -p 25432 postgres -c "SELECT t_infomask FROM heap_page_items(get_raw_page('aa', 0));"
 t_infomask 
------------
       2816
       2816
(2 rows)
```

**Comment by dgkimura** [comment]
Closing for now as this is expected behavior.  Please feel free to re-open if you feel that assessment is incorrect.

**Comment by BaiShaoqi** [comment]
Thanks @dgkimura 
The issue i was reporting did not intend to complain relfrozenxid does not equal to 2. 
Looking at my updated description in issue, 
```
postgres=# SELECT xmin,xmax,a,b, gp_segment_id FROM gp_dist_random('aa') ;
 xmin | xmax | a | b | gp_segment_id
------+------+---+---+---------------
  771 |    0 | 3 | 4 |             0
  771 |    0 | 7 | 8 |             0
  773 |    0 | 1 | 2 |             1
  770 |    0 | 5 | 6 |             2
(4 rows)

postgres=# select relfrozenxid  from gp_dist_random('pg_class') where relname='aa';
 relfrozenxid
--------------
          773
          770
          771
(3 rows)
```
Notice the xmin equal to relfrozenxid in each segment, this is expected behavior of copy freeze. 
So the issue I registered is why relfrozenxid in master shows 799, it has no relationship to any of relfrozenxid in each segments. which is 773, 770, 771. Should or should not relfrozenxid in master be updated is why I opened the github issue.
```
postgres=# select relfrozenxid  from pg_class where relname='aa';
 relfrozenxid
--------------
          799
(1 row)
```

**Comment by dgkimura** [comment]
Ah, thanks for that calcification!  I had misread those details.  Shouldn't relfrozenxid be the local transaction id doing the COPY FREEZE?  It still seems to me like this is expected behavior.  If you do pg_xlogdump on the master xlog I would expect the COPY FREEZE transaction to be tx 799.

If I am still misunderstanding something, then please don't hesitate to reopen this issue.

**Comment by BaiShaoqi** [comment]
right now, it seems to me that relfrozenxid from pg_class in  master have nothing to do with relfrozenxid from pg_class in  each primary 
In favor of closing the issue.
