### ISSUE TITLE
NO KEY UPDATE is unexpected blocking KEY SHARE	

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7981]
### Greenplum version or build
latest master, 9fe24dae5d5e8bb25879fe57b609aa080b56605d
### Expected behavior
Command in session 2 should not be blocked
### Actual behavior
command in seesion 2 is blocking
### Step to reproduce the behavior
session 1
```
CREATE TABLE ee AS SELECT 1 AS e;
begin;
SELECT * FROM ee FOR NO KEY UPDATE;
```
session 2
```
test2=# SELECT * FROM ee FOR KEY SHARE;
 
```

**Comment by kainwen** [comment]
If GDD is disabled, this is expected behavior. See the thread: https://groups.google.com/a/greenplum.org/forum/#!searchin/gpdb-dev/zlv%7Csort:date/gpdb-dev/q8Nro2iBHRU/78lk-k1_AQAJ

See the commit https://github.com/greenplum-db/gpdb/commit/6ebce73331773d7cf71cfd109d1d7617453c738e 

I close this. Feel free to reopen it if you have more questions.
