### ISSUE TITLE
SHARE is unexpectedly blocking SHARE, KEY SHARE

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#7982]
### Greenplum version or build
lateste master,  9fe24da

set optimizer to off
### Expected behavior
all commands in session 2 should not be blocked 

### Actual behavior
all commands in session 2 is blocking

### Step to reproduce the behavior
session 1
```
CREATE TABLE bb AS SELECT 1 AS b;
SELECT * FROM bb FOR share;
```
session 2
the following commands in session is all blocked
```
SELECT * FROM bb FOR share;

SELECT * FROM bb FOR key share;
```

**Comment by kainwen** [comment]
If GDD is disabled, this is expected behavior. See the thread: https://groups.google.com/a/greenplum.org/forum/#!searchin/gpdb-dev/zlv%7Csort:date/gpdb-dev/q8Nro2iBHRU/78lk-k1_AQAJ

See the commit https://github.com/greenplum-db/gpdb/commit/6ebce73331773d7cf71cfd109d1d7617453c738e 

I close this. Feel free to reopen it if you have more questions.
