### ISSUE TITLE
Vacuum removes tuples that are still needed

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#801]
Per discussion on gpdb-dev, thread "Why does VACUUM use distributed transactions?":

```
On 27/05/16 03:48, Ashwin Agrawal wrote:
> 1] Why vacuum needs to use distributed transactions:
> Distributed transaction has two aspects *always uses distributed snapshot*
> and *may perform 2PC*. SELECT run as distributed transactions in GPDB that
> use distributed snapshots but skip 2PC.
>
>     - Vacuum must use distributed snapshot to decide oldest transaction
>     *globally* running in cluster to make sure tuple is DEAD before removing
>     the same. If it performs the check just based on local snapshot on a
>     segment, would cleanup a tuple visible to a distributed query yet to reach
>     the segment. (My understanding was vacuum behaves this way currently, but
>     surprisingly its using local oldestXmin only and hence its broken from
>     snapshot isolation perspective). Simple experiment to show how this
>     isolation gets broken due to vacuum
>
> T1: SELECT * FROM foo; (Hold this in gdb after acquiring snapshot on
> master, before dispatching to segment, so gets DXID = 10)
>
> T2: DELETE from foo;
>
> T3: VACUUM foo; (Cleans the tuples which should still be visible to T1,
> when it reaches this segment as it globally started before T2)
>
> T1: <misses to see the rows when it reaches segment>
>
> So, I feel we should fix vacuum to use Distributed Snapshot, still pending
> to think through what all issues this causes currently.

Oh, good point! So, GetOldestXmin() is wrong as it is. because even if 
there are no old transactions that can see <XID> as in-progress in a 
node anymore, there might be one still running in the master. Yeah, that 
ought to be fixed, independently of the rest of this discussion.
```

This can be reproduced fairly easily, without gdb, by using a serializable transaction. Attached is an "isolationtester" spec file that reproduces this.

**Comment by hlinnaka** [comment]
[heap-serializable-vacuum.spec.txt](https://github.com/greenplum-db/gpdb/files/290086/heap-serializable-vacuum.spec.txt)

**Comment by ashwinstar** [comment]
Yes we knew with serializable it would be very straightforwardly broken
given non- serializable repro, but since serializable is anyways bit shaky
decided to focus discussion towards regular case.

- AshwinA

On May 30, 2016, at 2:11 PM, Heikki Linnakangas <notifications@github.com>
wrote:

Per discussion on gpdb-dev, thread "Why does VACUUM use distributed
transactions?":

On 27/05/16 03:48, Ashwin Agrawal wrote:
> 1] Why vacuum needs to use distributed transactions:
> Distributed transaction has two aspects *always uses distributed snapshot*
> and *may perform 2PC*. SELECT run as distributed transactions in GPDB that
> use distributed snapshots but skip 2PC.
>
>     - Vacuum must use distributed snapshot to decide oldest transaction
>     *globally* running in cluster to make sure tuple is DEAD before removing
>     the same. If it performs the check just based on local snapshot on a
>     segment, would cleanup a tuple visible to a distributed query yet to reach
>     the segment. (My understanding was vacuum behaves this way currently, but
>     surprisingly its using local oldestXmin only and hence its broken from
>     snapshot isolation perspective). Simple experiment to show how this
>     isolation gets broken due to vacuum
>
> T1: SELECT * FROM foo; (Hold this in gdb after acquiring snapshot on
> master, before dispatching to segment, so gets DXID = 10)
>
> T2: DELETE from foo;
>
> T3: VACUUM foo; (Cleans the tuples which should still be visible to T1,
> when it reaches this segment as it globally started before T2)
>
> T1: <misses to see the rows when it reaches segment>
>
> So, I feel we should fix vacuum to use Distributed Snapshot, still pending
> to think through what all issues this causes currently.

Oh, good point! So, GetOldestXmin() is wrong as it is. because even if
there are no old transactions that can see <XID> as in-progress in a
node anymore, there might be one still running in the master. Yeah, that
ought to be fixed, independently of the rest of this discussion.

This can be reproduced fairly easily, without gdb, by using a serializable
transaction. Attached is an "isolationtester" spec file that reproduces
this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/greenplum-db/gpdb/issues/801>, or mute the thread
<https://github.com/notifications/unsubscribe/AK3mz2fiLYjJEtSfucIkj_FNxfDWpFqdks5qG1KVgaJpZM4IqCPI>
.

**Comment by ashwinstar** [comment]
Also, while reading code for something else found 8.3 merge brought in great feature of "Heap Page Pruning" with HOT (which is similar to lazy vacuum cleans up dead tuples on page while scanning page for selects / updates / inserts /...) so reduces the need for separate individual vacuum and also potentially avoids on-disk space growth for a relation.

This feature is kind-off in disabled state currently, though unintentionally (I think) due to incorrectly coded check in `heap_page_prune_opt()`. It calls `RelationNeedToFetchGpRelationNodeForXLog()` to check if relation has persistent information needed to write xlog records then go ahead to prune the page else bail-out. But this function doesn't return that it returns if for a relation need to add persistent table information to xlog records or not. Which means mostly persistent tables themselves and hence as as a result page pruning is current happening only for persistent tables as returns false for all other relations.

I wished to enable the page pruning for all the table by checking instead like below.
```
bool
RelationOkayToGenerateXLogRecordNow(Relation relation)
{
    if (InRecovery)
        return false;

    if (GpPersistent_SkipXLogInfo(relation->rd_id))
        return true;

    /*
     * Only for non-system table fetch the info if not present. Incase of
     * system table like pg_class if trying to fetch the informatiom here it
     * may lead to infinite recursion as for reading pg_class tuple will have
     * to read gp_relation_node tuple to get PT info for which need to read
     * back pg_class tuple, hence avoid the same.
     */
    if (relation->rd_id >= FirstNormalObjectId)
        RelationFetchGpRelationNodeForXLog(relation);

    if (relation->rd_segfile0_relationnodeinfo.isPresent &&
        !relation->rd_segfile0_relationnodeinfo.tidAllowedToBeZero)
    {
        return true;
    }

    return false;
}
```

With this tried and it works perfectly, gets enabled for all the tables and does the job, but suffers the same problem as VACUUM, mentioned in this issue. Hence not enabling the same and keeping it currently (now intentionally) only for persistent tables as they use frozen inserts and updates. When the issue is fixed for `HeapTupleSatisfiesVacuum()` for VACUUM, should also enable this feature for all the tables using above function check.
