### ISSUE TITLE
Deadlock during gprecoverseg with timeout and new failing segments

### ISSUE THREAD

**Issue by l-wang** [greenplum-db/gpdb#8032]
### Greenplum version or build
5X, 4.3X

### Context
The gprecoverseg utility currently recovers a failed segment mirror by removing it from gp_segment_configuration and the relevant persistence tables and then adding it back to gp_segment_congiuration and the relevant persistence tables. Either removing the mirror or adding the mirror are required to hold a `ExclusiveLock` on gp_segment_configuration, and also to dispatch the query command to remove/add persistence table entires on QEs. 

### Scenario:
1. The mirror of content 0 is down.
2. gprecoverseg starts to recover the mirror of content 0 (dbid5), and takes `ExclusiveLock` on gp_segment_configuration.
3. Any other segment (say the mirror of content 1, dbid6) magically goes down during the gprecoverseg
4. FTS detected that dbid6 is down and try to acquire the `RowExclusiveLock` on gp_segment_configuration in order to update it. <==== waiting for the lock
5. gprecoverseg encounters a timeout (network slowness) when polling results from QEs, and request a FTS probe. <==== blocked, because FTS cannot do anything at this point since it's still waiting for the lock at step 4

This is probably a rare enough edge case.

### Step to reproduce the behavior
```
begin;
-- gp_{add, remove}_segment_mirror() takes exclusive lock on gp_segment_configuration
lock gp_segment_configuration in exclusive mode;
-- kill any segment process so that FTS needs to update pg_segment_configuration
\! ps -ef | grep dbfast_mirror1 | grep -v grep | awk '{print $2}' | xargs kill -9
```

**Comment by asimrp** [comment]
In 6X and beyond, because persistent tables have been removed, `gprecoverseg` cannot cause a deadlock as it doesn't dispatch anything to segments.  In fact, no function in `segadmin.c` that holds `AccessExclusiveLock` on `gp_segment_configuration` performs dispatch in 6X and beyond.  So this issue doesn't apply to versions newer than 5X.

Regardless, I still feel we should consider acquiring only RowExclusiveLock in the functions in `segadmin.c` that are currently acquiring `AccessExclusiveLock` or `ExclusiveLock` because such a strong lock is not needed for insert/update/delete.  In order to synchronize multiple `gprecoverseg` instances, a .pid file may be used.  Similar trick is used by `gpexpand` in 6X.

**Comment by ivannovick** [comment]
no plan to change on older versions
