### ISSUE TITLE
Can not break through the memory limit on  array_agg

### ISSUE THREAD

**Issue by zeromax007** [greenplum-db/gpdb#833]
Can not break through the memory limit on  array_agg

select array_agg(ID) from (select ID from IDLIST limit 100000000) t;
NOTICE:  invalid memory alloc request size 1073741824 (context 'accumArrayResult') (mcxt.c:1257) (mcxt.c:477)

**Comment by kuruv** [comment]
I am also getting similar error. It is not related to array_agg but with how gp_vmem_protect_limit and statement_mem are handled. I have set gp_vmem_protect_limit to 17066. If my statement_mem is below 8193MB then I do not get this error. I am using GP 4.3.8.2 build 1.

Error when ranking -
ERROR: invalid memory alloc request size 1610612736 (context 'TupleSort') (mcxt.c:1257) (mcxt.c:477)  (seg11 slice3 app2056:40003 pid=36139) (cdbdisp.c:1326)

Error when creating random forest -
ERROR:  plpy.SPIError: invalid memory alloc request size 1073,741,824 (context 'accumArrayResult') (mcxt.c:1257) (plpython.c:4648)

**Comment by hlinnaka** [comment]
@kuruv, the first one of your issues actually looks different. I suspect the sorting code tries to allocate an internal array for performing the sort that's larger than 1 GB, and hits the limit in the usual palloc() routine used for allocating memory. The upstream sorting code has an explicit check for that, and clamps the size of the array to avoid hitting the limit (switching to an external sort earlier than would otherwise be needed, but at least it won't fail). Do you get the same error if you set gp_enable_mk_sort=off?

The second one, from accumArrayResult(), looks like the same array_agg() limitation.

**Comment by foyzur** [comment]
Thanks @hlinnaka for quickly chiming in with valuable comments. I absolutely agree with all your prognosis. I also looked into the tuplesort.c and I see that we have check to make sure we don't cross MaxAllocSize. However, in tuplesort_mk.c we don't have any such check. Therefore, @kuruv should see the query working with mksort disabled. If not, could someone attach all the repro and we will take a look.

Thanks,

Query Execution Team.

**Comment by vraghavan78** [comment]
@kuruv please let me know if @hlinnaka's suggestion. If not, please provide us the repro so we can take a look.

**Comment by kuruv** [comment]
@hlinnaka, @foyzur , @vraghavan78, 

I had not been receiving the notifications of posts for some reason but I got notification about the closure. Thanks for looking at this

I have run the code with gp_enable_mk_sort=off

It has been running for more than an hour and has not thrown the error yet whereas when I ran it with the default setting (gp_enable_mk_sort=on) it threw the error in 10 min.

**Comment by kuruv** [comment]
@hlinnaka, @foyzur , @vraghavan78,

The code successfully ran with gp_enable_mk_sort=off

**Comment by hlinnaka** [comment]
@vraghavan78, did you fix the bug in tuplesort_mk.c? I didn't see a commit.
