### ISSUE TITLE
HashAgg with UDA goes out of memory (VMEM set to 40GB)

### ISSUE THREAD

**Issue by kaknikhil** [greenplum-db/gpdb#8764]
### Greenplum version or build
gpdb 5/6/master 3 primary segments 

### OS version
MacOS High Sierra
32GB memory

### Expected behavior
Query should run successfully and not hit vmem limit of 40GB. 

### Actual behavior
ERROR:  Canceling query because of high VMEM usage. Used: 36008MB, available 3992MB, red zone: 36000MB (runaway_cleaner.c:189)  (seg0 slice2 127.0.0.1:25432 pid=61411) (cdbdisp.c:254)

Note: The query works if the plan uses groupagg by `set enable_hashagg='false';`

### Step to reproduce the behavior
Load data
```
1. cd /tmp
1. wget https://github.com/apache/madlib-site/raw/asf-site/data/mnist_train.sql.gz
1. gunzip mnist_train.sql.gz
1. psql postgres -f mnist_train.sql
postgres=# select count(*) from mnist_train;
 count
-------
 60000
(1 row)

postgres=# select array_dims(x) from mnist_train limit 5;
 array_dims
------------
 [1:784]
 [1:784]
 [1:784]
 [1:784]
 [1:784]
(5 rows)
```
Create the aggreate
```
postgres=# create aggregate agg_array_concat(REAL[])(
STYPE=REAL[],
PREFUNC=array_cat, 
SFUNC=array_cat);
```
Run query
```
set optimizer='off'; -- turn orca off to eliminate orca related failures
postgres=# CREATE TABLE foo as SELECT agg_array_concat(ARRAY[x]) , (id%3.0)::smallint AS buffer_id FROM mnist_train GROUP BY buffer_id;
ERROR:  Canceling query because of high VMEM usage. Used: 36008MB, available 3992MB, red zone: 36000MB (runaway_cleaner.c:189)  (seg0 slice2 127.0.0.1:25432 pid=61411) (cdbdisp.c:254)

postgres=# explain CREATE TABLE foo as SELECT agg_array_concat(ARRAY[x]) , (id%3.0)::smallint AS buffer_id FROM mnist_train GROUP BY buffer_id;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 'buffer_id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
                                             QUERY PLAN
----------------------------------------------------------------------------------------------------
 HashAggregate  (cost=11401.90..12152.02 rows=20004 width=34)
   Group By: ((mnist_train.id::numeric % 3.0)::smallint)
   ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=7351.22..10501.75 rows=20004 width=34)
         Hash Key: ((mnist_train.id::numeric % 3.0)::smallint)
         ->  HashAggregate  (cost=7351.22..9301.55 rows=20004 width=34)
               Group By: (mnist_train.id::numeric % 3.0)::smallint
               ->  Seq Scan on mnist_train  (cost=0.00..7051.18 rows=20004 width=1028)
 Settings:  optimizer=off
 Optimizer status: legacy query optimizer
(9 rows)


Note: The query works if the plan uses groupagg i.e. `set enable_hashagg='false';`
```

Metadata
```
gpconfig -s gp_vmem_protect_limit
Values on all segments are consistent
GUC          : gp_vmem_protect_limit
Master  value: 40000
Segment value: 40000

postgres=# select hostname,address,mode,status from gp_segment_configuration where role='p';
 hostname | address | mode | status
----------+---------+------+--------
 nkakmac  | nkakmac | s    | u
 nkakmac  | nkakmac | s    | u
 nkakmac  | nkakmac | s    | u
 nkakmac  | nkakmac | s    | u
```

Stack trace from debugging the query w/ @bhuvnesh2703 (Note that vmem was set to 8GB in this case)

<img width="706" alt="Screen Shot 2019-10-03 at 4 51 03 PM" src="https://user-images.githubusercontent.com/11729207/66171877-996ca980-e5fe-11e9-98ca-a47e303aa0c6.png">

**Comment by soumyadeep2007** [comment]
We investigated this with @kaknikhil, @d  and @melanieplageman:
Since the transition function used is plain sql, the input arrays are immutable. This means that whenever we advance the aggregate by calling the transition function, we have to create a new array that can fit both the input arrays. If you make the same UDA in plain Postgres with `array_cat` as the transition function, you'll get similar performance behavior (there is no runaway killer to help you out here, however). In GPDB the behavior is worse because of a few differences. GPDB doesn't free the old transition value because of the `mpool` (which is an optimization for most workloads). Also, GPDB attempts to reuse the memory from the previous transition value allocation, and, if it doesn't fit, it allocates a much larger "realloc" chunk of memory to attempt to make it such that the memory could be reused next time with no malloc. This optimization falls over for this particular use case, however, because the new transition value will almost never fit in the space allocated last time, so we just 2x our already over-sized growth. Changing either of these two would likely be a regression for most workloads. In this case, the fix is to write the transition function in C.
