### ISSUE TITLE
The previous session was reset because its gang was disconnected 

### ISSUE THREAD

**Issue by kpmanojpg** [greenplum-db/gpdb#878]
Hi Team ,
Noticed  following error on my greenplum log 

seg-1,,dx66682,x10922773,sx1,"LOG","00000","The previous session was reset because its gang was disconnected (session id = 11963). The new session id = 12119",,,,,,,0,,"cdbgang.c",2712,

Restart also not helped here. Any idea what the reason for this ?

**Comment by asimrp** [comment]
Can you please provide more clues by tracing the distributed transaction ID `dx66682` in the same master log file?

**Comment by asimrp** [comment]
Hi @kpmanojpg can you please provide the requested details?

**Comment by deepesh1081** [comment]
Closing this due to lack of information. @kpmanojpg feel free to reopen this

**Comment by dragon-hl** [comment]
I also encountered the same problem. The detailed log information is as follows：

failed to acquire resources on one or more segments	"FATAL:  too many sessions
DETAIL:  Could not acquire resources for additional sessions.
HINT:  Disconnect some sessions and try again.
 (seg4 10.2.5.136:6000)"
An exception was encountered during the execution of statement: SET extra_float_digits = 3	
The previous session was reset because its gang was disconnected (session id = 34599791). The new session id = 34599830	
The error code for this error is 58M01 and appears frequently in master logs

The error code for this error is 58M01 and appears frequently in master logs.
