### ISSUE TITLE
RHEL8 rpm build

### ISSUE THREAD

**Issue by diarworld** [greenplum-db/gpdb#8821]
Red Hat Enterprise Linux 8 was released on 2019-05-07, centos 8 build was released on 2019-09-24: https://wiki.centos.org/About/Building_8
Do you plan to add rhel8 support and create rhel8 rpm for greenplum? As I tested gpdb-6.0.1 builds successfully and works correctly on centos8-1905. Could you add rhel8 build to your concourse pipeline? Thx.

**Comment by baotingfang** [comment]
GP Releng team have made a roadmap for the platform supports. We focus on the sles 12 and Oracle Linux 7 recently. Maybe @kmacoskey  can provide more information about the new platform supports.

**Comment by kmacoskey** [comment]
Hello @diarworld ! Support for Redhat/CentOS 8 is on the Roadmap but it's not at the top because of how recently it was released.

We have found that most users are using older platform versions, which is why Greenplum 6 still supports Redhat/CentOS 6, and that those users don't typically upgrade platform major versions quickly or tend to use the most recent. More data always helps though - if you yourself are a user or you know of users that have a need and desire for earlier support of Redhat 8, then please give more information and that will help shape the roadmap.

There are two sides to this topic though. Adding jobs in pipeline that build and test on rhel8 is something driven by the GP Server team's roadmap. @Eulerizeit and @gaos1 can help with this. Building and distributing RPMs for GP on rhel8 is what my response above is focused on.

**Comment by lij55** [comment]
please wait for 6.20.
