### ISSUE TITLE
Why does gp-6. X not need to create a filespace before creating a tablespace? 

### ISSUE THREAD

**Issue by byanjie** [greenplum-db/gpdb#8875]
In gpdb-5. X version, when creating the database tablespace, you need to specify the parameter filespace, while in 6. X, you only need location. For example, in 5. X version, you need to create the system filespace through the gpfilespace command first.
（在gpdb-5.x 版本的时候，创建数据库tablespace的时候还需要指定参数filespace,而6.x 的时候只需要location,比如说5.x版本是先通过gpfilespace 命令来创建系统文件空间。。。）

**Comment by kainwen** [comment]
> In gpdb-5. X version, when creating the database tablespace, you need to specify the parameter filespace, while in 6. X, you only need location. For example, in 5. X version, you need to create the system filespace through the gpfilespace command first.
> （在gpdb-5.x 版本的时候，创建数据库tablespace的时候还需要指定参数filespace,而6.x 的时候只需要location,比如说5.x版本是先通过gpfilespace 命令来创建系统文件空间。。。）

Because gpdb6 has done much work on tablespace. Now it is easier to deal with tablespace usage.

Please see the doc here:  https://gpdb.docs.pivotal.io/6-0/admin_guide/ddl/ddl-tablespace.html

I close this issue. If you have any further problems, please open another issue or ask in gpdb user mailing list, see more info here: https://greenplum.org/mailing-lists/
