### ISSUE TITLE
gpdb6.1 compile error on centos6

### ISSUE THREAD

**Issue by shendayu** [greenplum-db/gpdb#8962]
### autoconf options used ( config.status --config )

CFLAGS="-O0 -g3 -ggdb3" ./configure --with-perl --with-python --with-libxml         --enable-cassert --disable-orca --disable-gpcloud  --without-zstd  --disable-gpfdist --prefix=/home/work/gpdb/gpdb/build
&& make

### 
timestamp.c: In function 'interval_div_internal':
timestamp.c:2919: error: incompatible types when initializing type 'TimeOffset' using type 'IntervalOffset'
timestamp.c:2920: error: incompatible types when initializing type 'TimeOffset' using type 'IntervalOffset'

**Comment by gkokolatos** [comment]
Thank you for the issue!

Before diving into it, I will strongly recommend trying in Centos 7 or higher. Centos 6 has been EOLed since May 2017 and maintenance updates will be EOLed at end of this month. 

 Greenplum6 is rigorously tested on Centos7 among other operating systems. If you find the issue persisting on Centos7, please be so kind as to open a new issue.

**Comment by kainwen** [comment]
Close this since no response for a long time.
