### ISSUE TITLE
shared lock make table invisible to other session.

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#9117]
### Greenplum version or build
master 32cc07cc77a07be30da0ea9d2a6a2d3a498339f9
### Expected behavior
the second session should show
```
select * from t1 where c1=1 for update nowait;
ERROR:  could not obtain lock on row in relation "t1"
```

### Step to reproduce the behavior
first session;
```
create table t1 as select generate_series(1, 10) as c1;
begin;
select c1 from t1 where c1=1 for share;
```
second session;
```
select * from t1 where c1=1 for update nowait;
ERROR:  relation "t1" does not exist
LINE 1: select * from t1 where c1=1 for update nowait;
```

**Comment by kainwen** [comment]
I believe this issue is duplicated to this https://github.com/greenplum-db/gpdb/issues/8539

Greenplum is MPP database. We cannot easily lock tuples on segments(global deadlock or tuples might be motioned here).

select statement with locking clause has differente semantics in greenplum from postgres.

We have already created a story tracking this bug. All we should do is to design the correct
behaviour for greenplum to handle select statement with locking clause.

**Comment by kainwen** [comment]
If this really duplicates #8539, then let's close this one. @BaiShaoqi

**Comment by BaiShaoqi** [comment]
Yes, you are correct, sorry for the duplicate, I forgot that issue when I was playing some psql script.
