### ISSUE TITLE
vacuum on segment does not change PD_ALL_VISIBLE in heap and all_visible in visibility map

### ISSUE THREAD

**Issue by BaiShaoqi** [greenplum-db/gpdb#9139]
### Greenplum version or build
master 32cc07cc77a07be30da0ea9d2a6a2d3a498339f9

### Expected behavior
on segment 1, after vacuum t1, the PD_ALL_VISIBLE in t1's heap and all_visible in t1's visibility map should rebuilt, so the PD_ALL_VISIBLE in t1's heap and  all_visible in t1's visibility map should be true
### Actual behavior
on segment 1, after vacuum t1, the PD_ALL_VISIBLE in t1's heap and  all_visible in t1's visibility map is still showing false
### Step to reproduce the behavior
install extension pg_visibility
```
cd contrib/pg_visibility/
make install
```

on master
```
psql -d postgres 

create extension pg_visibility;

create table t1 as select generate_series(1,1000) as c1;
```

on segment 1
```
PGOPTIONS='-c gp_session_role=utility' psql -p 7002 -d postgres

# before vacuum, the all_visible and pd_all_visible is false, this is expected.
select * from pg_visibility('t1'::regclass);
 blkno | all_visible | all_frozen | pd_all_visible
-------+-------------+------------+----------------
     0 | f           | f          | f
(1 row)

vacuum t1;

# after vacuum, the all_visible and pd_all_visible should be true since they are forcebly rebuilt by vacuum.
select * from pg_visibility('t1'::regclass);
 blkno | all_visible | all_frozen | pd_all_visible
-------+-------------+------------+----------------
     0 | f           | f          | f
(1 row)
```

**Comment by pivotal-ning-yu** [comment]
I can get the same result with latest master commit d74aa39fc1254775791a6f598a1ff00117e18086.

The function `GetOldestXmin()` is used to get the oldest xmin:

```C
TransactionId
GetOldestXmin(Relation rel, bool ignoreVacuum)
{
    TransactionId result;

    result = GetLocalOldestXmin(rel, ignoreVacuum);

    /*
     * In QD node, all distributed transactions have an entry in the proc array,
     * so we're done.
     *
     * During binary upgrade and in in maintenance mode, we don't have
     * distributed transactions, so we're done there too. This ensures correct
     * operation of VACUUM FREEZE during pg_upgrade and maintenance mode.
     *
     * In bootstrap or standalone backend case as well ignore the distributed
     * logs using IsPostmasterEnvironment. Otherwise, during initdb can't
     * vacuum freeze template0.
     */
    if (IsPostmasterEnvironment && !IS_QUERY_DISPATCHER() &&
        !IsBinaryUpgrade && !gp_maintenance_mode)
        result = DistributedLog_GetOldestXmin(result);

    return result;
}
```

Suppose the tuples are inserted with xmin=555, the utility-mode connection's xid is 556, let's see what would happen when vacuum in utility mode.  The `GetLocalOldestXmin()` returns 556, if `GetOldestXmin()` also returns 556 then the table's tuples will satisfy the all-visible check.  However the `if` branch is executed so the result of `DistributedLog_GetOldestXmin()` is returned, which is 555, so the tuples can not be marked as all-visible.

Maybe the current behavior is correct because in utility mode we don't know the status of distributed transactions, so do not be aggressive.

However this does is confusing, for example, if we change the reproducer like below:

```sql
create extension pg_visibility;
create table t1 as select generate_series(1,1000) as c1;

-- commit an extra irrelative xact
create table t2 (c1 int);
```

Then after the utility-mode vacuum the `PD_ALL_VISIBLE` will be set:
```sql
0U: vacuum t1;
0U: select * from pg_visibility('t1'::regclass);
 blkno | all_visible | all_frozen | pd_all_visible
-------+-------------+------------+----------------
     0 | t           | t          | t
(1 row)
```

**Comment by asimrp** [comment]
Oh, the `vacuum` in the original repro is executed in utility mode!  I didn't notice that.  As @pivotal-ning-yu mentioned, vacuum in utility mode considers distributed snapshot for visibility checks, and that's correct behavior.

Also, the change in behavior due to an additional unrelated distributed transaction before `vacuum` is also expected.  See `DistributedLog_AdvanceOldestXmin()`.  The second unrelated distributed transaction causes the distributed xmin to advance and then the utility mode `vacuum` can determine that CTAS transaction is no longer seen as running in the cluster.  In other words, `vacuum` would see the unrelated transaction as the oldest XMIN returned by `DistributedLog_GetOldestXmin`.

I think this can be closed as expected behavior.

**Comment by BaiShaoqi** [comment]
I originally doing the experiment was trying to see if there will be any bad behavior if doing vacuum in one of the segment, but then I stopped, only found one thing that is PD_ALL_VISIBLE and all_visible in visibility map are not like postgres.
Thanks for your comfirmation, close it as it is expected behavior.
