### ISSUE TITLE
Locks on ao table impacts the effect of vacuum on this ao table

### ISSUE THREAD

**Issue by jiangj20** [greenplum-db/gpdb#9421]
### Greenplum version or build
GPDB 4 and 5
### Expected behavior
Vacuum on ao table should not be impacted by locks

### Actual behavior
Vacuum on ao table seems not working when there is lock on this ao table.

### Step to reproduce the behavior
Please see the attached file as there is format issue when pasting here.

[repro.docx](https://github.com/greenplum-db/gpdb/files/4058614/repro.docx)

**Comment by asimrp** [comment]
Vacuum on append-optimized tables is performed by inspecting one segment file at a time.  If the segment file has sufficient number of tuples dead tuples, a new segment file is created and all live times from the old segment file are moved to the new segment file.  This is called compaction.

If the append-optimized table is accessed by a concurrent transaction, lazy vacuum cannot remove the old segment file from the system because a concurrent transaction cannot see the newly created segment file (due to MVCC rules for transaction isolation).  In this case, lazy vacuum skips the drop and marks the old segment file indicating that it needs to be dropped by a subsequent vacuum operation.

Size of an append-optimized table may therefore increase after lazy vacuum due to concurrent transactions: <old segment file> + <new compacted segment file>.  This is expected behavior. 
If reduction in size is desired, please use `vacuum full` or run lazy vacuum only after the previous transaction that was running concurrently with the previous lazy vacuum, is finished.

**Comment by jiangj20** [comment]
Thanks @asimrp for the detailed explanation 👍
