### ISSUE TITLE
Error reading from AOCS table in serializable xact when a column is added concurrently

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#9599]
### Greenplum version or build
6X_STABLE (didn't check others)

### Step to reproduce the behavior

This isolation2 test, modified from the existing `add_column_after_vacuum_skip_drop_column` test, reproduces the issue:

```
-- @Description Ensures that an ALTER TABLE ADD COLUMN will drop segfiles in
--              AOSEG_STATE_AWAITING_DROP state left over by a previous vacuum
--
CREATE TABLE aoco_add_column_after_vacuum_skip_drop (a INT, b INT) WITH (appendonly=true, orientation=column);
INSERT INTO aoco_add_column_after_vacuum_skip_drop SELECT i as a, i as b FROM generate_series(1, 10) AS i;

DELETE FROM aoco_add_column_after_vacuum_skip_drop;

-- We should see all aocssegs in state 1
0U: SELECT segno, column_num, state FROM gp_toolkit.__gp_aocsseg('aoco_add_column_after_vacuum_skip_drop');

3: begin isolation level serializable;
3: select 123;

-- VACUUM while another session holds lock
1: BEGIN;
1: SELECT COUNT(*) FROM aoco_add_column_after_vacuum_skip_drop;
2: VACUUM aoco_add_column_after_vacuum_skip_drop;
1: END;

-- We should see an aocsseg in state 2 (AOSEG_STATE_AWAITING_DROP)
0U: SELECT segno, column_num, state FROM gp_toolkit.__gp_aocsseg('aoco_add_column_after_vacuum_skip_drop');

-- The AWAITING_DROP aocssegs should remain after the ADD COLUMN.
1: ALTER TABLE aoco_add_column_after_vacuum_skip_drop ADD COLUMN c INT DEFAULT 0;
0U: SELECT segno, column_num, state FROM gp_toolkit.__gp_aocsseg('aoco_add_column_after_vacuum_skip_drop');

3: select * from aoco_add_column_after_vacuum_skip_drop;
```

Output:
```
...
3: select * from aoco_add_column_after_vacuum_skip_drop;
ERROR:  Index 2 exceed size of vpinfo array size 2 (aocssegfiles.h:115)  (seg0 slice1 127.0.0.1:40000 pid=14930) (aocssegfiles.h:115)
```

**Comment by asimrp** [comment]
@wraymo @bbbearxyz another issue related to AO vacuum.  FYI, @kainwen

**Comment by interma** [comment]
This issue can be reproduced in latest 6X_STABLE:  PostgreSQL 9.4.24 (Greenplum Database 6.17.2+dev.50.g0de750e8c1 build dev)

with a shorter test case:
```
CREATE TABLE aoco_add_column_after_vacuum_skip_drop (a INT, b INT) WITH (appendonly=true, orientation=column);
INSERT INTO aoco_add_column_after_vacuum_skip_drop SELECT i as a, i as b FROM generate_series(1, 10) AS i;

DELETE FROM aoco_add_column_after_vacuum_skip_drop;

2: begin isolation level serializable;
2: select 123;

1: BEGIN;
1: SELECT COUNT(*) FROM aoco_add_column_after_vacuum_skip_drop;
1: END;
1: ALTER TABLE aoco_add_column_after_vacuum_skip_drop ADD COLUMN c INT DEFAULT 0;

2: select * from aoco_add_column_after_vacuum_skip_drop;
-- Error here: exceed size of vpinfo array size
```

I am going to fix it.

**Comment by interma** [comment]
Found the root cause, please see the following analysis.

### Short explanation 
1. No.1 session: it changed a table schema
1. No.2 session: though my transaction_isolation is RR or SERI, but the change of schema is still awared by me.

So column number mismatch: vpinfo obj and relation obj

### Details
this example (using a heap table) shows "the change of schema is awared by another session/txn"
```
1: 
create table test (i int, j char);
insert into test values (1, 'a'),(2, 'b');

2: 
-- start another txn (if using serializable, result is the same)
begin isolation level REPEATABLE READ; select 123; 

1: 
-- add/drop columns
ALTER TABLE test add COLUMN k int default 0;
ALTER TABLE test add COLUMN h int default 100;
ALTER TABLE test drop COLUMN j;

2: 
-- check table schema, it's the same as txn start, nice
demo=# \d test 
        Table "public.test"
 Column |     Type     | Modifiers
--------+--------------+-----------
 i      | integer      |
 j      | character(1) |
Distributed by: (i)

-- but the output column is changed and no output rows
demo=# select * from test;
 i | k | h
---+---+---
(0 rows)

demo=# commit;
COMMIT

-- get results after the txn finished
demo=# select * from test;
 i | k |  h
---+---+-----
 2 | 0 | 100
 1 | 0 | 100
(2 rows)

```
So imagine under the AOCS scene:
get 3 columns from scan desc obj, but only 2 columns in vpinfo, so it reported "exceed size of vpinfo array size" error.

Note: the above example behaves the same in pg9.6.

### Related code
in aocs_beginscan_internal()
https://github.com/greenplum-db/gpdb/blob/9b1c99efe4a57eaab938503301b69f44a870440a/src/backend/access/aocs/aocsam.c#L443

seginfo (contains vpinfo) array is good, column number is 2, but relation->rd_att.nattr is 3, not match. 
The relation obj is constructed from heap_open() and get catalog (column info) via the NonHistoricCatalogSnapshot, looks it gets the latest data.

### How to fix
three ideas:
* no fix: just remind user retry the query, it may success in the next txn
* just using the vpinfo column as the output (ignore the related field of relation obj), but need to read more code to confirm no side effects
* using a 'dict style' vpinfo (now use array), only chooses the intersection as output

That's my ideas, feel free to comment, thanks.

**Comment by interma** [comment]
After googled some info (thanks Haolin's help), I think "no fix" may be an accepted solution, reason:
Refer the postgres doc: 
> Some DDL commands, currently only TRUNCATE and the table-rewriting forms of ALTER TABLE, are not MVCC-safe. This means that after the truncation or rewrite commits, the table will appear empty to concurrent transactions, if they are using a snapshot taken before the DDL command committed. This will only be an issue for a transaction that did not access the table in question before the DDL command started — any transaction that has done so would hold at least an ACCESS SHARE table lock, which would block the DDL command until that transaction completes. So these commands will not cause any apparent inconsistency in the table contents for successive queries on the target table, but they could cause visible inconsistency between the contents of the target table and other tables in the database.
https://www.postgresql.org/docs/9.4/mvcc-caveats.html

So the table schema may be inconsistency between txns, when it happens at AOCS table, wo can just remind user: there is a concurrent txn modified the table schema, you should try again in a new txn.

**Comment by interma** [comment]
After tested, the issue also exists on master.

**Comment by interma** [comment]
yes, just remind user when it happens again.
