### ISSUE TITLE
Hash join is slow in some cases

### ISSUE THREAD

**Issue by pengzhout** [greenplum-db/gpdb#9687]
### Greenplum version or build
Latest master
### Step to reproduce the behavior
create table t1 (c1 int, c2 int, c3 int);create table t2 (c1 int, c2 int, c3 int);
insert into t2 select i, 1, 1 from generate_series(1, 11000000) i;
insert into t1 select i, 1, 1 from generate_series(1, 1000) i;
analyze t2;analyze t1;set enable_nestloop to off;set allow_system_table_mods to true;
update pg_class set reltuples = 10000000 where relname='t1';
select t1.* from t1, t2 where t1.c1 = t2.c2 limit 1;

The last query takes 7000ms on my laptop, but PG takes only 17ms. It should relate to the 
`update pg_class set reltuples = 10000000 where relname='t1';`, without it, GPDB is also fast. It might be an issue of hash spill or hash join internally.

**Comment by kainwen** [comment]
In my local laptop,
pg generate a nest loop plan, this is a good plan taking `limit 1` into consideration? 

GPDB uses hash join and create hash on t1, which might lead to huge start up cost?

**Comment by pengzhout** [comment]
You can set enable_nestloop to off, pg is still very fast in hash join case.

**Comment by gaos1** [comment]
it is indeed caused by hash join with file spill. with default 128M statement_mem, it needs 5600ms on my laptop. when I set statement_mem to 256MB, it can finish with 260ms without file spill.  when I analyze t1 and have proper reltuples in pg_class for it, I get 110ms with a plan that t1 is broadcasted.  
please reopen it if you have more thoughts.
