### ISSUE TITLE
windows function cause master process received signal SIGSEGV

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#9809]
### Greenplum version or build
5.23.0

### OS version and uname -a
CentOS Linux release 7.2

### Step to reproduce the behavior
3.sql run ok
4.sql will cause master process received signal SIGSEGV
The difference between 3.sql and 4.sql are only one column.
Attached is the sql for create and query.
[sql.zip](https://github.com/greenplum-db/gpdb/files/4374031/sql.zip)

**Comment by kainwen** [comment]
Hi, this is a known issue. Greenplum 5 has its own logic to implement `PERCENTILE_CONT`. This is historical reason at that time, postgres did not support this kind of agg.

Greenplum 6 and master does not have the issue because the kernel version is updated and we have the agg function PERCENTILE_CONT.

In gpdb5, you can work around this issue by setting a GUC:

```
gpconfig -c gp_idf_deduplicate -v 'force';
gpstop -rai
```

I have tested on my local env, just setting the above GUC, everything is OK.

**Comment by lambgong** [comment]
Thanks for the reply, it works fine for me.
BTW，gp_idf_deduplicate  param only need gpstop -u
