### ISSUE TITLE
Unexpected internal error with UPDATE WHERE CURRENT OF

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#9838]
### Greenplum version or build
master, works on 6X_STABLE

### Step to reproduce the behavior
```
CREATE TABLE tidscan(id integer);
INSERT INTO tidscan (id) VALUES (1), (2), (3);
BEGIN;
DECLARE c CURSOR FOR SELECT ctid, * FROM tidscan LIMIT 10;
FETCH NEXT FROM c;
UPDATE tidscan SET id = -id WHERE CURRENT OF c;
```
Produces error:
```
postgres=# UPDATE tidscan SET id = -id WHERE CURRENT OF c;
psql: ERROR:  Unexpected internal error (execCurrent.c:435)
```

**Comment by haolinw** [comment]
Based on 6X_STABLE behavior, the expected message should be 'cursor "c" is not a simply updatable scan of table "tidscan"'.
The reason of reporting "Unexpected internal error" on master branch is because the commit "updatable evaluation for partition table" 20ae004702818a375f101c809e701e589f9b68e5 limited the simply updatable check to partitioned table and temporary table, the ordinary table skipped the check and proceeded then failed at the empty tuple slot check.

More info, as I learned that PG12 removed tuple slot allocation from LIMIT plan node, intended to save some cost and separate the determination of the result type from the slot creation, (refer to https://github.com/postgres/postgres/commit/1ef6bd2954c4ec63ff8a2c9c4ebc38251d7ef5c5). 
This causes the empty tuple slot check failed in above scenario.

To be consistent with 6X_STABLE, a straightforward fix should be applying "simply-updatable" check to ordinary tables as well.

If necessary, I would try to add the slot creation back to LIMIT node to see whether it could execute the update statement successfully.

**Comment by haolinw** [comment]
Fixed by https://github.com/greenplum-db/gpdb/pull/12618
