### ISSUE TITLE
under different schema create same table get problem

### ISSUE THREAD

**Issue by GuoLiuFang** [greenplum-db/gpdb#988]
this is before create external table "ework_production.request_histories_external"
![Markdown](http://i2.piimg.com/1949/6f1132925eda30c1s.jpg)
this is my create table command
![Markdown](http://i4.piimg.com/1949/4960f2cf29950697s.png)

You will see that my previous smart_v9_production.request_histories_external and smart_v9_production.request_histories_external_error disappear???
but actually they are not really disappear or override ...when I execute the drop external table command , they are reappeared as if they never gone..and the data in table is still in .
![Markdown](http://i4.piimg.com/1949/80372eab6d2dd6ads.png)

anybody having any idea is welcome ..

**Comment by jianlirong** [comment]
First of all, this is the expected behaviour according to the code, and has nothing to do with the external tables.

The output of \d is to list all the visible relations. Here is the definition of "visible" according to the code:

```
/*
 * RelationIsVisible
 *		Determine whether a relation (identified by OID) is visible in the
 *		current search path.  Visible means "would be found by searching
 *		for the unqualified relation name".
 */
```
Please check your search path using the command "show search_path". Based on the output you posted, I think in your search path, the schema ework_production sits before the schema smart_v9_production. That's why only the tables with the name request_histories_external and request_histories_external_error in the schema ework_production are shown when using \d.

If you change the search_path through the command "set search_path" and make the schema smart_v9_production sit before ework_production, then you will see the tables with the name request_histories_external and request_histories_external_error in the schema smart_v9_production rather than in the schema ework_production when using \d.

Hopefully this will help.

Lirong
HashData

**Comment by jianlirong** [comment]
First of all, this is the expected behaviour according to the code, and has
nothing to do with the external tables.

The output of \d is to list all the visible relations. Here is the
definition of "visible" according to the code:

/*

 * RelationIsVisible

 *      Determine whether a relation (identified by OID) is visible in the

 *      current search path.  Visible means "would be found by searching

 *      for the unqualified relation name".

 */

Please check your search path using the command "show search_path". Based
on the output you posted, I think in your search path, the schema
ework_production sits before the schema smart_v9_production. That's why
only the tables with the name request_histories_external and
request_histories_external_error in the schema ework_production are shown
when using \d.

If you change the search_path through the command "set search_path" and
make the schema smart_v9_production sit before ework_production, then you
will see the tables with the name request_histories_external and
request_histories_external_error in the schema smart_v9_production rather
than in the schema ework_production when using \d.

Hopefully this will help.

Lirong

HashData

Lirong Jian
HashData Inc.

2016-07-26 16:51 GMT+08:00 GuoLiuFang <notifications@github.com>:

**Comment by GuoLiuFang** [comment]
@jianlirong Yes , you are right . But how can I see all the tables? when I make schema smart_v9_production sit before ework_production , then the tables with the name request_histories_external and request_histories_external_error in the schema smart_v9_production appear.But ework_production table with the same name "disapear". How can I see all tables at the same time .

**Comment by jianlirong** [comment]
@GuoLiuFang, actually the pg_class catalog table has the information of all
tables. But I guess the following query may give you what you want:

SELECT n.nspname as "Schema",
  c.relname as "Name",
  CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' WHEN 'i' THEN
'index' WHEN 'S' THEN 'sequence' WHEN 's' THEN 'special' END as "Type",
  pg_catalog.pg_get_userbyid(c.relowner) as "Owner", CASE c.relstorage WHEN
'h' THEN 'heap' WHEN 'x' THEN 'external' WHEN 'a' THEN 'append only' WHEN
'v' THEN 'none' WHEN 'c' THEN 'append only columnar' WHEN 'f' THEN
'foreign' END as "Storage"
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r','v','S','')
AND c.relstorage IN ('h', 'a', 'c','x','f','v','')
      AND n.nspname <> 'pg_catalog'
      AND n.nspname <> 'information_schema'
      AND n.nspname !~ '^pg_toast'
      AND n.nspname <> 'gp_toolkit'
ORDER BY 1,2;

This query is almost the same as "\d", but skips the relation visibility
check, so you can see all tables at the same time.

Lirong Jian
HashData Inc.

2016-07-27 11:06 GMT+08:00 GuoLiuFang <notifications@github.com>:

**Comment by GuoLiuFang** [comment]
@jianlirong Great ! The way you tell me works fine .Is this a bug or something? why list all the table is complicated？Is there an easy way to view all the table I have created in different schemas?

**Comment by jianlirong** [comment]
As I mentioned before, this is an expected behaviour, not a bug.

Actually the logic of the query I posted in the last email is quite simple
if you check it more carefully, just a left join between two catalog
tables, pg_class and pg_namespace. It looks a little bit "complicated" just
because I want the output of that query is almost the same as the one of
"\d".

And to be honest, I really don't know whether there is an easy way like
"\d" to view all the tables created in different schemas.

Lirong Jian
HashData Inc.

2016-07-28 10:35 GMT+08:00 GuoLiuFang <notifications@github.com>:

**Comment by GuoLiuFang** [comment]
@jianlirong  Thanks, OK . I think I can close this issue now.
