### ISSUE TITLE
ALTER TABLE <table_name> SET SCHEMA <schema_name> does not properly cascade the schema change from the root partition through the children.

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#9903]
### Greenplum version or build
5.19

### Expected behavior
Set schema on the root partition properly cascades to the children unless 

### Step to reproduce the behavior
```
alter table dba.test_sat_account_daily_class_master set schema ods_base;
alter table ods_base.test_sat_account_daily_class_master rename to sat_account_daily_class_master;
```
Manually check the ods_base schema to see if the Children have been properly moved.

**Comment by Eulerizeit** [comment]
The was reported to me in a conversation I have not tested it yet.

**Comment by d** [comment]
This is a known behavior in Greenplum partitioning code (in 4.3, 5.X, 6.X): moving a table to a schema only moves that individual table. Specifically, moving a root table does _not_ move any descendant tables. Conversely, you're allowed to move a constituent table without moving all other members in a partition. Now this has been known to cause headaches in `pg_dump` and friends, but what is the expected behavior?

**Comment by d** [comment]
I can see the intuition behind the desired requirement that "all tables in a partition move into the same namespace". However, such a feature pretty much cannot be reasonably offered unless we also enforce this invariant all the time: i.e. you have to ensure that members of a partition hierarchy are always in the same schema. Otherwise you easily end up with a partition (root) table that is "immovable".

**Comment by ashwinstar** [comment]
Even upstream implementation of Partition doesn't cascade the `SET SCHEMA` to child when invoked for parent. It only affects the table specified in the command. Hence, I don't think we have any intent to change this behaviour.
